### ISSUE TITLE
Reimplement AlgoliaExplainResults

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#1]
Previously in algoalisearch v2 we had [AlgoliaExplainResults](https://github.com/algolia/algoliasearch-client-js/blob/0151bc813263d942c7cfbb3859cb500f4cb16d1f/src/algoliasearch.js#L127).

Would it be a good idea to reimplement it in the upcoming V2 helper?

**Comment by vvo** [comment]
I do not think this is a priority somehow since it never got asked since Mar 20, @redox @bobylito We close it?

**Comment by bobylito** [comment]
I don't know how helpful it is. I guess @redox could give us some light on that :)

**Comment by redox** [comment]
Hmmm, last time I used it was months ago. The idea was to be able to display the attributes that matter the most depending on the matched words -> but in most cases you know exactly what you want to display: no need of such algorithm. I think we should either close it or store it somewhere for archiving.

**Comment by vvo** [comment]
Ok so we can close this since it's already archived in github (and I will pay you a beer if we ever need to resurrect it)
