### ISSUE TITLE
algoliasearch.helper is not on jsDelivr website/CDN

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#11]
Can you have a look why @bobylito?

We need it for V3 release of course.

**Comment by vvo** [comment]
So it's on the CDN (http://cdn.jsdelivr.net/algoliasearch.helper/1.0.0/algoliasearch.helper.min.js), not on the website.

Enough for V3, I guess the website takes some time to udpate.

**Comment by jimaek** [comment]
We are working on a full website redesign and updates to our API to make things much prettier with instant updates. The files themselves are already uploaded immediately after merging, you can rely on that and simply build the URL yourself until then.
You can always reach out to me via email if you need anything :)

P.S. Its live http://www.jsdelivr.com/#!algoliasearch.helper

**Comment by vvo** [comment]
Thanks @jimaek, do you have something that warned you we were talking about jsDelivr? :)

**Comment by jimaek** [comment]
I always monitor `jsDelivr` mentions around the web including Github :) 
Pro-active support...

**Comment by redox** [comment]
Like it :+1:
