### ISSUE TITLE
isRefined is not checking if the attribute has a numeric refinement

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-helper-js#110]
`isRefined` is checking if it a facet or disjunctive facet has a refinement; we should also check it it's an attribute with a numerical refinement.

**Comment by bobylito** [comment]
Well I think hasRefinement would be a better candidate to get if an attribute has any kind of numeric refinement. isRefined has more parameters which are not consistent between facets and numeric filters.

**Comment by redox** [comment]
Hmm, ok but: https://github.com/algolia/algoliasearch-helper-js/blob/master/src/algoliasearch.helper.js#L348-L355

**Comment by bobylito** [comment]
@redox what do you mean?

**Comment by redox** [comment]
Sorry, I meant currently `isRefined <=> hasRefinements` that's why I was thinking it should handle it.
