### ISSUE TITLE
Display warning msg when using disjunctive methods on regular facets

### ISSUE THREAD

**Issue by seafoox** [algolia/algoliasearch-helper-js#116]
In the case I initialize regular facets, like that:
```
{
      ...
      params: {
        hitsPerPage: 4,
        facets: [
          'category',
          'brand'
        ]
      }
    }
```
And then use the wrong method `helper.addDisjunctiveRefine("category", "Electronics")`, instead of `helper.addRefine("category", "Electronics")` - I'd be great then to display a warning message in the JS console. Same in the opposite case.

**Comment by redox** [comment]
I thought we raised an exception? I would definitely go for exceptions instead of logging.
