### ISSUE TITLE
Setters/getters for misc parameters

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#12]
Add functions to set and get the value for any parameters that will be used for the the search.

**Comment by bobylito** [comment]
A generic getter would be enough : `helper.get( parameterName )`

The setter part is handle by setQueryParameter.

**Comment by redox** [comment]
Yes, `helper.getQueryParameter(name)` to fit its setter friend's naming.

**Comment by bobylito** [comment]
Sure! :)
