### ISSUE TITLE
Allow passing array of refinement values

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-helper-js#120]
Today, if I want to add multiple refinement values on the same facet, I'll have to do:

```javascript
helper.addDisjunctiveRefine('facetName', 'foo');
helper.addDisjunctiveRefine('facetName', 'bar');
helper.addDisjunctiveRefine('facetName', 'baz');
```
Would it be possible to add the handling of arrays, like so:

```javascript
helper.addDisjunctiveRefine('facetName', ['foo', 'bar', 'baz']);
```
Or do you think it may conflict for other uses of faceting?

**Comment by bobylito** [comment]
TBH your first example could just be : 
```javascript
helper.addDisjunctiveRefine('facetName', 'foo');
          .addDisjunctiveRefine('facetName', 'bar');
helper.addDisjunctiveRefine('facetName', 'baz');
```

**Comment by pixelastic** [comment]
I was more concerned about handling facet values as variables.

Handling the array case can be as easy as:

```javascript
function addDisjunctiveRefine(facetName, facetValue) {
  if (Array.isArray(facetValue)) {
    facetValue.each(function(value) {
      addDisjunctiveRefine(facetName, value)
    }
   return
  }

  // normal code
}
```

But in any case I'm okay with being pragmatic and waiting for a real world example of a user needing this feature
