### ISSUE TITLE
helper.isDisjunctiveRefined() returns true or undefined

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#123]
Using `helper.isDisjunctiveRefined(name, value)` when the value is not refined, I get `undefined`.

I would expect to get either `true` or `false`.

Is this expected behavior?

If not, I will PR :-)

**Comment by bobylito** [comment]
Another topic that we can discuss, shall be stay with falsy/truthy values
or should we force real booleans? :) What do you think?

On Mon, Jun 29, 2015 at 9:41 AM, Vincent Voyer <notifications@github.com>
wrote:

> Using helper.isDisjunctiveRefined(name, value) when the value is not
> refined, I get undefined.
>
> Is this expected behavior?
>
> If not, I will PR :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/algolia/algoliasearch-helper-js/issues/123>.
>



-- 
Alexandre Stanislawski
Software Engineer
Algolia

**Comment by redox** [comment]
I think we should force real booleans for all `{is,has}Method`.

**Comment by vvo** [comment]
Yes I think when a method says "isSomething" most of the time you would expect true/false booleans. Not falthy values.

Mostly because some templating languages/utilities will check for === false === true when doing conditions.

**Comment by bobylito** [comment]
Good for me! SHHOOOTT :D (you mentioned that you wanted to do some PRing
@vvo :) )

On Mon, Jun 29, 2015 at 9:55 AM, Vincent Voyer <notifications@github.com>
wrote:

> Yes I think when a method says "isSomething" most of the time you would
> expect true/false booleans. Not falthy values.
>
> Mostly because some templating languages/utilities will check for ===
> false === true when doing conditions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/algolia/algoliasearch-helper-js/issues/123#issuecomment-116509648>
> .
>



-- 
Alexandre Stanislawski
Software Engineer
Algolia
