### ISSUE TITLE
Add an example to the tutorial on how to store/retrieve/set the state from/to the url bar

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#127]
It could be cool to have your input on how to synchronize a search interface with/from the url bar.

And having it in the tutorial would help when building instant search uis

**Comment by redox** [comment]
:+1:

**Comment by redox** [comment]
I'm playing a bit around for a while and I'm less and less convinced by a lot of attributes flooding the URL like with JSON-encoded array and so on `?q=Test&instant=1#q=Test&page=0&refinements=%5B%7B%22categories%22%3A%5B%22Accessories%22%5D%7D%5D&numerics_refinements=%7B%7D&index_name=%22magento_default_products%22`

I think I would go for the same encoding we use for the `browseFromCursor` implementation; something like `?q=Test&params=#{Base64.encode "......"}`

What do you think?

**Comment by vvo** [comment]
So for my latest demo I used jQuery.param and jQuery.deparam to serialize a deep JSON object to the url.

It works well but still a bit verbose since I am storing the full state into the url (like your JSON solution).

While a better strategy would be to store only the diff between all the default parameters/the refined parameters. So that in the end what we store in the url is only the refined parameters/modified parameters.

URLs could then look like: `https://website.com/search.html?query=something&facetsRefinements[category][]=bananas&page=2`

To serialize a JSON object with readable querystring parameters, all we have to do is use $.param and $.deparam (extraneous plugin for deparam).

I would not go with JSON stringify in URL (ugly), neither with the cursor base64 approach (cryptic).

But rather do simple query string serialization with either:
- $.param and $.deparam
- https://github.com/hapijs/qs
- https://github.com/vjeux/URLON

All of them support nested objects well

This would allow to have clean and short urls.

Then the question will be, do we include those shortcuts into the helper browser build? #40 

Let's discuss this after the "how to serialize" question is solved.

**Comment by vvo** [comment]
Also when doing a pushState you should make sure you are not pushing a encoded string but rather a decoded one so that things like [].. are not encoded. (decodeURIComponent)

It will work well and will hide the hideous % to the user. When he will copy paste in any client those will be converted to encoded form.

**Comment by redox** [comment]
Yeah I think we're on the same page. I'm happy with https://github.com/hapijs/qs syntax :)

**Comment by bobylito** [comment]
Hey, late to the party here :)

I agree on the syntax part, that we really ought to find something that is nicer than just the plain json in the URL.

I also think that we don't want to have the full state in the url. Just the bare minimum.

I made a synchronisation plugin for the helper, but it doesn't do the nice url part (but you can choose what parameters you want to put in the URL, it has a smart way to either add a new state or just update the current one). Maybe @vvo you could start upon that? https://github.com/algolia/algolia-ui-kit/blob/master/src/setup/url.js and it is used here https://github.com/algolia/algolia-ui-kit/blob/master/src/index.js#L37-L79
