### ISSUE TITLE
use standard formatter

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#128]
To end issues about style and stop having to reformat every line of code written by different people, we could use the `standard` formatter: https://github.com/feross/standard

- have a look at the predefined [rules](https://github.com/feross/standard#rules)
- there is no configuration only a standard style builtin
- there is an automatic formatter and [editor plugins](https://github.com/feross/standard#editor-plugins)
- it's basically like [gofmt](https://golang.org/cmd/gofmt/) but in JavaScript
- it's based on eslint

I would be happy to switch all our JavaScript projects to standard format and start building things the fastest way instead of wrapping our mind and our code to the current project lead preferences.

So that you never find yourself contributing to an Algolia project and using your valuable time to align things, put a space there and there, remove a space there, fight with parenthesis, brackets, equals. 

A good number of projects are using standard, including the whole [npm codebase](https://github.com/npm/npm/blob/8c9fe9ce196c7f99b374ec5e45a1298e27b6d6e7/package.json#L175).

What do you think?

**Comment by redox** [comment]
:+1:

**Comment by bobylito** [comment]
Cool :) PR it? :)

On Wed, Jul 1, 2015 at 12:04 PM, Sylvain Utard <notifications@github.com>
wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/algolia/algoliasearch-helper-js/issues/128#issuecomment-117576457>
> .
>



-- 
Alexandre Stanislawski
Software Engineer
Algolia

**Comment by vvo** [comment]
I will!

**Comment by bobylito** [comment]
Thanks :)

**Comment by vvo** [comment]
So `standard` helps but still leave a lot of cases unresolved like writing `var a = [ 1, 2 ]` or `var a = [1,2]`  etc..

This will be a good first pass but we will move to http://jscs.info/ soon so that we end style conversations for good!

**Comment by pixelastic** [comment]
Oh good, one style guide to rule them all. I'm in favor of that. For jscs, we could just use one of the predefined style guide ([AirBnB](https://github.com/airbnb/javascript/tree/master/es5) for example) and move on.

**Comment by vvo** [comment]
No convinced by JSCS nor standard so I forked standard just like uber did for instance https://github.com/uber/standard.

**Comment by bobylito** [comment]
What's your arguments against standard or JSCS? (just curious)

**Comment by vvo** [comment]
So I have detailed pro/cons and whys in #131

**Comment by vvo** [comment]
was done
