### ISSUE TITLE
should the helper throw on undeclared facet toggleRefine() usage?

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#130]
Referencing this code: https://github.com/algolia/algoliasearch-helper-js/blob/f8d33b99337700f325438f7778c0c78537850dbd/src/algoliasearch.helper.js#L222-L228

Should we throw instead of just console.log()? A console.log can silently fail and will maybe slow down the debugging from the user point of view.

While a throw would break the application and thus would force the developer to debug, and find the error message in console.

**Comment by redox** [comment]
Oh yes we should !

**Comment by bobylito** [comment]
Yes! :)
