### ISSUE TITLE
Create an event triggered when a search request is sent

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#136]

**Comment by redox** [comment]
What is the underlying use-case @bobylito ?

**Comment by bobylito** [comment]
Synchronising helpers :)

On Mon, Jul 6, 2015 at 3:06 PM, Sylvain Utard <notifications@github.com>
wrote:

> What is the underlying use-case @bobylito <https://github.com/bobylito> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/algolia/algoliasearch-helper-js/issues/136#issuecomment-118849163>
> .
>



-- 
Alexandre Stanislawski
Software Engineer
Algolia
