### ISSUE TITLE
Use an immutability library for arrays and objects in SearchParameters

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#14]
Although the state is mostly immutable in SearchParameters, the inner structures based on array and objects are not due to their nature of native objects. It would be nice to use a library like Immutable to change the implementations of those structures. We could also benefits from data structures like Set or OrderedMap.

We should also make sure to leak the very minimal amount of abstractions to the users...

**Comment by bobylito** [comment]
Conjunctive, disjuncive and exclude facet refinements should be stored in sets

**Comment by Jerskouille** [comment]
Pretty scared of the `JSON.stringify(state)` of this. Agreed if we handle URL parameters with the helper.

**Comment by bobylito** [comment]
I have the same kind of fear, that's why I explicitly mentionned that we shouldn't leak to the user. It's for internal purpose only.

**Comment by vvo** [comment]
I do not understand the fear around JSON.stringify, where it is (would be?) used?

thx

**Comment by bobylito** [comment]
If we expose objects that are much more complex that plain objects or array, what would their serialization? That's the question. I guess you question is right in the sense that if we stringify an object it'll be pure json. Then no need to worry... yet I think it's better that the users thinks the values are simple js structures.

**Comment by bobylito** [comment]
see #105
