### ISSUE TITLE
API proposal: `algoliasearchHelper.ux` namespace or `algoliasearch-ux-helper-js` module?

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#141]
Let's say we wanted to provide a programmatic way to:

- sync the url page with the current state (#138)
- create a slider widget based on one of the facets
- create a hierarchical navigation widget
- create a checkbox list widget
- create an instant search bar
- create an autocomplete search bar

Where should we put this? Either in the helper (algoliasearchHelper.ux) or in another module?

[algolia-ui-kit](https://github.com/algolia/algolia-ui-kit) has already a set of react components you can instantiate with html tags but we rather have the programmatic version also. This is what we will be looking for when building a website search.

Putting all widgets in the helper would be handy for users since they will only have to load the js client and the helper to build a good search.

Putting widgets in a separate module is also an option but then when building your search you would have to load 3 files.

I would go for a new module like `algoliasearch-ux-helper-js` and start from here.

**Comment by pixelastic** [comment]
Hmm.

> - create a slider widget based on one of the facets
> - create a hierarchical navigation widget
> - create a checkbox list widget
> - create an instant search bar
> - create an autocomplete search bar

Isn't that the scope of the ui-kit?

**Comment by vvo** [comment]
> Isn't that the scope of the ui-kit?

Yes it is. So the idea would be to wrap the ui-kit in a programmatic interface and provide it as an easy to use module to build your search.

**Comment by pixelastic** [comment]
I've just read your other proposals, I better understand the programmatic side of what you're suggesting.

On one hand we have the UI kit to deal with everything that is UI-related but that should only depend on the helper for its internal logic. And that makes sense.

On the other hand we have the core algoliasearch module and the helper that both provides a way to interact with the search in more or less advanced situations but leaves the UI aside.

It seems confusing to me to have a new part, in between the helper and the ui kit. I would still put any UI-related code in the UI kit, and any internal helper methods into the helper but subdividing it by `ux` seems  weird. I would have a hard time deciding if something is helper-ux related or ui-kit related.

**Comment by vvo** [comment]
Ok so we may need to make ui-kit a programmatic interface.

**Comment by bobylito** [comment]
I agree with @Tim. Conceptually we should avoid circular dependencies
between those two modules.

Also even though the ui kit doesn't provide simple wrapper functions to
instantiate the components, one can already use them directly by requiring
them. We could easily create them, but that would on the ui-kit side to
discuss it.

**Comment by vvo** [comment]
Closing as this is a ui-kit issue
