### ISSUE TITLE
Can't add array of NumericRefinement in addNumericRefinement

### ISSUE THREAD

**Issue by chrisyeung1121** [algolia/algoliasearch-helper-js#148]
I have an array of codes like the following

``` javascript
$('.date-field').on('change', function() {
  helper.clearRefinements('occupied_at_i');
  var arrayOfDates = addDateFilters();
  _.forEach(arrayOfDates, function(n) {
  helper.addNumericRefinement('occupied_at_i', '!=', n);
  });
  helper.search();
});
```

I remembered once I tried I could get an array of values get meets the same operator but somehow I can't repeat it again. 

I tried: 

    helper.addNumericRefinement('occupied_at_i','!=',1233)
    helper.addNumericRefinement('occupied_at_i','!=',1234)

    helper.getRefinements('occupied_at_i')

And I got the following:

``` bash
Object
  operator: "!="
  type: "numeric"
  value: 1234
  __proto__: Object
```

Instead I want to get the following: 

``` bash
Object
  operator: "!="
  type: "numeric"
  value: [1233, 1234]
  __proto__: Object
```

What should I do?

**Comment by Jerskouille** [comment]
I believe you're right, we seem currently [override the value][1].

[1]: https://github.com/algolia/algoliasearch-helper-js/blob/master/dist/algoliasearch.helper.js#L5685

**Comment by redox** [comment]
Yes indeed, that's reported in https://github.com/algolia/algoliasearch-helper-js/issues/35. @bobylito could we work on that in the next few days?

**Comment by bobylito** [comment]
It's on my todo!

**Comment by chrisyeung1121** [comment]
Cheers!

**Comment by bobylito** [comment]
Would it be ok if the API accepts arrays only for = and != operators? Or should we go for the same api that would construct a list for = and !=, while still keeping the same behaviour (override) for the other operators?

**Comment by redox** [comment]
> Would it be ok if the API accepts arrays only for = and != operators? Or should we go for the same api that would construct a list for = and !=, while still keeping the same behaviour (override) for the other operators?

Even if I don't see right now a use-case for that, I assume it can happen (especially when you generate the filters programmatically). Anyway, I don't think it would change anything in the underlying implementation, isn't it?
