### ISSUE TITLE
[hierarchicalFacets] helper.state.hierarchicalFacetsRefinements format

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-helper-js#160]
Following #137 

In the ```helper.state.hierarchicalFacetsRefinements``` the value(s) should be store in an array to be consistent with ```disjunctiveFacetsRefinements``` and ```facetsRefinements```.

That is useful when you handle the storage of the refinements in the url to be generic.

for example:
```
{
  categories: "Accessories"
}
```
should be
```
{
  categories: ["Accessories"]
}
```

**Comment by vvo** [comment]
@maxiloc There can be only one refinement for a hierarchical facet, thus putting it an array would lie

**Comment by vvo** [comment]
At some point, we may want to have multiple leaf of a hierarchical navigation opened so yes I will make it an array :)
