### ISSUE TITLE
[hierarchicalFacets] Sorting

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-helper-js#162]
Following #137

Can we add a way to disable the selected refinement to go on top when you refine. So that every refinement keep the same order not matter what is refined

**Comment by vvo** [comment]
Implemented: https://github.com/algolia/algoliasearch-helper-js/tree/babd91a94002ad78aed0388fcb06d04eb278d8a5#specifying-a-different-sort-order-for-values
