### ISSUE TITLE
[hierarchicalFacets] Unselect level0

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-helper-js#164]
Following #137 

![0ujzmmvdwr](https://cloud.githubusercontent.com/assets/1689007/8880606/60cad5a6-323a-11e5-9f24-09dbd436e95c.gif)

When you unselect a level0 that have a level1 refined it does not unselect level0. See the gif

**Comment by vvo** [comment]
@maxiloc I was not able to reproduce it, can you show me the code you are using and the objects values? If you are using objects with

```json
{"categories.lvl0": ['cat1', 'cat2']}
```

I am not sure the current implementation handles it.

**Comment by vvo** [comment]
Oh wait, your flow is:

```js
helper.toggleRefine('root > sub');
helper.toggleRefine('root');
```

Now I get it, yes it's a bug

**Comment by vvo** [comment]
Also I am not sure this is what you want, when clicking on the parent level which is not the current selected category, maybe you DO want to see all the accessories.

**Comment by vvo** [comment]
forget about it, yes I am fixing this

**Comment by maxiloc** [comment]
:+1:
