### ISSUE TITLE
API Proposal: Sorting facet values

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#178]
following #38,

After discussing the API will be hosted by the SearchResults object. We will introduce 2 new functions to cover the needs for sorting and deprecate the previous `getFacetByName`.

```javascript
// RefinementValue is {name : string, count: number, isRefined : boolean }
results.getFacetValues('categories', {
  sortBy: ['isRefined:desc', 'count:desc'] // predicate list : string[] || sorting function :  (a: RefinementValue, b: RefinementValue
});
// Returns RefinementValue[]
// [ {name: 'skirt', count:'3', isRefined:true}, 
//   {name: 'jeans', count:'15', isRefined:false},
//   {name: 'pull', count:'10', isRefined:false} ]

results.getFacetStats('customerReviewCount');
// Returns
// {
//   "max": 7461,
//   "avg": 157.939,
//   "min": 1
// }
```

Checklist:

- [x] deprecate `getFacetByName`
- [x] implement `getFacetStats`
- [x] implement `getFacetValue`
- [x] update readme
- [x] update sample
- [x] document RefinementValue type

**Comment by bobylito** [comment]
Well that's definitely something we want for sure :)

PRO's : 
 - consistent with the current API of hierarchical facets
 - pretty straightforward

CON's : 
 - as is, not backward compatible (would either need to have both API support, or ditch support)
 - everything is inside the helper (high coupling, not modular)
 - it's complex to change the ordering on the fly

I would love to have this feature as something more external. A method that would let you get the results ordered properly on the results object maybe?

**Comment by vvo** [comment]
> I would love to have this feature as something more external. A method that would let you get the results ordered properly on the results object maybe?

Yes that's a good idea if we advocate the use of `results.getFacetByName` more.

So smg like:

```js
results.getFacetByname('popularity', {
  sortBy: ['name:asc', 'count:desc']
});
```

?

**Comment by bobylito** [comment]
Actually that could work pretty well :)

**Comment by redox** [comment]
I would rather use `value` instead of `name`. Then the question is do we use `value:asc` or `asc(value)` to use the same convention than our API :+1:

**Comment by vvo** [comment]
> value:asc or asc(value)

I feel `asc(value)` is harder to read (A little bit like [yoda conditions](https://en.wikipedia.org/wiki/Yoda_conditions): `if (2 === claps.length)`

> I would rather use value instead of name

Yes!

**Comment by redox** [comment]
> I feel asc(value) is harder to read (A little bit like yoda conditions: if (2 === claps.length)

Totally agree with you, but I was surprised reading a new format. Also the thing is that we only have value or count in your example, what if I want to sort that with a custom function? (like put the refined values on the top then the values, or like specific parsing of the value + sort)

**Comment by vvo** [comment]
> Totally agree with you, but I was surprised reading a new format

I did not know about the current format, where do we use it?

> what if I want to sort that with a custom function? (like put the refined values on the top then the values, or like specific parsing of the value + sort)

Then you can have `sortBy: function(a, b) {}`(array.sort style) or `sortBy: function(a) {}` (lodash).

Or since you know how to sort with a function, you might just do the sort yourself. But adding the function to our API is priceless, we can just forward to lodash.

PS: Do you know why lodash have only one argument, what's the difference with array.sort()? (stable sort?).

**Comment by bobylito** [comment]
I don't think we need to be able to give a function. Indeed the number of parameters that can be sorted is already know : the value (key of data attribute), the count (value of the data attribute), if the value is refined. The only borderline case would i18n not in the data. 

Don't you think?

**Comment by bobylito** [comment]
One thing that I had in mind, though, would be to propose a set of functions to express and combine orders (sort functions). But I don't know if it's friendly enough : 

```javascript
var nameAlphabeticalOrder =...
var countOrder =
var refinedFirstOrder = 
var reverse = 
var combine = 

results.getFacetByname('popularity', combine(refinedFirstOrder, countOrder, reverse(nameAlphabeticalOrder));
```

But this has the advantages to : 
 - propose a single API
 - let the advanced user do a function
 - the advanced user can reuse existing orders, and implement just his own specific stuff

**Comment by redox** [comment]
> I did not know about the current format, where do we use it?

`customRanking` and `ranking` in your index settings -> not JS related, but still it's a notation.

> results.getFacetByname('popularity', combine(refinedFirstOrder, countOrder, reverse(nameAlphabeticalOrder));

I'm not a big fan of that kind of functional programming pattern, it looks too different compared to the rest of the code.

**Comment by bobylito** [comment]
> I'm not a big fan of that kind of functional programming pattern, it looks too different compared to the rest of the code.

It's confusing and different, I agree! Just wanted to expose alternatives here.

Ok so let's go for a double api? Something like that the following?
 ```
results.getFacetByname('popularity', {
  sortBy: ['isRefined:desc', 'name:asc', 'count:desc']
});

results.getFacetByname('popularity', function(a, b) {
  // a and b are objects that contains three properties : name, count, isRefined
  // should return a number like a sort function
});
```

**Comment by vvo** [comment]
> Ok so let's go for a double api? Something like that the following?

YES! :+1:

**Comment by vvo** [comment]
Small change: we will not have an 'isRefined' property (unless we add it everywhere but that would change the current output: (https://github.com/algolia/algoliasearch-helper-js/issues/137#issuecomment-125963761)

```js
results.getFacetByname('popularity', {
  sortBy: ['value:asc', 'count:desc']
});

results.getFacetByname('popularity', {
  sortBy: function(a, b) {
    // a and b are objects that contains three properties : name, count, isRefined
    // should return a number like a sort function
  }
});
```

**Comment by bobylito** [comment]
Continuing on the brainstorm we just had with @vvo. The current getFacetByName returns the object that is available in the SearchResults (of type http://algolia.github.io/algoliasearch-helper-js/docs/SearchResults.html#.Facet). If we do the implementation we were thinking, it would mean to change the return signature with an array of object instead of a plain object (object can't be sorted). This would be a breaking change, which would mean to release a new major version...

But we found a solution : Provide an alternative method to get access to data, in a sorted manner : `getFacetValues(facetName, sort)`. To be able to also get the stats as easily we would need `getFacetStats(facetName)`. This will look like : 

```javascript
helper.getFacetValue('categories', {
  sortBy: ['isRefined:desc', 'count:desc']
});
// Returns 
// [ {name: 'skirt', count:'3', isRefined:true}, 
//   {name: 'jeans', count:'15', isRefined:false},
//   {name: 'pull', count:'10', isRefined:false}]

helper.getFacetStats('customerReviewCount');
// Returns
// {
//   "max": 7461,
//   "avg": 157.939,
//   "min": 1
// }
```

And we should deprecate `getFacetByName`.

Also we think that the sort functions with 2 arguments are more idiomatic than the kind required by Lodash.

**Comment by vvo** [comment]
> And we should deprecate getFacetByName.

Yes and also maybe not expose too much nor document or use in tutorial the searchResults.facets/disjunctive etc..

So that we advocate to always use getFacetValues etc..

AWESOME!

> Also we think that the sort functions with 2 arguments are more idiomatic than the kind required by Lodash.

Yes :+1: 

Thanks for summing that up

**Comment by redox** [comment]
:+1: go for it

**Comment by bobylito** [comment]
I've implemented the feature and did the tests, after using our new API I feel that the option object is a bit awkward to use. I'm thinking of just passing the sortBy as the 2nd parameter instead of having to create an object that will only contain one property. 

```javascript
// from 
content.getFacetValues('city', { sortBy: ['name:asc'] });
// to
content.getFacetValues('city', ['name:asc']);
```

What do you think?

**Comment by vvo** [comment]
With the second API, adding more options (like a map: fn) will mean maintaining two different apis (array and opt object). 

I like the first one because ˋgetFacetValues(mandatory, option object)ˋ is a common pattern. Also sortBy: is more descriptive than just passing an array.

Otherwise the method should be called getSortedFacetValues smg like that. To be easily understood.

What do you think?

**Comment by bobylito** [comment]
I was strictly speaking about this case. I don't see any other options to add there, do you have an idea of parameter that would justify the use of this pattern?

**Comment by redox** [comment]
I think I can easily see some others:

```js
content.getFacetValues('city', {
  sortBy: ['name:asc'],
  includeRefinedValues: false,
  minCount: 42
});
```

**Comment by bobylito** [comment]
Ok cool then :) Let's keep it that way :)

**Comment by martinverdejo** [comment]
I was looking for a way to sort my facet results and found this page. not sure if the API described here is still in use. I only found [search_for_facet_values](https://www.algolia.com/doc/api-reference/api-methods/search-for-facet-values/#method-param-requestoptions) in the current documentation. but it doesnt provide a sorting capability other than [name and count](https://www.algolia.com/doc/api-reference/api-parameters/sortFacetValuesBy/). Is there a way for me to sort the facets by proximity to the search query?

**Comment by vvo** [comment]
@martinverdejo Thanks for the comment.

Could you open a new issue describing what you are trying to achieve in more detailed way? And is it linked to this particular project or a more generic question about how to use Algolia?

If the former, please post your question here: https://discourse.algolia.com/
