### ISSUE TITLE
[Hierarchical faceting feature] Improve the doc for multiple categories record

### ISSUE THREAD

**Issue by purban** [algolia/algoliasearch-helper-js#181]
It is not clear that you have to use an array on each level, right now it is only a string.

**Comment by vvo** [comment]
Can you precise what is not clear right now by linking or copy pasting text? Thx

**Comment by purban** [comment]
https://github.com/algolia/algoliasearch-helper-js/compare/master...purban-patch-readme?quick_pull=1

**Comment by redox** [comment]
Not sure I'm following the whole story, is it required to have an array of strings per level?

**Comment by vvo** [comment]
@redox No this is an option, you can have an array of values for a level or just a value. ok?

**Comment by redox** [comment]
> @redox No this is an option, you can have an array of values for a level or just a value. ok?

Totally guys :+1:
