### ISSUE TITLE
refine VS refinement, isRefined VS hasRefinements

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-helper-js#184]
We need to fix the naming of the refinements API, it's pretty confusing right now.

Today we have:

 * `addRefine` and `removeRefine`
 * `addExclude` and `removeExclude`
 * `addTag` and `removeTag`
 * `addDisjunctiveRefine` and `removeDisjunctiveRefine `
 * `addNumericRefinement` and `removeNumericRefinement`

I would:

 * alias+deprecate `{add,remove}Refine` to `{add,remove}FacetRefinement`
 * alias+deprecate `{add,remove}Exclude` and `{add,remove}FacetExclusion`
 * alias+deprecate `{add,remove}DisjunctiveRefine` to `{add,remove}DisjunctiveFacetRefinement`

Also, because `hasRefinements` checks the `numericFilters`, it's very confusing to use `isRefined`.

So I would:

 * deprecate `isRefined`, `isExcluded` and `isDisjunctiveRefined` -> I don't think we need them
 * <strike>make the `hasRefinements` handle the exclusion as well</strike>
 * alias+deprecate `isTagRefined` to `hasTag`

What do you think @bobylito ?

**Comment by bobylito** [comment]
Looks great, will make the API evolve in a nice way. I hope the v3 is not too far ahead so that we can get rid of those bad names.

**Comment by bobylito** [comment]
Merged on develop!
