### ISSUE TITLE
Too many facet values returned in the case a disjunctive facet is an Array

### ISSUE THREAD

**Issue by seafoox** [algolia/algoliasearch-helper-js#187]
It has been identified that when an attribute with multiple values (in an array) is used for faceting (using disjunctive faceting), the Helper returns more facet values that the number passed in `maxValuesPerFacet`.
That seems to be due to the way the help combines facet values coming from the 2 API call performed in order to get the Disjunctive behavior.

Is the case for that queries for instance:
```curl 'https://msyuozhs7n-dsn.algolia.net/1/indexes/*/queries?x-algolia-api-key=885146f167ba45da085ae6a4864c5e0d&x-algolia-application-id=MSYUOZHS7N&x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%203.7.5' -H 'Pragma: no-cache' -H 'Origin: https://demo.algolia.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36' -H 'content-type: application/x-www-form-urlencoded' -H 'accept: application/json' -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' --data '{"requests":[{"indexName":"content","params":"query=&query=&hitsPerPage=21&maxValuesPerFacet=16&page=0&facets=%5B%22type%22%2C%22category%22%2C%22tags%22%5D&tagFilters=&facetFilters=%5B%5B%22tags%3Abrunettes%22%5D%5D"}]}' --compressed```

It's a bug, since it's not expected, but could also be an interesting behavior/feature to expose in the Helper.

**Comment by bobylito** [comment]
This should at least be documented. Since we have a new doc that should be pretty nice. WDYT @seafoox ?

**Comment by seafoox** [comment]
We could document it, but don't you think we should update the helper to only return the number of expected facet values instead?

**Comment by bobylito** [comment]
Ok for the documentation / FAQ :)
