### ISSUE TITLE
Is there any way to get more facets_stats?

### ISSUE THREAD

**Issue by tquill** [algolia/algoliasearch-helper-js#194]
I'm looking to calculate additional metrics on ALL hits, like percentiles (25%, median, 75%, ect), and possibly things like standard deviation.

Is that possible?

I know I can calculate those based on the hits on the current page, but the results are very limited because I don't want the hitsPerPage too high.

**Comment by redox** [comment]
Hi @tquill,

unfortunately Algolia doesn't provide such advanced metrics/aggregations/stats features. Our current focus is more about full-text search, we might add it in the future but it's not on our short-term roadmap.

I'm closing the issue, but feel free to reply and contact us through email if you want to chat about it ;)
