### ISSUE TITLE
Ability to easily list refined attributes

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-helper-js#195]
To conditionally display the list of current applied filters OR/AND a `clearRefinements` button.

**Comment by vvo** [comment]
You mean something like http://algolia.github.io/algoliasearch-helper-js/docs/AlgoliaSearchHelper.html#getRefinements but giving you all refinements?

**Comment by redox** [comment]
> You mean something like http://algolia.github.io/algoliasearch-helper-js/docs/AlgoliaSearchHelper.html#getRefinements but giving you all refinements?

yes

**Comment by bobylito** [comment]
Fixed via #348
