### ISSUE TITLE
nbHits_plural not in helper's JSON result response

### ISSUE THREAD

**Issue by qcaron** [algolia/algoliasearch-helper-js#202]
Hi ! I have used the [Instant Search Tutorial](https://www.algolia.com/doc/tutorials/instant-search), with

    {{#nbHits_plural}}s{{/nbHits_plural}}

in the `stats-template`. But `nbHits_plural` is not in the JSON response.

I was thinking of testing the nbHits value but this does not seem possible in Mustache templates has it a logic-less templating library.

Is there a simple solution to test the number of results ? Or maybe you could add this boolean to the Helper response ? 

Cheers !

**Comment by redox** [comment]
Hi @qcaron,

yes you're right, `nbHits_plural` is not part of the JSON answer. You need to create such attribute before calling the `render` method, something like:

```js
answer.nbHits_plural = nbHits != 1;
hoganTemplate.render(answer);
```

I'm closing this issue, let us know if you need more details!

**Comment by qcaron** [comment]
@redox Thank you !

I did not notice but this is in the renderStats function:

    nbHits_plural: content.nbHits !== 1

It did not work and I changed it

    nbHits_plural: content.nbHits > 1

Now it is working! Thank you poiting this out to me! You may need to update the tutorial code then ;)

**Comment by redox** [comment]
> It did not work and I changed it to:

OK, depends on your language :) zero is plural in english /o\

**Comment by qcaron** [comment]
Indeed! This is the next thing I'll have to figure out ;)
