### ISSUE TITLE
hasRefinments throws Exception

### ISSUE THREAD

**Issue by BenWise9000** [algolia/algoliasearch-helper-js#204]
Throws Error: {disjunctiveFacetName} is not defined in the facets attribute of the helper configuration 

I believe this is due to the fact that it only calls helper.state.isFacetRefined() and doesn't change that call to helper.state.isDisjunctiveFacetRefined() for a disjunctive facet.

**Comment by vvo** [comment]
Hi @BenWise9000, thanks for reporting this bug, we did a correction and will soon release a patch for this.

Is it blocking you somehow right now?

thanks

**Comment by BenWise9000** [comment]
Hi Vincent,

It's not blocking me as I'm using the deprecated method for now. Wanted to
file a report so it can be improved over time.

Thanks for the fast response and for the great work that is Algolia.

Thanks, Ben.

On 8 September 2015 at 23:55, Vincent Voyer <notifications@github.com>
wrote:

> Hi @BenWise9000 <https://github.com/BenWise9000>, thanks for reporting
> this bug, we did a correction and will soon release a patch for this.
>
> Is it blocking you somehow right now?
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/algolia/algoliasearch-helper-js/issues/204#issuecomment-138567270>
> .
>



-- 
<http://www.catchoftheday.com.au/>

Ben Wise
PHP Developer

0432 981 636
ben.wise@catchoftheday.com.au
767 Springvale Rd, Mulgrave 3170
<http://www.catchgroup.com.au/> <http://www.scoopon.com.au/>
<http://www.mumgo.com.au/> <http://www.groceryrun.com.au/>
<http://www.yumtable.com.au/>

<http://www.facebook.com/CatchAustralia> <https://twitter.com/catchoftheday>
<http://instagram.com/CatchOfTheDayAU>
<https://www.linkedin.com/company/catchoftheday.com.au>
<http://blog.catchoftheday.com.au/>
