### ISSUE TITLE
Query parameter sent twice in the query params

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#205]
- on http://demos.algolia.com/instant-search-demo/
- looking at the network tab
- then clicking on a queries/* call
- then headers
- then scrolling to form data, clicking on view source
 - you will see this:

![2015-09-08-114759_772x79_scrot](https://cloud.githubusercontent.com/assets/123822/9731800/7d4ffea0-561f-11e5-9ba4-f0dade9d2bc2.png)

Which shows the double query=&query= parameter. So it means we send it twice in the parameters.

**Comment by bobylito** [comment]
Whooo nice catch :)
