### ISSUE TITLE
getFacetValues throws when no hits returned

### ISSUE THREAD

**Issue by olance** [algolia/algoliasearch-helper-js#208]
When a search returns no hits, calling `getFacetValues` for an existing facet will throw in the `extractNormalizedFacetValues ` function.

At [this line](https://github.com/algolia/algoliasearch-helper-js/blob/master/src/SearchResults/index.js#L434), `facet` is undefined because the `results.facets` array is empty, so trying to access `data` on `facet` raises an error:

```javascript
    if (results._state.isConjunctiveFacet(attribute)) {
        var facet = find(results.facets, predicate);
        var facetValues = map(facet.data, function(v, k) { // Uncaught TypeError: Cannot read property 'data' of undefined
```

I guess the problem would arise on lines [445](https://github.com/algolia/algoliasearch-helper-js/blob/master/src/SearchResults/index.js#L445) and [456](https://github.com/algolia/algoliasearch-helper-js/blob/master/src/SearchResults/index.js#L456) as well!

While it's easy enough to check for `nbHits` before calling `getFacetValues`, I guess it'd be better to safeguard the function internally :)

**Comment by redox** [comment]
Good catch @olance :) I would not use the `nbHits` but rather the existence of that facet in the results. What do you think @bobylito ?

**Comment by bobylito** [comment]
Very nice catch indeed, @olance. Thanks for reporting it.

@redox, yes it would be more reliable to avoid using nbHits and check the facets.

Will try to make it fit into tomorrow's release.

**Comment by olance** [comment]
My pleasure ^^

What I meant is that checking `nbHits` is a satisfactory workaround in my own case where this problem occurred, but as it could also happen when none of the returned hits "carry" the requested facet's attribute, I agree checking the facets would be the best option :)
