### ISSUE TITLE
expose state.getNumericRefinement(attribute, operator) as helper.getNumericRefinement

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#214]
When reading the numeric methods on the helper you get:
- helper.addNumericRefinement(attribute, operator, value)
- helper.removeNumericRefinement(attribute, operator, value)

But no helper.getNumericRefinement(attribute, operator).

Do you think it would make sense to expose it? We have state.getNumericRefinement but it's not obvious because other methods are on the helper instance.

**Comment by redox** [comment]
Yes, makes sense.

**Comment by bobylito** [comment]
`getRefinements` does the job no?

**Comment by vvo** [comment]
Yes but you then have to loop through it to find what you are looking for.
