### ISSUE TITLE
Url feature is broken on IE8

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#220]
So I have fixed one issue on IE8 (#219) but we have more: the [qs](https://github.com/hapijs/qs) module is not compatible with IE8 (and will never be).

I think it's time to think about dropping official IE8 support to something very easy: you want IE8 support? Insert this: 

```html
<script src="https://cdn.polyfill.io/v1/polyfill.min.js"></script>
```

And that's it. It's not a big dependency (6kb gzip)

I would stop supporting IE8, bump major on helper and clientjs, add a note on how to have IE8 support and move on. We are spending too much time on this browser while the polyfill service is really well working.

**Comment by vvo** [comment]
cc @algolia/javascript

**Comment by redox** [comment]
> I would stop supporting IE8, bump major on helper and clientjs, add a note on how to have IE8 support and move on. We are spending too much time on this browser while the polyfill service is really well working.

OK, go for it then!

**Comment by vvo** [comment]
:fire:

**Comment by bobylito** [comment]
We added a message saying that IE8 needs a polyfill. So we can close this one.
