### ISSUE TITLE
State to url => order of attributes

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-helper-js#221]
Following https://github.com/algolia/instantsearch.js/issues/128 

Can we keep the order in the generated url string compared to the trackedParameters

**Comment by pixelastic** [comment]
Just to clarify, what you would like is that given a `trackedParameters` of `['query', 'index', 'page']`, then you would like the url to look like `q=foo&idx=bar&p=0` (with the query string variables in the same order than the `trackedParameters` array?

This seems feasible for such an easy use-case, but will start to get complicated for the `attributes:*` that stores all the facets...

Could you expand on your use-case and why you would need this?

**Comment by maxiloc** [comment]
Yes the goal is to be able to have query, index and page before attribute so that it is easy to modify in the url. Right now you can not ensure that.

**Comment by bobylito** [comment]
What about the parameters that are already in the URL (before we add ours)?

**Comment by maxiloc** [comment]
For my integrations we can erase them

**Comment by maxiloc** [comment]
But it could make sense to keep them

**Comment by vvo** [comment]
Maybe since we are always ordering the parameters (https://github.com/algolia/algoliasearch-helper-js/pull/224) we are could be good here? Because modifying the parameters by hand is something WE developers only do..?

We just need to ensure to always loop using the same order.

Having always the parameters in the same order for everyone may be better here for us to debug/follow?

**Comment by maxiloc** [comment]
Yes that works but I would just put attributes at the end

**Comment by bobylito** [comment]
@vvo #224 is not related to that issue.

Predictability is a must :) So the order would be : named parameters, named attributes (we can specify attribute:price) , `attribute:*`, remaining parameters from the URL that are not ours?

**Comment by maxiloc** [comment]
@bobylito :+1:

**Comment by bobylito** [comment]
Will PR in qs so that it supports sorting keys.

**Comment by bobylito** [comment]
qs 5.2.0 released, let's get back to work! :D

**Comment by bobylito** [comment]
see #227
