### ISSUE TITLE
algoliasearchHelper.AlgoliaSearchHelper.getForeignConfigurationInQueryString

### ISSUE THREAD

**Issue by kokliKo** [algolia/algoliasearch-helper-js#226]
Hey, why does this method need to be hidden like this?
Would it be possible to make it accessible just under `algoliasearchHelper.getForeignConfigurationInQueryString`

Thanks!

**Comment by bobylito** [comment]
Thanks for report @kokliKo 

This is a static method. You can't access it through the instance. Maybe we could make an alias on the instance for ease of use.

**Comment by Jerskouille** [comment]
What about an alias on `algoliasearchHelper` ?

**Comment by bobylito** [comment]
because this is the root namespace and I don't think it's good idea to have a it too crowded, especially with tools.

**Comment by bobylito** [comment]
Will make a module containing all the function needed to deal with query string parsing / creation. This module will be exposed as urlTools on the root of the algoliasearch object.

**Comment by kokliKo** [comment]
Yay! Thanks :-)

**Comment by bobylito** [comment]
Released in 2.6.0!
