### ISSUE TITLE
When adding an attribute in both the facets and disjunctiveFacets, you cannot retrieve the stats

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-helper-js#228]
If you initialize the helper with:

```js
{
  facets: ['price'],
  disjunctiveFacets: ['price']
}
```

You cannot anymore get the `getFacetStats('price')` because both `isConjunctiveFacet` and `isDisjunctiveFacet` are `true` (expected) but the underlying `facet` object is only in one of them (in `disjunctiveFacets`).

**Comment by redox** [comment]
You can reproduce the bug running the dev application of https://github.com/algolia/instantsearch.js/tree/feature/price-ranges

**Comment by bobylito** [comment]
thanks for the bug report!

**Comment by vvo** [comment]
Be careful while solving this because this may be a usecase we are facing only because we are trying to reuse the same attribute with different UI widgets. While in most usecases you would have only one place where to refine "price" (right?)

**Comment by bobylito** [comment]
Careful is my second name #famouslastwords Making the lib bulletproof will help us I think ;)
