### ISSUE TITLE
removeNumericRefinement(attribute) 

### ISSUE THREAD

**Issue by AlexGaspar** [algolia/algoliasearch-helper-js#230]
Hi there,

[According to the README.md](https://github.com/algolia/algoliasearch-helper-js/blob/master/README.md#batch-numeric-filter-removal) we should be able to do `removeNumericRefinement(attribute)`

But if you look at the code, it looks like you need to specify at least the couple `(attribute, operator)`: https://github.com/algolia/algoliasearch-helper-js/blob/43bae7b06366effa13328500bf4bb59682157316/src/SearchParameters/index.js#L700-L732

Did you remove this functionality?

**Comment by bobylito** [comment]
Hi Alex :)

Thanks for your comment. Actually there are indeed three cases and you can do removeNumericRefinement(operator) :)

**Comment by AlexGaspar** [comment]
I guess you meant `(attribute)`

Not working for me, I've to explicitly call 
```removeNumericRefinement('foo', '<'). removeNumericRefinement('foo', '>')```

See below: 
![screen shot 2015-10-13 at 17 46 56](https://cloud.githubusercontent.com/assets/2635915/10459977/85f1c146-71d2-11e5-844f-3e89f37df649.png)

**Comment by bobylito** [comment]
Which version are you using?

**Comment by bobylito** [comment]
Ok I reproduced the error. Thanks for the report.

**Comment by AlexGaspar** [comment]
Thank you :)

**Comment by bobylito** [comment]
You're welcome, also had the opportunity to add more tests. Thanks to you, don't hesitate to contribute again! :)
