### ISSUE TITLE
AlgoliaSearchHelper: Simplify the hierarchical facets refinement

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#24]
To be able to build [such facet tree](http://jsfiddle.net/SpL3n/8/) without messy code.

(originally by @redox on https://github.com/algolia/algoliasearch-client-js/issues/35)

**Comment by redox** [comment]
The original demo is here: http://jsfiddle.net/sylvainutard/9KA3T/

**Comment by vvo** [comment]
doing in #137
