### ISSUE TITLE
Geo-search, how to make multiple bounding box or Polygon

### ISSUE THREAD

**Issue by kokliKo** [algolia/algoliasearch-helper-js#240]
The Algolia API can make a search on an union of bounding shapes.
To do so, we need to send multiple times the param insideBoundingBox or insidePolygon.

Unless I missed something, the helper only accepts to send these params once.
How do we handle that?

Thanks!

**Comment by bobylito** [comment]
Whooo... Do you have a working example of code with the JS Client? :)
