### ISSUE TITLE
Support for multiple queries

### ISSUE THREAD

**Issue by bndw** [algolia/algoliasearch-helper-js#242]
I currently use the [multiple query](https://github.com/algolia/algoliasearch-client-js/tree/develop#multiple-queries) pattern for batching requests with the algoliasearch-client-js. I'd like layer in the search helper to handle pagination, but it is not clear if the helper supports batching queries on multiple indexes.

**Comment by bndw** [comment]
I just took a quick, first, look at this code and noted a potential starting point.

1. Updating the [addIndex](https://github.com/algolia/algoliasearch-helper-js/blob/aca735467c49e90f4d1cbd7ccf7f4fe99d7b20d8/src/algoliasearch.helper.js#L392-L396) signature to accept multiple index names
2. The [search call site](https://github.com/algolia/algoliasearch-helper-js/blob/aca735467c49e90f4d1cbd7ccf7f4fe99d7b20d8/src/algoliasearch.helper.js#L709-L719) could pass those into the request builder
3. The request builder's [get queries](https://github.com/algolia/algoliasearch-helper-js/blob/master/src/requestBuilder.js#L16-L33) signature could accept multiple index names

Please let me know if I'm missing something and there's already a way to get batching/multiple queries with a decent way to manage pagination.

**Comment by bobylito** [comment]
Thanks @bndw for creating this issue. The helper does not currently support multiple queries batch. We don't know what would be the best way to implement that.

**Comment by avbrychak** [comment]
Would be a welcome addition indeed. I've faced this problem when I wasn't able to use batch queries from js client because it doesn't provide such useful functions like `getFacetValues()`.

**Comment by bobylito** [comment]
@bndw well your solution seems fine as long as the results will have the same facets. But this is not very  likely so one set of filters might not work on another. What about the pagination?

One solution could be to have a main index, and some secondary indices that will be queried only with a subset of the filters.

Another solution could be to have several helpers that we synchronize to make a single batch query and redispatch the different responses into their original helpers. That would  

What do you think?

cc/ @avbrychak

**Comment by bndw** [comment]
Hi @bobylito 

I worked around this issue by writing my own abstraction around `algoliasearch-client-js`, where I managed the pagination and facet state of each index manually.

Now that it's all said and done, my requirements may be a little different than most, so my original feature request may not be relevant. My requirement was to fetch a single set of results comprised of records from different indexes, where each index holds different types of records with different attributes. This meant the text query is the same against all indexes, but the facets and ranking are unique.

**Comment by pixelastic** [comment]
Hey @bndw,

I actually think your use-case is most common one: doing a query in several indices, each containing its own specific objects.

Would you have a public repo or website where we could have a look at the way you implemented that? This could give us some ideas for the best way to add it to the helper.

**Comment by bndw** [comment]
Hi @pixelastic,

Sorry for the slow responses. Unfortunately the implementation is not public. I'll look at pulling the relevant bits out for reference, but it likely won't be for another couple weeks.

The code is running in production at https://www.gratafy.com/?q=beer, where the results are a mix of data from multiple indexes paged independently.

**Comment by bobylito** [comment]
Closed in favor of #337
