### ISSUE TITLE
Clear refinements matching a specific criteria

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#25]
Something like:

```
helper.clearRefinements(function(facet, value) {
  return facet === "foo" && value.indexOf("bar") === 0;
});
```

imported from https://github.com/algolia/algoliasearch-client-js/issues/33

**Comment by bobylito** [comment]
It's definitely powerful to provide a function for filtering which parameters needs to be cleared. I'm wondering if we could something more to the point like : 

``` javascript
helper.clearRefinements( myFacetName );
```

Also we should think about the facet not all refinements are the same, and we may want to also insights on the type of refinement we want to clear. 

ping @redox

**Comment by redox** [comment]
Using a single `facetName` parameter is definitely a feature we want. Being able to pass a function as well is to handle the hierarchical refinements. For instance, to remove all refinements of a specific level we could do something like:

```
helper.clearRefinements(function(facet, value) {
  return facet === "categories" && value.indexOf("Level 1/") === 0;
});
```

**Comment by bobylito** [comment]
Facet refinement should be totally managed and shouldn't rely on people implementing this kind of function imho.
Ok for both the simple (facet name) and advanced (function) way of clearing though.

**Comment by Jerskouille** [comment]
Adding `function (facet, value)` won't be that trivial, because of the `numericRefinements` which are composed of `name`, `operator` and `value`.
We might imagine merging `operator` and `value` ?

**Comment by chrisyeung1121** [comment]
Just wondering if the problem I am facing is the one described in this issue?

I have a webapp that allows user to filter by `>=` and `<=` of the `daily_rate`.

`helper.addNumericRefinement('daily_rate','>=', $(this).val());`
`helper.addNumericRefinement('daily_rate','<=', $(this).val());`

And I want to be able to do `helper.clearRefinement('daily_rate','<=')`

Can I do that?
