### ISSUE TITLE
{add,remove}HierarchicalFacetRefinement methods?

### ISSUE THREAD

**Issue by Jerskouille** [algolia/algoliasearch-helper-js#250]
Here is what we currently have:

- Facet => `{add,remove}FacetRefinement`
- Disjunctive facet => `{add,remove}DisjunctiveFacetRefinement`
- Hierarchical facet => Only `toggleRefinement`
- Exclude => `{add,remove}FacetExclusion`
- Numeric => `{add,remove}NumericRefinement`
- Tag => `{add,remove}Tag`

We should probably add `addHierarchicalFacetRefinement` and `removeHierarchicalFacetRefinement` for consistency.

**Comment by vvo** [comment]
Yes agree!

**Comment by vvo** [comment]
Good for consistency but we should keep in mind that the hierarchicalFacet can only have one current refinement at a time, thus this is why I think add and remove where not implemented at first

**Comment by bobylito** [comment]
I would like to be able to select a refinement wether or not it is already define. I think it's pretty close to add with the other kind of filters, but we can only select one value. Do you think it's close enough?

I would prefer that over checking if it's already refined.

I don't see any problems with the remove.

What do you think?

**Comment by Jerskouille** [comment]
I think it makes sense @bobylito .

**Comment by bobylito** [comment]
any thoughts @vvo ?

**Comment by vvo** [comment]
so addHierarchicalRefinement would be an override? sort of?

**Comment by vvo** [comment]
To sum up, yes we need addHierarchicalFacetRefinement and remove, add should throw if we are trying to add a second refinement.

There's only one possible refinement for every hierarchical facet at any point in time.

Anyone can take this.
