### ISSUE TITLE
Proposal: Base path for hierarchical faceting

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-helper-js#251]
On ([magento](http://magento.algolia.com/sale.html#q=&page=0&refinements=%5B%7B%22categories%22%3A%5B%22Sale%22%5D%7D%5D&numerics_refinements=%7B%7D&index_name=%22magento_default_products%22)) we replace the default category page, by a search page.

What we do is refine the search on the selected category.
It's good but the only issue is that the hierarchical facet values display everything including categories and sub-categories that are not in the path of the current category.

The idea would be to add a filter at the beginning on the category. It's already possible to do so but the the hierarchical code is blocking it. It is caused by this line https://github.com/algolia/algoliasearch-helper-js/blob/master/src/SearchResults/generate-hierarchical-tree.js#L87

The fix would be to add a optional basePath that we would used here:
https://github.com/algolia/algoliasearch-helper-js/blob/master/src/SearchResults/generate-hierarchical-tree.js#L29

@vvo Do you see an issue with this ?

**Comment by vvo** [comment]
What you want is "initialRootPath" I feel. You already did some work but its not yet released and you are still experimenting in instantsearch.

Let me know when you are good, next steps:
- if initialiRootPath is better than prefixPath then change it so
- check everything is working with npm link in instantsearch
- update doc
- update helper changelog (UNRELEASED -- change)
- submit PR

Then we will do a release of the helper, then you will have to update instantsearch.js with this new option
