### ISSUE TITLE
Missing "exhaustive" on the hierarchical refinements

### ISSUE THREAD

**Issue by Jerska** [algolia/algoliasearch-helper-js#258]
Hierarchical refinements embed the same kind of information as the other ones, except the `exhaustive` attribute. It would probably make sense to also add it.

**Comment by bobylito** [comment]
So adding exhaustive on hierarchicalFacets items? Why not, I like consistency :). Would there be any problems to have an accurate values @vvo @redox ?

**Comment by vvo** [comment]
I do not follow what is the exhaustive attribute, can you precise?

**Comment by Jerskouille** [comment]
The fact that the counts of the values are exact.

**Comment by vvo** [comment]
So it is a flag to indicate that the count is exact, WFM
