### ISSUE TITLE
Expose aroundLatLng in results

### ISSUE THREAD

**Issue by escholtz** [algolia/algoliasearch-helper-js#261]
When `aroundLatLngViaIP` is used in the query, please expose latitude and longitude in the results. It looks like this `aroundLatLng` is returned by the algolia API but the helper does not expose it.

Intended use case is displaying approximate distance between the IP address and the individual results.

**Comment by bobylito** [comment]
Thanks @escholtz for reporting that. Will have a look!

**Comment by escholtz** [comment]
thanks @bobylito :+1:

**Comment by bobylito** [comment]
My pleasure @escholtz. Feel free to report any new issue or feature request :)
