### ISSUE TITLE
Query multiple Indexes

### ISSUE THREAD

**Issue by mspivak** [algolia/algoliasearch-helper-js#270]
I want to mix element from two different indexes in my results. Using the JS client I was able to do it like this: https://github.com/algolia/algoliasearch-client-js#multiple-queries

Is there a way to do it with the much more featured JS helper?

**Comment by pixelastic** [comment]
Hello @mspivak,

Unfortunatly no, the helper only listens and reacts to the state of one index at a time. You can instanciate two helpers, each targetting a different index. You might be able to make them listen to the same `input` and reconciliate results manually on your side.

Maybe you could also see if you can fit all your records in the same index? As indices are schemaless, you can put records of various types in it.

**Comment by bobylito** [comment]
Related to #337. Moving the discussion there.
