### ISSUE TITLE
Do not apply distinct for the second query of the disjunctive facets.

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#272]
For example my dataset contains tshirts and shoes and they all have colors. I apply a distinct on the colors, I would like to choose tshirts and see all the colors. I can't right now because the facet values only contains those in the result set (which is limited to a single color).

Would it make sense to not apply distinct to the secondary queries? Should it be an option?

cc/ @redox @vvo @pixelastic @kokliKo

**Comment by redox** [comment]
:+1:

**Comment by kokliKo** [comment]
Great idea!
I'm not even sure it should be an option, I think I'd do that by default.

**Comment by bobylito** [comment]
Definitely breaks the expected behavior :P Could be an option until v3?

**Comment by kokliKo** [comment]
I have no clue what's best.
(But I'm ok with waiting v3 if that's what you think is best.)

**Comment by redox** [comment]
> Definitely breaks the expected behavior :P Could be an option until v3?

it only add more values in the underlying refinement list, but anyway we set a maxValuesPerFacet; so I would not consider that as a major change.

**Comment by redox** [comment]
Oh but wait; we changed that behavior -> the faceting is always done BEFORE applying the distinct. Did you actually try it and experienced a diff?

**Comment by ricktbaker** [comment]
In our scenario.  We are using the instantsearch.js library and we have the group by set within algolia.   It's definitely applying the group by to the faceting as well.
