### ISSUE TITLE
Fix the reset point of the helper

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#273]
Sometimes we want to be able to fix a set of parameter in the helper. What we recommend now, it to set it programmatically when we initialize the helper. However if we reset the helper by clearRefinements or other methods, we might end up changing the initial value.
### API proposal

``` js
var search = new AlgoliasearchHelper();
search.addNumericRefinement('price', '=', 4);
search.setCurrentPage(3);
// price = 4, other > 4, page = 3
search.pinState({
  constants: [page]
});
search.addNumericRefinement('other', '>', 4);
search.addNumericRefinement('price', '=', 5);
// Changes the value, no problem
// price = 5, other > 4, page 3
search.setCurrentPage(3);
// Can't be changed, (throw an error here?)
search.clearRefinements();
// price = 4, other undefined, page 3
search.reset()
// Revert back to the pinned state
```
### Behavior

By default, all the values can still be changed, only the reset/clear functions will have their behavior modified. However, we sometimes want to have certain properties fixed once and for all. The constants can be a SearchParameters field or a specific facet (much like the filter API)

**Comment by vvo** [comment]
It looks like a great addition, I wonder what's the difference/use cases between this API and the one you talked in instantsearch.js ("constants")

**Comment by bobylito** [comment]
@vvo I need to update this proposition to be able to specify the behavior of the reset point : should it be a strict or soft fixed point.

**Comment by pixelastic** [comment]
```
search.pinState({
  constants: [page]
});
search.clearRefinements();
// price = 4, other undefined, page 3
```
I don't get why price is not reseted to `undefined`? Also shouldn't it be `constants: ['page']`?

I'm not found of `pinState`/`reset`. I'd rather have a symmetry. Couldn't we just have an `exportState`/`importState` instead?

**Comment by bobylito** [comment]
> I don't get why price is not reseted to undefined? Also shouldn't it be constants: ['page']?

It's because the example is not good :) Updating it.

> Couldn't we just have an exportState/importState instead?

It's already implemented, but it's not very convenient. 
https://community.algolia.com/algoliasearch-helper-js/docs/AlgoliaSearchHelper.html#setState
https://community.algolia.com/algoliasearch-helper-js/docs/AlgoliaSearchHelper.html#getState

**Comment by vvo** [comment]
I think the example is still a bit broken:
- the first comment says "other > 4" while its not yet set
- its ['page'] I believe

As for naming, just some randoms idea: freezeState, freezeSearchParameters, pinSearchParameters, resetState

**Comment by bobylito** [comment]
> I think the example is still a bit broken:
Erf true!



> As for naming, just some randoms idea: freezeState, freezeSearchParameters, pinSearchParameters, resetState

Great! Keep them coming. There are nice things here. Making the reference to SearchParameters is very good I think!

Implementation-wise I started to have a look and it can be tricky. We'll have to discuss :)

**Comment by pixelastic** [comment]
`freeze` implies that we cannot change it afterward for me, which is not the case. `pin` or `bookmark` better convey the idea of getting back to a specific state. Agreed for keeping the `SearchParameter` naming

**Comment by bobylito** [comment]
There is no actionable use case. Closing.
