### ISSUE TITLE
Batch queries and helper

### ISSUE THREAD

**Issue by kokliKo** [algolia/algoliasearch-helper-js#28]
Hey,

Using the helper with batch queries doesn't feel very natural right now. You have a "main" query, which can use all methods like toggleRefine(), and "extra" queries which cannot.

Do you think it'd be possible to make the helper handle all queries the same way?

Thanks!

**Comment by bobylito** [comment]
@redox @vvo Any thoughts?

Imho, I have faced the same questions myself and I think the way we handle the extra query does not feel very natural or consistent with the way we handle the main query.

**Comment by redox** [comment]
Feel free to refactor it. We just need to ensure the `searchCallback` is called with all underlying answers because we might need the result of an extra query to filter the main one.

**Comment by vvo** [comment]
Anything that can ease the use of the helper is good to take. Maybe propose a before/after example so that anyone can understand where we are going.

**Comment by bobylito** [comment]
Closed in favor of #337
