### ISSUE TITLE
Turn the helper js website into a more complete one

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#283]
Following our discussions on the fact that we should still focus on the helper and instantsearch.js is not the silver bullet (not right now, maybe never).

We currently have a documentation website for the helper: https://community.algolia.com/algoliasearch-helper-js/docs/

I propose to build a more complete website for the helper much like the https://community.algolia.com/instantsearch.js/ (less fancy) where we would summarize all the use cases of it:
- homepage (small example, getting started, what is the helper anyway? a state holder) in plain simple words for anyone
- helper logo
- helper readme should only be about running the stack like instantsearch.js
- API docs (like we have today, maybe restyled)
- tutorials
  - how to handle urls with the helper
  - what is a search state
  - vanilla + helper
  - ember + helper
  - angular + helper

And then, from the website algolia.com, link to this website.

@algolia/javascript what do you think?

**Comment by olance** [comment]
Yup, would be nice to have that :)
It would help better understand the usefulness of the lib, which looks quite geeky/obscure at first.

I think the doc could be reworked a bit. I find it quite confusing sometimes because there are many methods found both on State and Helper... sometimes I find it hard to understand what I should look at!

**Comment by vvo** [comment]
> on State and Helper... sometimes I find it hard to understand what I should look at!

I do agree with this, we need to organize the doc in a way where we gradually dig in details

**Comment by bobylito** [comment]
:+1:

**Comment by proudlygeek** [comment]
I agree with the fact that the JS helper is somewhat not really pushed as it deserves to be, having better docs with examples / tutorials would be great. :+1:

**Comment by lae25c** [comment]
Would love to help.

**Comment by bobylito** [comment]
Done!
