### ISSUE TITLE
Inconsistency between add and remove NumericRefinement

### ISSUE THREAD

**Issue by Jerskouille** [algolia/algoliasearch-helper-js#285]
Follow-up of https://github.com/algolia/instantsearch.js/pull/847 . In the helper:
- `addNumericRefinement(attribute, operator, value)` type-checks value and convert it to a float if it's a string
- but `removeNumericRefinement(attribute, operator, value)` just does a simple `===` comparison

Which means that:
```js
var val = /* ... */;
helper.addNumericRefinement('attribute', '=', val);
helper.removeNumericRefinement('attribute', '=', val);
```
is actually not guaranteed to work, which is, to me, weird.

**Comment by bobylito** [comment]
Thanks! Fixed in https://github.com/algolia/algoliasearch-helper-js/pull/284
