### ISSUE TITLE
similarSearch()

### ISSUE THREAD

**Issue by denu5** [algolia/algoliasearch-helper-js#289]
Would it be possible to add similarSearch() from the js-client to the search-helper? as far as i understand, search and similarsearch are interchangeable in the js-client. So, there could simply be a new private method similar to _search(), using this.client.similarSearch() instead of .search(), and the according public method is needed to be done as well.

I'd love to do a pull request, but I'm new to github and i could really need this feature asap, so treat me nicely please :)

**Comment by bobylito** [comment]
Hi @denu5 

Thanks for filling this issue. To be able to submit a PR, fork the project, commit on it, verify that the tests are passing, then submit a pull request by going back to the original project. Github made [a guide](https://help.github.com/articles/using-pull-requests/) about this subject and you can have a look at our [contributing guide](https://github.com/algolia/algoliasearch-helper-js/blob/master/CONTRIBUTING.md). We would be very happy to have a new contributor :)

**Comment by bobylito** [comment]
#diggingup

I think that this feature could be implemented as an attribute of the `SearchParameters` and with #337 it could make a lot of sense:
 - the main search for the `search`
 - a derived one for the `similarSearch`

WDYT @vvo?

**Comment by vvo** [comment]
Yes something like `searchMethod: 'search'`? But then it opens the way to browse :D

**Comment by bobylito** [comment]
It seems that the similar search is implemented using a different attribute using the same end point in the Algolia API. This means that some SearchParameters not using `query` but `similarQuery` would have the same effect as a call to `similarSearch()` on a JS client.

It's not sure how mature is this feature, but when we are sure we want to expose it, we'll document it properly. For now, let's not move forward with any change in the API as it is possible to use it already.
