### ISSUE TITLE
Avoid callback for outdated queries

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#29]
Depending on the network, it may happen that a request sent before another is received after. This should not happen, and shouldn't be left to the responsibility of the user.

**Comment by vvo** [comment]
Do you mean we want to "cancel" cases like:

```js
helper.search() //slow one, cancel it
helper.search() // fast one, get it
```

Would it be transparent for the user that he will only get results for second search? I guess if we are using an event emitter and the two requests were for the same search then it might not be a good idea to trigger it twice indeed.

But what if the user did two different searches?

**Comment by bobylito** [comment]
The helper is not meant for doing two different searches, the helper managed the state of the search : the whole state. If you are using 2 indexes, you probably should use two helper instances. Same for helpers based on two separates parts of a UI.

**Comment by bobylito** [comment]
Kinda related with #31 (see the proposed fixed)
