### ISSUE TITLE
Why is the "/dist" dir being ignored in package.json?

### ISSUE THREAD

**Issue by ramumb** [algolia/algoliasearch-helper-js#292]
Is there any valid reason why the "/dist" directory is being ignored in https://github.com/algolia/algoliasearch-helper-js/blob/master/package.json#L42-L46?  I'd like to use those file in my front-end code (by leveraging npmjs instead of bower), but I can't because of the ignore.  I've notice that the same directory is not ignored in https://github.com/algolia/algoliasearch-client-js/blob/master/package.json.  Can the ignore be removed?

**Comment by vvo** [comment]
I think we could expose them indeed, thoughts @bobylito?

**Comment by ramumb** [comment]
That would be great; we're using AMD so running into issues with CommonJS.

**Comment by bobylito** [comment]
Seems fair to me :) 👍

**Comment by Andyccs** [comment]
+1

**Comment by bobylito** [comment]
Fixed in the latest release (2.13.0)

cc @Andyccs @ramumb

**Comment by ramumb** [comment]
Sweet!  Thank you @bobylito!
