### ISSUE TITLE
Avoid deep merge in parseNumbers

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#299]
Current parseNumbers of SearchParameters (https://github.com/algolia/algoliasearch-helper-js/blob/master/src/SearchParameters/index.js) is a deep merge (lodash.merge({}, obj)).

We should use lodash.assign since the goal is to get a new reference from the first SearchParameters.\* level only.

This will remove some extra work and loops. We already got new references and copied deeper childnodes like array lists.
## TODO

_(modify this list when needed if you start working on it)_
- [ ] use lodash.assign instead of lodash.merge in parseNumbers

**Comment by Haroenv** [comment]
This is likely outdated now :)
