### ISSUE TITLE
support promises

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#3]
As the algoliasearch client support both promises and callbacks.

As the helper is a smart wrapper around our JavaScript client.

It would be great for the helper to support both promises and callbacks as the API it's wrapping.

So that we can write examples using both callbacks and promises and people never complain about one or another missing implementation ("I am using promises on the client, why can't I have promises in the helper?").

**Comment by bobylito** [comment]
We are moving towards an event based api for v2 (I feel very old saying that)
