### ISSUE TITLE
Only do a parseNumbers on external data

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#300]
We currently do a parseNumber (internal number parsing) in both:
- setQueryParameters => called on any method of the helper
- new SearchParameters(params) => called on any method of the helper

The later being the more problematic one since we then do a parseNumber(fullSearchParameters) which result in another extraneous deep full merge (see #299).

So we should only do a parseNumber in setQueryParameters.

## TODO:

*(modify this list when needed if you start working on it)*

- [ ] stop doing parseNumbers in SearchParameters constructor

**Comment by bobylito** [comment]
https://github.com/algolia/algoliasearch-helper-js/blob/develop/src/SearchParameters/index.js#L497

I updated the implementation during the lodash migration (due to dependencies using v4). And I implemented this new behaviour.
