### ISSUE TITLE
Provide an API to detect real changes from fake ones

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#305]
Real change:

``` js
.setQuery('a')
.setQuery('b') 
```

Fake change:

``` js
.setQuery('a')
.setQuery('a')
```

After every setQuery call here, a change event will be submitted while in the `fake change` example, the state is the same object (see https://github.com/algolia/algoliasearch-helper-js/blob/4357cf95d7efb0c1d017a0c897093289bf31c266/src/SearchParameters/index.js#L627)

Should we:
1. Avoid sending a change event (may be breaking change but should not)
2. Send a change event but indicate in an option object the fact that it's just the same state

Also, it could be good when in a real change event to get the previousState somewhere in the change event data. Right now there's no real way to do so.

**Comment by bobylito** [comment]
Agreed! I would definitely go for : send only real change events, and provide the current and previous state as parameters.

Not sure about the order of the parameters. Right now, we provide the current state  and then the latest results. If we were to provide the old state should it be a third parameter to avoid breaking the current implementations?

And I'm wondering about the diff? Should we provide it? Or maybe just provide an helper method on the state to be able to do a diff? like state.diff(otherState) => [changedProperties]

**Comment by vvo** [comment]
> If we were to provide the old state should it be a third parameter to avoid breaking the current implementations?

Yes, in the future we might go for "change event data" single object `{previousState, state, results}`.

> And I'm wondering about the diff? Should we provide it?

Maybe we can wait for it to be a requirement.

**Comment by bobylito** [comment]
> Maybe we can wait for it to be a requirement.

My personal feeling here is that it can be done "on demand" with a method and that it should be done as such until we see that it should be generalized (if we see perf problems due to diffing objects).

**Comment by vvo** [comment]
Ah yes indeed this was the other question, yes on demand for an object diff should be more efficient since we lived until then without having it (= not enough use case for now)
