### ISSUE TITLE
Method for remove a queryParameter

### ISSUE THREAD

**Issue by prspace** [algolia/algoliasearch-helper-js#306]
Suppose i have done this

    helper.setQueryParameter('aroundLatLng', _position._lat + ',' + _position._lng).search();

Now how can i set this to previous query parameter. like

    helper.removeQueryParameter('aroundLatLng').search();

Is there any way to do so? thanks.

**Comment by prspace** [comment]
Ok! i got it! Just setting the second parameter off.

    helper.setQueryParameter('aroundLatLng').search();

Works perfectly.

**Comment by vvo** [comment]
thanks for the feedback, indeed we might need a method here

**Comment by prspace** [comment]
yes method like removeQueryParameter() would be more readable.
