### ISSUE TITLE
Impossible to declare an attribute in both hierarchicalFacets and facets

### ISSUE THREAD

**Issue by olance** [algolia/algoliasearch-helper-js#310]
Well, it **is** possible to declare them:

``` js
{
        facets: ['level1', 'level2'],
        hierarchicalFacets: [{
          name: 'categories',
          attributes: ['level1', 'level2']
        }]
}
```

In this example, `level1` and `level2` would follow the hierarchical faceting convention:

``` json
{
  "level1": "Category",
  "level2": "Category > Subcategory"
}
```

But then `facets.xxx` are "filtered out" because of the way the helper distributes facet information into `facets`, `disjunctiveFacets` and `hierarchicalFacets` in the final results object.

The result of this, is that I'll end up with `hierarchicalFacets` containing the facet data for `level1` but not for `level2`, and `facets` containing nothing at all.

The reason for this is in the `if .. else` used in [SearchResults/index.js](https://github.com/algolia/algoliasearch-helper-js/blob/master/src/SearchResults/index.js#L319-L352), making it impossible to have a hierarchical facet considered a conjunctive facet as well.

Would there be any side effect if we didn't use `else` here?
(I cannot seem to be able to run the tests locally :/)

**Comment by vvo** [comment]
Thanks for reporting this.

What is the usecase in term of UX of having both facets and hierarchicalFacets declared? As soon as you would refine hierarchicalFacets, the facets would also be refined.

**Comment by olance** [comment]
I am building a dropdown menu (can't show publicly but can send you a gif in PM) from the categories of products in an index, with submenus when there are subcategories.

I'm building the whole menu from a single query to get facet information of each level; that works well with `searchOnce`.  
But then I want to enable/disable items in this menu depending on their presence in the results set once the user starts typing something. I wanted to do this using facet information from the request, and hence tried to add all my levels as regular facets as well as hierarchical ones, because I always need to know about all the levels at once.

I just realized that I could use another query with `searchOnce` with all search parameters but the hierarchical facets and that would work 😄 
But if I could avoid the double querying, that'd be nice. Although I think supporting the same attribute on the different types of facets might be quite hard from what I have understood of the code.

**Comment by vvo** [comment]
It seems like you already kind of dived into the code, maybe submit a PR with a new test and a fix for us to see (it's easy to add a new test with some fake data coming from the API server).

**Comment by olance** [comment]
Not that easy @vvo.
Right now the code has a certain bias towards hierarchical facets, as it's always the first thing that is checked.

If I remove that `else`, then my code would work but it's just because I'm lucky to actually want the hierarchical facet to be refined when I call `toggleRefinement`.

If I wanted the conjunctive facet to be refined with that call, that probably wouldn't work?  
Or maybe if we just refine on all types (conjunctive/disjunctive/hierarchical) the attribute has been declared on, it will just work ™️ ?

I can surely fiddle with this and come back to you when I have a clearer idea of the impact of this change :)

**Comment by bobylito** [comment]
Sorry but conjunctive and hierarchical were not made to work with each other.

I think this should be solved by a feature, either on hierarchical facets or elsewhere. Let's try to figure out what exactly is the needed feature so we can plan that correctly :)

**Comment by bobylito** [comment]
I'd be happy to reopen this issue if that can be useful. Thanks for the time spent on this issue @olance @vvo
