### ISSUE TITLE
Analytics API Support

### ISSUE THREAD

**Issue by andymac4182** [algolia/algoliasearch-helper-js#316]
Are you going to be extending this client to support the Analytics API?

**Comment by vvo** [comment]
Hi @andymac4182 thanks for reporting this,

We are currently thinking about doing so but we do not have any ETA.

For now, you better use the analytics API rest calls: https://www.algolia.com/doc/rest#analytics-api on your end.

If we ever do this, it will fit into the algoliasearch-client-js: https://github.com/algolia/algoliasearch-client-js
