### ISSUE TITLE
Distinct : true with no filters nor query, automatic behavior?

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#32]
We can't use the distinct flag set to true when the query is empty because the algolia engine returns an error. Why don't we change this parameter automatically when the query is empty or if we do not use filters?

**Comment by redox** [comment]
Yes definitely, force it to `false` when there isn't any query string or filters.

**Comment by bobylito** [comment]
Working on it now! :)

**Comment by Jerskouille** [comment]
@redox Why is the API sending back an error ?

**Comment by bobylito** [comment]
Because it is unable to do it accurately, I think. Maybe @redox can give us more explanations?

**Comment by Jerskouille** [comment]
I deleted my comment because I thought I misunderstood the issue. But after re-reading, I still can't get it : @redox why is the API responding with an error if there is no query ?

**Comment by redox** [comment]
Yes, without any filter the engine needs to browse the whole dataset to retrieve only distinct records. Since it's very inefficient we're not allowing it. It can for instance trigger the timeout before finding enough hits to display the first page.

**Comment by Jerskouille** [comment]
It is the behaviour I expected. But why is this different for queries with one letter ? We're just dividing by a small constant the number of items in the dataset to browse.
If it can't scale with 0 letter, how can it with 1 ?
