### ISSUE TITLE
Exception when requesting the breadcrumb before any refinements

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#320]
![pasted image at 2016_06_24 10_37](https://cloud.githubusercontent.com/assets/393765/16334535/cf0580be-3a01-11e6-9317-72ea105801ab.png)

via @seafoox

**Comment by bobylito** [comment]
Workaround: test if the facet is refined first. If it's not refined, do not use the breadcrumb getter.

**Comment by vvo** [comment]
Fixes we should make:

1. this should throw if the facet was not defined
2. if the facet was defined but not refined, we should send an empty array

thoughts?

**Comment by bobylito** [comment]
Looks like a good strategy!
