### ISSUE TITLE
[ documentation ] Change header color 

### ISSUE THREAD

**Issue by LukyVj** [algolia/algoliasearch-helper-js#335]
From a plain : 
![](https://puu.sh/qnhv1/278fad96d3.png)

`background: #FDBD57;`

To a subtle gradient : 
![](https://puu.sh/qnhvQ/c4ed96c30f.png)

`background-image: linear-gradient(to bottom right, #FDBD57, #ffad59);`

--- 

### Why ? 
Mostly because of this : 

| contrast yellow background, white font | contrast yellow background, black font |
| --------------------------------------- |:---------------------------------------:|
| ![](https://puu.sh/qnhMH/415531bf6b.png)|![](https://puu.sh/qni5w/14aa9f781a.png) |

It seems that the header background is too bright for a white font. Making it hard to read. 
A way to gently change this, would be to apply a subtle gradient instead. 

I think it's better this way. 

My 2 cts.

**Comment by bobylito** [comment]
Thanks!

The second screenshot doesn't show the results with your new colors. Also this would be going out of the official Algolia palette :) cc @Shipow @AntoinePlu

**Comment by LukyVj** [comment]
You're right, my point was more about "it's really hard to read and a gradient could improve this just a little bit" :)

**Comment by bobylito** [comment]
Done via #341
