### ISSUE TITLE
API: Derive a new Helper from a main helper

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#337]
## API proposal

``` js
var helper = Helper(...);
var helperOnOtherIndex = helper.derive(function modifyParameters(params) {
  return params.setIndex('otherIndex');
});
helperOnOtherIndex.on('result', renderOtherResults);
helperOnOtherIndex.addTagRefinement('discount');
helper.search();
```

Notes about this sample:
- The last call will trigger a search in the main and the sub helper
- Before the sub helper search is triggered `modifyParameters` is called.
- `modifyPameters` receives a SearchParameters and will return a new one.
- Modifications on the sub helper does not change the main helper.
## Motivation

This kind of API would let us build easily related but distinct search in the same UI.
## Other properties / ideas
- search can be triggered directly on a sub helper, without triggering either the main or the other sub helpers
- ?

**Comment by bobylito** [comment]
@Morhaus @redox @clement-leprovost @PLNech What do you think?

**Comment by redox** [comment]
If I had a refinement on the main helper, does it impact the sub helper? I assume it doesn't because those refinements might not exist there. So if get it right, this will only help us not calling `subHelper.search()` explicitly?

**Comment by clement-leprovost** [comment]
@bobylito I think we need to discuss it, preferably outside the matrix (in the "real world") (a.k.a. "meeting"). I have a similar need for the iPad Movie Search demo (searching both movies and actors). But I'm not convinced yet that we need explicit support for that kind of use case.

**Comment by bobylito** [comment]
@redox humm true :) Let's figure out if we can find out more of those case where it would be impractical to use.

@clement-leprovost Definitely, this issue is just a starting point for further discussions. As @redox showed the presented API might have some holes. Also having real life use case in mind, like yours would be great :)

**Comment by redox** [comment]
> @redox humm true :) Let's figure out if we can find out more of those case where it would be impractical to use.

In such case, maybe I would rather democratize the usage of a second helper that you would build using the previous state `var anotherHelper = new Helper(helper.state.mutate(....));` and ask them to call `.search()` twice.

**Comment by bobylito** [comment]
@redox If you are synchronising many helpers, then the task is more complex and is definitely at least a pattern.

Maybe we could reduce the possibilities to make more obvious to use, and less prone to generating weird patterns.
