### ISSUE TITLE
popState problem with instant search

### ISSUE THREAD

**Issue by BenediktGross1982** [algolia/algoliasearch-helper-js#338]
Hi,

Your demo https://github.com/algolia/instant-search-demo and the app has a problem with popstate.

When you change the price slider and hit the browser back button url changes but search is not updated.

Can you please fix this.
We need this function in our app.

**Comment by bobylito** [comment]
Are you refering to this: https://demos.algolia.com/instant-search-demo/ ?

Which browser are you using? On which platform?

**Comment by bobylito** [comment]
I was able to reproduce the issue. I have PRed a fix https://github.com/algolia/instant-search-demo/pull/22

Cheers.
