### ISSUE TITLE
API: provide a static search function

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#340]
## Problem

In a redux-like architecture (like done in the [WIP instantsearch-react](https://github.com/algolia/instantsearch.js/tree/instantsearch-react/packages/instantsearch-react)), we might want to only deal with the SearchParameters because:
- the change event is explicit via the call to the state manager
- the SearchParameters is a direct mapping from the UI

Therefore the mutable helper wrapper is not really necessary. That doesn't mean shouldn't stay, just stay but it's not necessary in every case.
## Proposition

Provide a search function that takes a SearchParameters as the input and returns a promise of the result.

``` js
var H = require('algoliasearch-helper');
var SearchParameters = H.SearchParameters;
H.search(new SearchParamters({
  index: 'myIndex',
  query: 'apple'
})).then(function result(results) {
  // results is a SearchResults as you would expect in the result event
}, function error(e){
  // Like the error event.
});
```
## Question
- how to pass the search state in the with success callback?

**Comment by Morhaus** [comment]
We don't need to pass the search state in the success handler since it is already available.

I believe the reason why we used to pass search state was because the helper's `result` event acted as a single callback for all search results, so there was no other way to reconcile a result with its search parameters?

**Comment by bobylito** [comment]
The promise can be passed around making the availability of the `SearchParameters` less obvious. It's clear that if the then method is used right away there is not much added value, otherwise it may make sense.

**Comment by Morhaus** [comment]
I think keeping a reference to the arguments is the user's responsibility. Having the promise resolve directly to results would be consistent with most promise-based APIs.

**Comment by bobylito** [comment]
This feature is not necessary for the moment. Closing.
