### ISSUE TITLE
Helper method to clear every kind of filtering

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#342]
Much `clearRefinement` or `clearTag` but that could reset all the filters set like:
- query
- page 
- facet refinements
- numeric refinements
- tags
## API

``` js
helper.reset();
```

No parameters. So far the purpose to clear any parameters (no the settings), so that would be make the signature tricky to let the user cherry pick.

**Comment by vvo** [comment]
`helper.reset();`?

**Comment by bobylito** [comment]
> helper.reset();

No strong feelings here. Isn't `clearAll` better because it would be the same way of expressing it than in instantsearch?

**Comment by vvo** [comment]
I think in instantsearch-react we distinguised the clearAll (which clear all filters) from reset (which clear all filters and resets the query), this is the reason I jumped here to propose reset.

But clearAll also works for me.

**Comment by bobylito** [comment]
Cool makes sense @vvo :)

**Comment by bobylito** [comment]
I've dug deeper into this and especially I looked at the code in instantsearch.js. Truth is that just combining the two clears is not that big of code removal and creates yet another way which could be confusing. If we want to remove more code from instantsearch we might consider [reimplementing this](https://github.com/algolia/instantsearch.js/blob/60c6fa7add35bcbed09b9cbfcb267eb95d9589dd/src/lib/utils.js#L205-L227). But then it's just moving code around.

What about we evolve the signature of the clears with a unified clear method? Make another version that make the old deprecated 'a la ember', so that we can drop it when we change version? 

WDYT @vvo @rayrutjes

**Comment by rayrutjes** [comment]
To me the following makes the most sense:
```js
helper.reset(); // Which removes the query string
helper.clearFilters(); // Which clears all refinements
```

Combining both could result in:

```js
helper.resetAndClearFilters();
```

But the previous implementations should also exist. Not sure the `resetAndClearFilters` is mandatory.

I hope this helps and isn't too much off topic here.

**Comment by rayrutjes** [comment]
>  If we want to remove more code from instantsearch we might consider reimplementing this.

I agree with this. We should make things cleaner in that part of the code and "move things around".

It is not obvious what this does: `clearRefinementsFromState(inputState, attributeNames)`

**Comment by vvo** [comment]
> What about we evolve the signature of the clears with a unified clear method? Make another version that make the old deprecated 'a la ember', so that we can drop it when we change version?

**Comment by LoganLehman** [comment]
Just to verify, there is currently no method in Algolia Search Helper to clear the currently set query parameters?

**Comment by bobylito** [comment]
@LoganLehman What do you mean? All the parameters, like really all of them?

**Comment by Haroenv** [comment]
`helper.clearRefinements()` does this afaict.
