### ISSUE TITLE
Handle the whole scope of numeric filtering

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#35]
The algolia API has the ability to set multiple values for a single parameter with or and and. https://www.algolia.com/doc#numericFilters

The helper api should be simple and not json based :P :palm_tree:

**Comment by bobylito** [comment]
Example of friendly api : 

```javascript
helper.addNumericRefinement( "attr1", "=", [1,4,5,42] );
```

**Comment by redox** [comment]
Looks good but it will not handle all the cases. 

Since the engine is able to handle ANDs or ORs: 
```
<or> ::= condition (OR condition)*
<filter> ::= <or> (AND <or>)*
```

Maybe we should define it like:
```
// attr1=42 AND (attr2=12 OR attr2=51)
helper.addNumericRefinement({ attribute: "attr1", operator: "=", value: 42 });
helper.addNumericRefinement([
  { attribute: "attr2", operator: "=", value: 12 },
  { attribute: "attr2", operator: "=", value: 51 }
]);
```

**Comment by bobylito** [comment]
Thanks for the feedback. Let's iterate on that so we can make the most simple yet powerful api for handling those kind parameters.

**Comment by reinaris** [comment]
:+1:

**Comment by vvo** [comment]
```js
helper.addNumericRefinement({ attribute: "attr1", operator: "=", value: 42 });
helper.addNumericRefinement([
  { attribute: "attr2", operator: "=", value: 12 },
  { attribute: "attr2", operator: "=", value: 51 }
]);
```

The fact that the second call would mean `(attr2=12 OR attr2=51)` is really not obvious. In fact in most JS APIS this would just mean that the function accepts a single item or an array of items but not that they have different semantics.

While I can criticize the proposed API I do not have another solution for it right now.

**Comment by pixelastic** [comment]
I can see the limitation of the current approach here too.

Maybe we could expose a high-level, SQL-like, string API to let user easily craft the query they'd like (eg. `attr1=42 AND (attr2=12 OR attr2=51)`) ? We'll transform that into our JSON-based representation of a query, while also letting more advanced users add to it directly.

On how to handle more complex cases while retaining a (more or less) readable structure, we can have a look at how things were done in other frameworks. Here's a [CakePHP example](http://book.cakephp.org/2.0/en/models/retrieving-your-data.html#complex-find-conditions).

This need more thoughts.

**Comment by vvo** [comment]
In the end, mapping to the REST api would be the most simple and easy to understand thing to do: helper.addNumericRefinement( "attr1", "=", [1,4,5,42] );

But why would we then need to parse it on our side? I do not understand.

**Comment by pixelastic** [comment]
@vvo : You're right, I wasn't aware of the REST API syntax. No need to parse anything back.

In the and, I guess passing an array of items to represent a `OR` call makes sense once you understand the underlying REST API (where you group items in parenthesis to represent a `OR`). I think it is important that we have a strong consistency between our various APIs.

**Comment by bobylito** [comment]
@vvo I guess this kind of api could make sense. With respect to the idea
that we should prevent the user from having to store data on his side, how
easy would it be to use this kind of api? Do we have a page that uses both
and and or filters? Just to be sure, what is the semantic of the array in
what you propose?

**Comment by vvo** [comment]
The API I outlined in https://github.com/algolia/algoliasearch-helper-js/issues/35#issuecomment-102449730 was just the one @redox proposed. But:
- it's hard to understand that the semantics are different given you set one or more element in your call

But I do not see any obvious solution to this problem. The only solution would be to provide a very simple:

```js
helper.addNumericRefinement('code=1,(price:0 to 10,price:1000 to 2000)');
```

Which is directly mapping the REST API. I do not understand why we would need to split this string in an array of objects.

**Comment by Jerskouille** [comment]
@vvo The current solution is actually needed for such facet types as the slider (at least the one I developed for Shopify). Sure, we can parse this string, but it is really convenient right now.

**Comment by reinaris** [comment]
Any idea when we could use something like `helper.addNumericRefinement( "attr1", "=", [1,4,5,42] );` (as written above), would be really useful!

**Comment by bobylito** [comment]
@reinaris : as of now, this is not  possible. We'll provide an advanced API that will let you override the parameters with the same raw string the engine understands.

**Comment by reinaris** [comment]
@bobylito cool! Looking forward to it!

**Comment by sweetroll** [comment]
Is there plans to enhance `helper.addNumericRefinement` to allow multiple operators within an ORed query?

@bobylito has [helpfully told me a way around this](http://stackoverflow.com/questions/37862351/addnumericrefinement-or-with-different-operators) however this disallows the use of any other widget the uses the helper function.

**Comment by bobylito** [comment]
Hi @sweetroll, we have some good leads for this with all the filters and a nice API. But this will need a complete rework and will probably be in the next version.

**Comment by sweetroll** [comment]
@bobylito ok no worries. Thanks for the update.
