### ISSUE TITLE
Geo Search error with setQueryParameter - aroundLatLng

### ISSUE THREAD

**Issue by nick-douglas82** [algolia/algoliasearch-helper-js#350]
If I use setQueryParameter with manually entered string of longitudes and latitudes aroundLatLng works perfectly however, using dynamic longitudes and latitudes from another objects _geoloc attribute (even when converted to a similarly formatted string as teh manual entries) causes the locations around the point to be incorrect and the distance to show an incorrect number

**Comment by stevieg83** [comment]
@nick-douglas82 any reason you closed this issue?

**Comment by vvo** [comment]
@nick-douglas82 Maybe open a new detailed issue if you have something more to discuss. Thanks!

**Comment by vvo** [comment]
~~@nick-douglas82 Maybe open a new detailed issue if you have something more to discuss. Thanks!~~ was done, see #516
