### ISSUE TITLE
[website] NPM package `algoliasearch-client` does not exist

### ISSUE THREAD

**Issue by mikemclin** [algolia/algoliasearch-helper-js#353]
On the following page - https://community.algolia.com/algoliasearch-helper-js/gettingstarted.html#npm, the NPM command references an incorrect package name resulting in an error.

`npm install --save algoliasearch-client algoliasearch-helper`

There is no `algoliasearch-client` package, it is `algoliasearch`.  Also, it appears the client can be omitted, since the helper automatically brings in an saves the client to the `package.json` file with this command:

`npm install --save algoliasearch-helper`

**Comment by bobylito** [comment]
Thanks @mikemclin for the issue.

Indeed the package name is wrong. Will update the doc.

For the second part, this is only true with npm@2. With npm@3 peer dependencies are not downloaded automatically.

**Comment by bobylito** [comment]
Thanks again @mikemclin. Fixed with 33863730cdd839e68bf0f2b01f7ea1e1a7797055
