### ISSUE TITLE
is there a way to start/stop the search ?

### ISSUE THREAD

**Issue by chrisvidal** [algolia/algoliasearch-helper-js#358]
is there a way to start/stop the search ?

**Comment by bobylito** [comment]
Hi @chrisvidal. Can you explain what is it that you want to achieve?

**Comment by chrisvidal** [comment]
thanks for your answer
i need to build a UI where the user can : 
- toggle between 3 different search indexes and  each of this index have different facet attributes 
- bookmark the specific url in order to retrieve later his results

I tried many approaches, and so far the one i m working on this concept:
having only 1 instance of instantsearch and playing with different state in my UI.
when a change of state occur in the UI (switching from an index to another one), i change the index name of the instantsearch instance (with the method setIndex), and this is working fine.

Now i dont know how to remove the previous facet/widgets from the previous state before adding the new facet/widgets of the new state.

**Comment by bobylito** [comment]
thanks @chrisvidal. This is an instantsearch.js issue :) I just [answered you](https://github.com/algolia/instantsearch.js/issues/1206) :)
