### ISSUE TITLE
is holdSearch parameter counter intuitive?

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#36]

**Comment by kokliKo** [comment]
Proposition: have performSearch parameter instead.
And have performSearch = true by default.

**Comment by redox** [comment]
I'm not super fan of the naming or adding another parameter. What about triggering the search only if the searchCallback is specified, and emit an `search/change` event in any case.

**Comment by bobylito** [comment]
The suggestion concerns the parameter added to each mutating method of the helper. For example : 

```javascript
helper.search( "my input", true );
```

True here is the holdSearch parameter set to true. Holdsearch is the name of the variable and is described in the jsDoc of the 2.0 branch.

The suggestion is about reversing the semantic of this parameter to something where we would set it to false if we do not want the search to happen right away.

**Comment by vvo** [comment]
I want to point out that in any case, there is no way to easily understand what true/false means when using an API like:

```js
helper.search( "my input", true );
```

Can we have use a named parameter or another function like helper.holdSearch()?

Very nice article about the "boolean trap" http://ariya.ofilabs.com/2011/08/hall-of-api-shame-boolean-trap.html

**Comment by bobylito** [comment]
Good point on the boolean trap!

The use of named parameters would imply passing an object, which would be ok if all the parameters of the function would live in this object. Since the mutating functions are based on one parameter, and the idea of using the boolean to hold the search was to handle an edge case,  you will have to create an object for a single parameter most of the time...

```javascript
helper.setDisjunctiveRefine({ facetName:"facet1", facetValue:"value", doTheSearchNow : false} );
helper.search( { query : "some input" } );
```

Having a method called helper.holdSearch() implies that we have an internal state, that changes the behaviour of all the other methods. I think that this will lead to multiple misunderstandings and bugs as someone may forget the use of the conterpart to release/activate/launch the search.

```javascript
helper.holdSearch()
helper.setDisjunctiveRefine( "facet1", "value");
helper.search( "some input" );
helper.searchNow();
```

I guess that having the helper to do the search right away is not such a great idea. What about we remove the auto search, make a separate search function that takes no parameter, change the name of the query setter and make all the mutating functions chainable (to provide a more user friendly API). This would like : 

```javascript
helper.setDisjunctiveRefine( "facet1", "value" )
      .setQuery( "some input" )
      .search();
```

**Comment by redox** [comment]
Removing the auto-search + making all mutating functions chainable LGTM :+1:

**Comment by bobylito** [comment]
Ok creating issues to track that!
