### ISSUE TITLE
disjunctiveFacets for nested object in helper init

### ISSUE THREAD

**Issue by harshmaur** [algolia/algoliasearch-helper-js#365]
All of my documents have a "properties" key which is an object of all the properties that I want to show disjunctive facets for. 

I have it nested because my index contains a large number of properties and are very specific to a particular document, the properties change on the basis of what the document is. 

I want to initialise all the properties in my helper initialisation and its not possible to define each and every property manually, is there a wildcard that can be used to do that?

**Comment by bobylito** [comment]
Hi @harshmaur thanks for posting this issue. Unfortunately, the helper does not retrieve the list of attributes for faceting therefore we cannot implement a wildcard.

You can create a script that can output you this list using the `getSettings` [method from the JS client](https://www.algolia.com/doc/api-client/javascript/settings#get-settings).
