### ISSUE TITLE
The facet order should be consistent with the configuration

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#37]
There is no guarantee on the order of the facets for the moment. The user has to manually sort its facets...

**Comment by redox** [comment]
Would be cool to be able to sort the values as well. I want my facet1 values sorted by count (default) and my facet2 values sorted by lexicographical order for instance.

```js
{
  facets: [ "facet1", "facet2" ] // default sort order
}
```

or

```js
{
  facets: [
    {attribute: "facet1", sortFunction: Helper.sortByCountDesc },
    {attribute: "facet2", sortFunction: Helper.sortByValueAsc },
    {attribute: "facet3", sortFunction: function custom(a, b) { /* */ } }
   ]
}
```

**Comment by bobylito** [comment]
Thanks. Will be the subject of another issue.

**Comment by bobylito** [comment]
So this issue is more than anticipated. The order of the attributes is not defined in the specs. So we'll have to rely on some other tools to provide the ability to sort the facets...

Should it be a function like a foreach that can take the array definition of the facets as an input, or should it be a method of the helper that takes a function?

Or maybe we should return the facets not in an object but as an array that contains an object per facet (and the facet identifier should be stored in it).

I guess the later solution would make the more sense but it would imply that we move forward to a model for the results too sooner rather than later.
