### ISSUE TITLE
Dynamic sorting / customRanking at query time?

### ISSUE THREAD

**Issue by timkelty** [algolia/algoliasearch-helper-js#370]
Here's my use-case:

- I have a `products` index with a `products.category` is a facet.
- Different pages have a search with a pre-filtered `products.category` facet.

I want to "Feature" products to always show first, but whether or not they are featured changes based on the page your are on.

The only way I can see doing this currently is with a unique index for each of my "categories", whic doesn't seem manageable.

Any other ideas?

**Comment by bobylito** [comment]
Hi @timkelty. Thanks for opening an issue :) I think this is a bit beyond the scope of the Helper.

I think you can achieve this either by having a featured attribute for each category on each product and them to your custom ranking. You can also split your index into several indices. 

Please send an email to `support at algolia dot com` mentioning me if this doesn't solve your issue :)

**Comment by timkelty** [comment]
Thanks, I will.
Wasn't sure which repo to log in, this was my best guess :)

**Comment by timkelty** [comment]
@bobylito Back on this issue again.

Currently in contact with support about it, but I made a SE post for it here: http://stackoverflow.com/questions/41166479/complex-featured-product-model-using-query-time-ranking-optional-filters

It looks like the private beta `optionalFacetFilters` param may be relevant.
