### ISSUE TITLE
API: provide a load more mechanism

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#376]
Implementing infinite scroll can be tedious if we rely on the actual page (previousPage, nextPage, setPage) API. The difficulty is in storing all the results, making them available when the results are back and managing the page number.
### usage

``` js
helper.on('result', searchCallback);
helper.loadMore();
// > set the page to the page, triggers a search


function searchCallback(results) {
  // results.hits contains the hits of all the previous request in the order
}
```
### Interaction with the other methods

`setPage` should reset the cached answers. As well as any method that is not `loadMore`
## Questions
- What happens with the mechanism that drops outdated results? Should we be strict or not really care?

**Comment by vvo** [comment]
> What happens with the mechanism that drops outdated results? Should we be strict or not really care?

Do you speak about a specific mechanism we implemented somewhere? Or did you wanted to say "Should we drop outdated results"?

**Comment by bobylito** [comment]
I don't remember :/ :) I will figure this out ;)

**Comment by vvo** [comment]
> What do you think about the overall idea?

It's a nice way to easily provide examples like "showing hits from different index" without having the user to write some boilerplate code and plumbind => goal of the helper

**Comment by bobylito** [comment]
We've settled to implement that in instantsearch.js and react-instantsearch and it works well so closing this.
