### ISSUE TITLE
Add DocSearch

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-helper-js#378]
It would be amazing to be able to search in the documentation with Algolia.
❤️

**Comment by vvo** [comment]
Yes adding `docsearch` could help

**Comment by seafoox** [comment]
That would be great. Any chance it happens soon @bobylito @ElPicador ?

**Comment by ElPicador** [comment]
Whenever you need a DocSearch just use the form and we'll do it.

Or you also can do it 😄

**Comment by bobylito** [comment]
You are sooo right @seafoox @rayrutjes @vvo :) Putting this in my todo :)

**Comment by Haroenv** [comment]
Since this website no longer is used frequently, we don't need to add docsearch here
