### ISSUE TITLE
Sort facets values

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#38]
Copy of @redox suggestion : 

Would be cool to be able to sort the values as well. I want my facet1 values sorted by count (default) and my facet2 values sorted by lexicographical order for instance.

```js
{
  facets: [ "facet1", "facet2" ] // default sort order
}
```

or

```js
{
  facets: [
    {attribute: "facet1", sortFunction: Helper.sortByCountDesc },
    {attribute: "facet2", sortFunction: Helper.sortByValueAsc },
    {attribute: "facet3", sortFunction: function custom(a, b) { /* */ } }
   ]
}
```

**Comment by bobylito** [comment]
Maybe we could make the static sort functions on the helper instead of having the feature built-in? I'm thinking of this because I think it would make the api less clear and also would need some messy code inside the helper to handle many types for the facets attributes.

**Comment by Jerskouille** [comment]
:+1: for static functions.
I agree with @bobylito , but a way to retrieve facets results by name would be cool.
We will have many cases where having functions directly in a facet configuration would be useful.
For example, a `displayFunction` could also be useful, and we probably don't want this inside the helper, do we ? Idem for the title of a facet.

Having a way to retrieve a facet result from the result data by its name would be cool to do so in a not-too-much-pain-in-the-ass way.
So one could do like it was done before, i.e. iterate on his configuration array to apply different action by facet type.

```js
    var FACETS = [
        { name: "price", sortFunction: Helper.sortByCountDesc, displayFunction: function (e) { return '$' + e; }, title: 'Price' },
        { name: "vendor", Helper.sortByValueAsc, title: 'Vendor' }
    ];
```
Now the handling of content : 
```js
    helper.on('result', function (content) {
        FACETS.forEach(function (facetConfig) {
            var facet = content.getFacet(facetConfig.name);
            var values = [];
            for (var value in facet.data) {
                if (facet.data.hasOwnProperty(value)) {
                    values.push({
                        label: ((typeof(facetConfig.displayFunction) === 'function') ? facetConfig.displayFunction(value) : value),
                        value: value,
                        count: facet.data[value],
                        refined: helper.isRefined(facetConfig.name, value)
                    });
                }
            }
            if (typeof(facet.sortFunction) === 'function') {
                values.sort(facet.sortFunction);
            }
            facetTemplate.render({ facet: facet.name, values: values, title: facetConfig.title });
        });
     });
```

The notable thing here is the `getFacet`.
If you want the basic behaviour of the helper, then you can just iterate on the two arrays `content.facets` and `content.disjunctiveFacets`
But if you want to customize in a configuration way, having this method allows to handle the order in which you want to display the facets and give additional infos directly inside the configuration, while the helper just needs to give you a way to access a specific facet.

**Comment by vvo** [comment]
Moving to #178 

@Jerskouille As for getting a facet by name there is now results.getFacetByName: http://algolia.github.io/algoliasearch-helper-js/docs/SearchResults.html#getFacetByName
