### ISSUE TITLE
Sorting of facets does not handle accented characters

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-helper-js#397]
Initially posted on instantsearch.js: https://github.com/algolia/instantsearch.js/issues/1377

![image](https://cloud.githubusercontent.com/assets/283419/19118169/e038fe68-8b1b-11e6-94c7-26ce7875faa8.png)

As seen in this screenshot, names starting with an accented characters are sorted at the end. In JavaScript, the way to fix that would be to use `localeCompare` instead of the classical sort.

But we are using `_.sortBy`, and it does not provide a way to override the default sort method used (see https://github.com/lodash/lodash/issues/1222). The suggest solution is to `deburr` (replace accented characters with their non-accented version) before doing the sort:

``` javascript
var facets = _.sortBy(facetValues, (facet) => { return _.deburr(facet.name) });
```

Not perfect, but would fix the issue above.

I guess we have no way to automatically select a locale for the user, and it will have to be explicitly set for it to work properly. In the above example, instantsearch.js is already aware of locale and could pass it to the Helper instance.

**Comment by bobylito** [comment]
Hey @pixelastic have you had time to check the issue? Feel free to drop your findings here :)

**Comment by pixelastic** [comment]
Hey, no I didn't dig deeper. The thing about this issue is that it impacts InstantSearch, but the solution lies in the Helper.

The quickwin solution of using `deburr` could be enough for now, but we might want to specify a locale when instanciating the helper and rework the sorting logic using that locale later on.

**Comment by Haroenv** [comment]
InstantSearch now exposes a sortBy & transformItems option, which allows users to resort using localeCompare themselves
