### ISSUE TITLE
When an error is returned from Algolia, a JS error occurs

### ISSUE THREAD

**Issue by kayneb** [algolia/algoliasearch-helper-js#399]
When I have an invalid query, for example, if I specify an invalid index, I get a JS error:

```
index.js:210 Uncaught TypeError: Cannot read property 'results' of undefined
```

That's SearchResults/index.js.

The problem is that a `SearchResults` is being constructed with the Algolia response, which is undefined. That response is blindly accessed in the constructor of `SearchResults`.

**Comment by bobylito** [comment]
Thanks for the issue! I looked at the PR, it is great :D
