### ISSUE TITLE
API DOC get client ip

### ISSUE THREAD

**Issue by chriscalip** [algolia/algoliasearch-helper-js#414]
algoliasearch helper has client ip feature.
How do we get client ip for use?

**Comment by vvo** [comment]
Hi @chriscalip can you give a bit more context on your issue, your use case? Right now I cannot understand what you are asking for.

**Comment by vvo** [comment]
There's no method in Algolia to GET your user IP. We only READ the userip on our servers and use it for geocoding ranking.

What is your usecase for getting the user ip in relation to algolia? Thanks

**Comment by chriscalip** [comment]
@vvo right, hits information contains places/locations.. with address attributes (street,city,state,zip)
So on instantsearch.widgets.hits template.item I want to add in the directions from user ip to hit address attributes via google.

**Comment by vvo** [comment]
> I want to add in the directions from user ip to hit address attributes via google

Hi again, can you provide more details and specs to what you want to accomplish in term of UI? That would help me, thanks.

**Comment by chriscalip** [comment]
![algolia-hit-item-template](https://cloud.githubusercontent.com/assets/479454/20012437/3253833a-a27d-11e6-9296-05590f4898fe.png)

It's fine if there is no algolia method for getting user client-ip. I'll be able to get it in another way.. was just curious.

**Comment by chriscalip** [comment]
<code>
// var origin = client_ip goes here
var destination = encodeURIComponent(String() +
  content.hits[i].street + ' ' +
  content.hits[i].city + ' ' +
  content.hits[i].state  + ' ' +
  content.hits[i].zip + ' '
);
'<p class="map-popup--directions"><a href="' + 'https://www.google.com/maps/dir/' + origin +' /' + destination + '/' + '" target="_blank">Get Directions</a></p>';
</code>

**Comment by vvo** [comment]
There are some web apis to get user IP like: https://www.ipify.org/

Is that all you need? If so, please close this issue, thanks!

**Comment by chriscalip** [comment]
@thanks.
