### ISSUE TITLE
Removing of refinements

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-helper-js#42]
It be nice to be able to remove all refinements for a particular facet (conjunctive or disjunctive) without having to modify the helper refinements object from outside the helper.

**Comment by bobylito** [comment]
Thanks @maxiloc! This is by far the most requested feature. And I just experience what makes it so necessary - if you modify the internals without the control of the helper functions, it might not get what it expected, and thus miserably fail with errors.

**Comment by bobylito** [comment]
And this is a duplicate of #25. So I'll close this :)
