### ISSUE TITLE
Multiple queries

### ISSUE THREAD

**Issue by hovhannesDavtyan** [algolia/algoliasearch-helper-js#428]
are there multiple queries functionality??, sorry cant find it. thanks

**Comment by bobylito** [comment]
Hi @hovhannesDavtyan 

Thanks for opening an issue :) We are indeed working on it. There is an on going prototype that I will soon release but it's not yet documented. You can see the [PR here](https://github.com/algolia/algoliasearch-helper-js/pull/374). Let me know what are your thoughts on it.

**Comment by jeerbl** [comment]
Hello,

Will this PR soon be merged? Thanks for this feature btw.

Jerome

**Comment by bobylito** [comment]
Hi @jeerbl . The PR has been merged and the feature release in 2.17.0. You can find a presentation of [the mechanics](https://community.algolia.com/algoliasearch-helper-js/concepts.html#derivations-of-the-helper-multi-queries), and the API reference to the [method](https://community.algolia.com/algoliasearch-helper-js/reference.html#AlgoliaSearchHelper#derive) in the docs.

Let us know if you have other questions.
