### ISSUE TITLE
Remove tagFilters in the ReadMe

### ISSUE THREAD

**Issue by kokliKo** [algolia/algoliasearch-helper-js#433]
We're removing the notion of `tagFilters` in all the docs (deprecated).
Can we remove this paragraph from the ReadMe?

PS: the feature still needs to work, for legacy reasons.

**Comment by bobylito** [comment]
Great! Thanks for letting us know @kokliKo . If you feel like it, you can PR the doc. Otherwise, what's the ETA for the actual removal?

**Comment by kokliKo** [comment]
Ok, making the PR. The earlier the better :)

**Comment by bobylito** [comment]
Since we don't have a consensus and it's been quite some time since we last discussed about it, I'm gonna assume it's not going to move for the moment. Feel free to open it again :)
