### ISSUE TITLE
Remove extraQueries in v2

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#44]
There are questions around the use of the extraQueries. So we might as well get rid of them for initial v2 and reintroduce later in a better form.

**Comment by bobylito** [comment]
@redox @vvo @kokliKo My idea was that we should get rid of extraQueries for now, as it might be too limited, in order to reintroduce it later with a better design in mind. Removing it now, means that we don't have to ensure the compatibility for the v2, and when we reintroduce it we'll be more happy to ensure the maintenance. What do you think?

**Comment by redox** [comment]
Go for it.

**Comment by vvo** [comment]
yes, as it's a V2, no need to rush to include potentially low usage methods
