### ISSUE TITLE
Rename toggleRefinement to toggleFacetRefinement

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#447]
it only works on facets.

**Comment by Haroenv** [comment]
How would you deal with `toggleFacetRefinement` already existing? 

[SearchParameters/index.js#L1173](https://github.com/algolia/algoliasearch-helper-js/blob/7d9917135d4192bfbba1827fd9fbcfef61b8dd69/src/SearchParameters/index.js#L1173)

**Comment by bobylito** [comment]
/o\ Indeed it does not work well :(

**Comment by Haroenv** [comment]
Another option might be leaving out the original toggleFacetRefinement completely, and doing its functionality in the conjunctive if. I think that would make things easier.

**Comment by bobylito** [comment]
Check the PR, I added some ideas :)
