### ISSUE TITLE
ConcurrentModificationException in Client.java

### ISSUE THREAD

**Issue by PrabithaK** [algolia/algoliasearch-helper-js#454]
Please help

**Comment by bobylito** [comment]
Hi @PrabithaK, thanks for opening this issue. I think you are not on the correct repository. I think you're looking for [the java client](https://github.com/algolia/algoliasearch-client-java). In the mean time I opened an issue there. Closing the issue here :)

**Comment by PrabithaK** [comment]
Thanks for the help..
