### ISSUE TITLE
`SearchResults` is missing the `params` response field

### ISSUE THREAD

**Issue by clement-leprovost** [algolia/algoliasearch-helper-js#466]
Cf. the [Search Response Format](https://www.algolia.com/doc/api-client/javascript/search/#search-response-format).

**Comment by bobylito** [comment]
Indeed. Just out of curiosity, what would be the use of it since we are providing the "same level of abstraction" SearchParameters ?

**Comment by clement-leprovost** [comment]
In a real use case, I don't know. When debugging, it can be useful to investigate what the helper actually sent to the API (it was my case).

**Comment by bobylito** [comment]
After giving some thoughts to this bug, I don't think it's possible given our given API. `search` is an user oriented event and in this case the results are created from the aggregation of multiple results. Therefore it's not possible to give a single `params` for mutliple algolia requests. However this got me thinking about making more tools for debugging and I created a dedicated [new issue](https://github.com/algolia/algoliasearch-helper-js/issues/470) for this purpose.
