### ISSUE TITLE
Persistent facets

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#47]
In the case of menus, we want to be able to keep the reference to certain facets. But that's a pretty boring task that can be handled in the helper.

For this, it would be great that we can define some facets as persistent when we initialize the helper. It would need to trigger a blank search once, and cache the results. Those cached results will be then served through the search results object with some function or information to evaluate if the facet is available with the current search.

**Comment by bobylito** [comment]
@Shipow

**Comment by Shipow** [comment]
:+1:

**Comment by bobylito** [comment]
Could be useful for numeric data as well... In sliders, we want to keep the whole range of price.
