### ISSUE TITLE
Debugging API

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#470]
The idea of this issue is to provide enough to be able to inspect the internals be it for internal purpose when testing the behaviour of features or even creating tools for users to get insights about what's going on with the JS Helper. I know this might sound as niche but react dev tools and other redux tools have proved that this can be quite useful.

Proposed new API's

Create two new events for inspection purpose:

 - `post-search` to inspect the queries sent to Algolia in their purest form (and yet structured in the better fashion that in the Chrome dev tools)
 -  `pre-results` to get all the responses returned from Algolia with some insights about how they're gonna be dispatched (between main and derived helpers)

Other ideas?

**Comment by Haroenv** [comment]
This did not have any response for a long time, which means (I think) that there's not much need for this feature, let's close this issue for now.
