### ISSUE TITLE
Howto use the param paginationLimitedTo

### ISSUE THREAD

**Issue by yann-kelcible** [algolia/algoliasearch-helper-js#472]
Hi,

I need to increase the parameter **paginationlimitedto** but I don't see if it's possible throw _algoliasearch-helper-js_ ?

https://www.algolia.com/doc/api-client/ruby/parameters/#paginationlimitedto

thanks for your report

Yann

**Comment by bobylito** [comment]
Hi @yann-kelcible thanks for posting your issue. Yes it should be possible using [setQueryParameter](https://community.algolia.com/algoliasearch-helper-js/reference.html#AlgoliaSearchHelper#setQueryParameter):

```js
helper.setQueryParameter('paginationLimitedTo', 4);

// to see the results with the parameters applied, do not forget to search
// helper.search();
```

Let me know if this works for you.

**Comment by yann-kelcible** [comment]
Hi, 

I've got this error : 

```
message : "Unknown parameter: paginationLimitedTo"
name : "AlgoliaSearchError"
```

algoliasearch version : 3.18.1
algoliasearch-helper : 2.14.0

**Comment by yann-kelcible** [comment]
I update to 
algoliasearch : 3.21.1
algoliasearch-helper : 2.18.0

Same Error :-(

**Comment by bobylito** [comment]
Oh this is an API error, let me check the status of this parameter.

**Comment by bobylito** [comment]
@yann-kelcible actually this parameter is a setting not a query parameter, that's why the API returns an error when you try to use it.

**Comment by mahdaen** [comment]
@bobylito so, where I can put that setting? I can't find the `.setSettings()` method. Thanks!

**Comment by bobylito** [comment]
@mahdaen It can be set using a client with backend features. For example, you can use the JS Client (not in the front end), have a look at how to configure your index [here](https://github.com/algolia/algoliasearch-client-javascript#configure).
