### ISSUE TITLE
Bug: search.helper.setQueryParameter('removeStopWords', ignoreWords);

### ISSUE THREAD

**Issue by chriscalip** [algolia/algoliasearch-helper-js#475]
The intent is to remove a specific set of words from the query sent to algolia.
For example every time a user searches for something remove the words {'near', 'nearby', 'by', 'at', 'in'}

Trying to implement intent via api feature setQueryParameter and its parameters {'optionalWords', 'removeWordsIfNoResults', 'queryType', 'removeStopWords'}

See example:
https://jsfiddle.net/chriscalip/z09gdopy/1/
Search for : Treatment near
Expected behavior: keyword near is removed.

**Comment by bobylito** [comment]
Hi @chriscalip thanks for posting this issue. It seems that the [parameter](https://www.algolia.com/doc/rest-api/search/#removestopwords) `removeStopWords` accepts a boolean or a list of language ISO codes. You can't pass words.

<img width="753" alt="screenshot 2017-02-15 11 31 49" src="https://cloud.githubusercontent.com/assets/393765/22970460/89f68394-f372-11e6-9638-6f592c7503f8.png">

If you want to remove words from the query you should do it manually when the query parameter is set. This means creating a custom widget for your searchbox.

Let me know if you need more infos.
