### ISSUE TITLE
facetingAfterDistinct

### ISSUE THREAD

**Issue by redsquare** [algolia/algoliasearch-helper-js#478]
Hi, are you planning to add in this prop? Is there anyway I can add it to my react app (using your react widgets) without hacking at this helper lib?

**Comment by bobylito** [comment]
Hi @redsquare thanks for opening this issue. The JS Helper does support this option. Have a look at [this sample](http://codepen.io/team/algolia/pen/mWJLPZ). If you have any issue using it in react-instantsearch, I suggest that you open an issue in the [instantsearch issue tracker](https://github.com/algolia/instantsearch.js/issues).

**Comment by redsquare** [comment]
Thanks @bobylito  ++
