### ISSUE TITLE
The helper should provide a way to know how many queries it will execute

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#48]
One problem with the helper is that it's a black box that does queries without letting the user know how many operations it'll actually do on Algolia.

**Comment by redox** [comment]
Why is that needed?

**Comment by bobylito** [comment]
Because as we add more complex features that do operations we'll add more operations. I think it'll help users understand what's happening behind the scene if we explain it.

**Comment by redox** [comment]
Hmmm, ok. I would say the only focus should be the implemented experience even if it costs twice the operations -> I don't remember any customer complaining about the number of operations it costs as soon as we can explain and that the implementation is optimized.
