### ISSUE TITLE
Falsy comparison in removeNumericRefinement

### ISSUE THREAD

**Issue by Jerskouille** [algolia/algoliasearch-helper-js#49]
In `SearchParameters/index.js:removeNumericRefinement`, the parameter `value` is never used, and the `if ( value )` might evaluate to false if the numeric filter value is 0.

See [`_.isUndefined`](http://devdocs.io/lodash/index#isUndefined)

**Comment by bobylito** [comment]
thanks!

**Comment by bhagwat** [comment]
I can't see a way to add numeric refinement. Did I miss something or is there any workaround?

**Comment by Jerskouille** [comment]
@bhagwat It is not yet implemented in master, but in v2 branch.

See https://github.com/algolia/algoliasearch-helper-js/blob/v2/src/algoliasearch.helper.js#L93

**Comment by bhagwat** [comment]
Thanks @Jerskouille 
I hope this v2 branch is stable and I can use it in my project. Right?

**Comment by Jerskouille** [comment]
@bhagwat You shouldn't rely on it yet, we're still in beta. Even if we try not to introduce breaking changes, it might be necessary, so you should use `v1` for now except if you really need this functionnality. To use `numericFilters` with the v1, you should declare them directly in your search, like this :
```js
helper.search("query", callback, { numericFilters: "price>=2" });
```

We expect to release it in the upcoming weeks, stay tuned !

**Comment by bhagwat** [comment]
Thanks @Jerskouille
