### ISSUE TITLE
Filter php searcg

### ISSUE THREAD

**Issue by sergiownd** [algolia/algoliasearch-helper-js#490]
Hi!
I have in my algolia engine the next "entity"

> objectID: "eyJpZCI6OX0="
> ...
> status: id: 1
> 

And I like to make a search just with the ones that have status = 1.
I've tried this:

```
 $searchResult = $this->get('algolia.indexer')->rawSearch(Professional, $data, [
           'hitsPerPage' => 10,
           'page' => 1,
           'facetFilters' => 'status:1',
           ]);
```

Seems that im nos using facetFilters correctly,
any help?
Thanks

**Comment by bobylito** [comment]
Sorry @sergiownd for taking so long to answer your issue. I don't think this is the right for this kind of issue. Have you checked the PHP API client [documentation](https://www.algolia.com/doc/api-client/php)? You could also try to ask your question directly in the [community forum](https://discourse.algolia.com/)?
