### ISSUE TITLE
Use with Webpack 2

### ISSUE THREAD

**Issue by scneptune** [algolia/algoliasearch-helper-js#491]
I've recently upgraded to using webpack 2 in our builds and for some reason builds look for `browser` flagged versions of Lodash libraries. I understand that there is implied dependency on lodash through the npm installation, and that the library has been optimized for es6 module loading and tree shaking with `rollup`, but I'm curious if I'm missing steps in using the library in webpack 2? 

For those struggling with webpack 2 and this issue,
I was able to get around this build issue by also including lodash explicitly in my package.json file.

**Comment by bobylito** [comment]
Hi @scneptune we've reverted the rollup related changes. Is it good for you?

**Comment by scneptune** [comment]
Yes thanks for your help.
