### ISSUE TITLE
Facet conjunctive inside array of options

### ISSUE THREAD

**Issue by gpassarelli** [algolia/algoliasearch-helper-js#492]
Sorry if the title was't clear enough and not even sure if here is the right place to post my question, but I'm trying to implement something and I'm struggling a little bit to understand how to do that.

So I have a set of records that has an attribute of an array of "accommodations" like so:

```js
"accommodations" : [{
    "id" : 3,
    "name" : "Casa de Família",
    "housing" : "Casa de Família",
    "roomType" : "Individual",
    "meal" : "Café da Manhã ",
    "bathroom" : null,
    "durations" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 50, 52, 56, 30, 15, 14, 13, 25, 19, 21, 23, 42, 35, 22, 18, 17, 26, 27, 29, 33, 34, 43, 31, 37]
  }, {
    "id" : 562,
    "name" : "Casa de Família",
    "housing" : "Casa de Família",
    "roomType" : "Individual",
    "meal" : "Café da Manha e Jantar",
    "bathroom" : null,
    "durations" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 50, 52, 56, 30, 15, 14, 13, 25, 19, 21, 23, 42, 35, 22, 18, 17, 26, 27, 29, 33, 34, 43, 31, 37]
  }, {
    "id" : 4,
    "name" : "Apartamento Estudantil",
    "housing" : "Apartamento Estudantil",
    "roomType" : "Duplo",
    "meal" : "Sem Refeição",
    "bathroom" : "external-shared",
    "durations" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 50, 52, 56, 30, 15, 14, 13, 25, 19, 21, 23, 42, 35, 22, 18, 17, 26, 27, 29, 33, 34, 43, 31, 37]
  }, {
    "id" : 5,
    "name" : "Apartamento Estudantil",
    "housing" : "Apartamento Estudantil",
    "roomType" : "Individual",
    "meal" : "Sem Refeição",
    "bathroom" : null,
    "durations" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 50, 52, 56, 30, 15, 14, 13, 25, 19, 21, 23, 42, 35, 22, 18, 17, 26, 27, 29, 33, 34, 43, 31, 37]
  }, {
    "id" : 1148,
    "name" : null,
    "housing" : "Hostel DMI",
    "roomType" : "Compartilhado",
    "meal" : "Sem Refeição",
    "bathroom" : null,
    "durations" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 50, 52, 56, 30, 15, 14, 13, 25, 19, 21, 23, 42, 35, 22, 18, 17, 26, 27, 29, 33, 34, 43, 31, 37]
  }],
```

And my attributes for faceting includes:

```js
[
'accommodations.durations',
'accommodations.name',
'accommodations.housing',
'accommodations.roomType',
'accommodations.meal',
'accommodations.bathroom',
]
```

I'm able to filter by those options, but if I select my facet `accommodations.housing` for the value of "Apartamento Estudantil" it will keep showing that my `accommodations.meal` has the option of "Café da Manha e Jantar" when that option is only available for the  "Casa de Família" option as `accommodations.housing`.

Did I make myself clear? Is it possible to make this work? When I select  select my facet `accommodations.housing` for the value of "Apartamento Estudantil" only display the option of "Sem Refeição" for my `accommodations.meal` facet?

Thanks

**Comment by gpassarelli** [comment]
Hi Guys, I'm still with this problem. I was already asked in the Algolia Forum but didn't get any response either. Is it possible to do this that I'm trying or not?

I saw a suggestion to transform each of this accommodation option as a separate record and use the distinct option, but as I have many options of accommodations it would ending up with a lot of records, and I would like to avoid this.

So I would really appreciate if anyone could help me out.

Thanks

**Comment by Haroenv** [comment]
It's a better option to use multiple records and use distinct I think. I can't really think of a workaround that works well. Algolia is designed for more, but less nested objects.

**Comment by Haroenv** [comment]
Please open a new issue if you still have this :)
