### ISSUE TITLE
Search multiple dates ranges

### ISSUE THREAD

**Issue by cmalard** [algolia/algoliasearch-helper-js#499]
Hi there,

I'm developing a widget to filter on dates.
So I added to our index Unix dates to stick to your engine. In this way, I search from midnight to midnight.

I would like to be close to a classic refinementList, possible values ​​are:
- today
- yesterday
- tomorrow
- Last 7 days
- Next 7 days

I want to be able to select several of these values ​​in OR / disjunctive mode.

I found #429 to guide me. It suggests using `setQueryParameter()` directly.
For today or yesterday, I create a request like that:
> Filters: date >= 1491775200 AND date <= 1491861599 OR date >= 1491688800 AND date <= 1491775199

But... I do not get the expected results, it seems that there is no priority of AND over OR.
So I tried to add parentheses to link the AND to each other, but I got this error:
> filters: filter (X AND Y) OR Z is not allowed, only (X OR Y) AND Z is allowed

Do you have a clue?

~~I'm thinking of another option: skip h/m/s dates, which would allow me to directly search with `addNumericRefinement()` by providing a table of dates (or `addDisjunctiveFacetRefinement()` if I want a hits counter).
I would lose precision on the dates, but that won't hinder me for now, I don't plan to do research on the hours of the "-24h" type.~~ Not viable with time zones.

Thanks ! :-)

Edit: I realize I only have this issue because I want to handle `yesterday` + `tomorrow`.
For now, I will simply make this case impossible, so I can have just 1 range and not 2.

**Comment by bobylito** [comment]
Thanks @cmalard for opening the issue, if algolia/instantsearch#5722 was solved would that solve your issue?

**Comment by cmalard** [comment]
I do not think, because the issue is to search different dates ranges, so numbers have to be linked specifically.
*I want "this" dates range (interval of 2 dates) OR "that" one.*

But this is no longer a need for me, you can close it :-)

**Comment by bobylito** [comment]
Ok thanks, let's reopen if need happens again 👍 Thanks for your time @cmalard
