### ISSUE TITLE
serverUsed doesn't seem to be provided by default

### ISSUE THREAD

**Issue by Haroenv** [algolia/algoliasearch-helper-js#500]
https://github.com/algolia/algoliasearch-helper-js/blob/develop/src/SearchResults/index.js#L295

https://community.algolia.com/algoliasearch-helper-js/reference.html#searchresults

http://codepen.io/Algolia/pen/AXbmEX doesn't show it

also mentioned in https://www.algolia.com/doc/api-client/javascript/search/#fields

EDIT: it's needed to set [getRankingInfo](https://www.algolia.com/doc/api-client/javascript/parameters/getRankingInfo/) for this to work, but I don't see that in the doc of the helper, nor how to do it 😄 

EDIT 2: `.setQueryParameter('getRankingInfo', true)` does the job, this should be mentioned.

**Comment by bobylito** [comment]
That's a good point 👍
