### ISSUE TITLE
searchQueueEmpty should be emitted after error if an error occured

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-helper-js#502]
Currently, if an error occurred, the searchQueueEmpty event is triggered before the error event.

In my use case, I try to wrap the helper in a promise, and I listen to the searchQueueEmpty event to determine if I should resolve the promise. I also listen to the error event to reject it.

Given searchQueueEmpty is always triggered before the error event, I'm unable to catch the error.

**Comment by bobylito** [comment]
What is the benefit to transform the events into promises? The semantic is very different and I'm not sure it fits the usage of the JS Helper. Also why do you need to check if there is a pending search?

**Comment by vvo** [comment]
> In my use case, I try to wrap the helper in a promise

What would help is you to explain the context and usecase before we speak about the failed implementation of wrapping into a Promise.

Maybe there's a feature to be added too.

**Comment by rayrutjes** [comment]
See #504

**Comment by bobylito** [comment]
Released in 2.21.1
