### ISSUE TITLE
Provide a method/event to determine if refinements have changed

### ISSUE THREAD

**Issue by timkelty** [algolia/algoliasearch-helper-js#506]
It would be useful to be able to easily determine if refinements have changed between the current results and the last results.

My use case for this: I'm progressively adding markers to a map with each `result`, but once the search is refined, I need to clear them.

Here's how I did it:

```
    helper.on('result', (results) => {

      // Determine if the refinements have changed,
      // We need to remove `count`, since that changes.
      let refinements = results.getRefinements().map((item) => _.omit(item, 'count'));
      
      if (lastRefinements && !_.isEqual(lastRefinements, refinements)) {
        clearMapMarkers();
      }

      addMapMarkers();      
      lastRefinements = refinements;
    });
```

Ideally, something like a `refine` event could be triggered, so I could just do something like this:
```
    helper.on('refine', (results) => {
        clearMapMarkers();
    }
```

**Comment by Haroenv** [comment]
Is that not the `change` event? https://community.algolia.com/algoliasearch-helper-js/concepts.html#event-based

**Comment by timkelty** [comment]
@Haroenv there is, but in this case the change event is firing as someone is moving the map (eg changing `insideBoundingBox` values) but no refinement is happening.

**Comment by Haroenv** [comment]
aha, but that would trigger `refine` too, am I right? Anyway, you could do a check in `change` like you do in `result` and clear then. I don’t fully understand when you’d expect `refine` to be called compared to `change`

**Comment by timkelty** [comment]
> aha, but that would trigger refine too, am I right

Well, I guess I'm saying no, only because the geo refinements don't appear in `results.getRefinements` (which is slightly confusing and maybe a separate issue).

**Comment by timkelty** [comment]
> Anyway, you could do a check in change like you do in result and clear then.

So yes - I could do a check in change, but I'd still have to the awkward comparison of `results.getRefinements()`, stripping out the `count` prop.

**Comment by Haroenv** [comment]
Geo is tracked in algolia/instantsearch#5726, but I think I get your issue now. I’m not sure this is something that can be fixed fast, but maybe @bobylito has suggestions 😄

**Comment by timkelty** [comment]
@Haroenv no rush - what I have now works, just seemed clumsy :)

**Comment by Haroenv** [comment]
Thanks for letting know, and thanks for making issues, it’s very helpful!

**Comment by timkelty** [comment]
If you're weary of adding an event, it might also make sense as just a method of SearchParameters, so something like:

```
helper.on('change', function(state, lastResults) {
  if (state.refinementsHaveChanged()) {
    clearMapMarkers();
  }
});
```

**Comment by timkelty** [comment]
Or maybe even `state.getLastRefinements` to get an array of refinements between the last search and this one.

**Comment by timkelty** [comment]
> but in this case the change event is firing as someone is moving the map (eg changing insideBoundingBox values) but no refinement is happening.

So after some testing, it appears this is NOT true. Altering geo params are NOT triggering `change`.

However, I explicitly want to do something when a _facet refinement_ happens. Using `change` fires on facet refinements, but _also_ on pagination, sort by selector changes...)

**Comment by Haroenv** [comment]
Aha, in that case, your check shared in the beginning *should* be the way to go for now I think

**Comment by timkelty** [comment]
In summary:
- It seems odd that geo param changes don't fire the `change` event.
- This FR is for an easier way to determine when _just a facet refinement_ has occurred.

**Comment by bobylito** [comment]
Am I wrong in saying that you want to know which part of the search parameters has changed? If so maybe the use of `change` with a method that would be able to extract the actual change would be good, no?

As for the geo parameters not triggering a `change` event that seems odd to me too. How do you set the geo parameters?

**Comment by timkelty** [comment]
> Am I wrong in saying that you want to know which part of the search parameters has changed? If so maybe the use of change with a method that would be able to extract the actual change would be good, no?

That sounds correct! In this case I would want to know if it was a facet refinement change (not pagination, geo...)

> How do you set the geo parameters?

```
helper
      .setQueryParameter(insideBoundingBox, mapBounds)
      .search()
```

**Comment by bobylito** [comment]
It seems similar to algolia/algoliasearch-helper-js#305 Don't you think @timkelty ?

**Comment by timkelty** [comment]
@bobylito yep, seems related.

As far as the diff part is concerned:
For my use-case, I wouldn't need a full _diff_ per-say...that is, I wouldn't be concerned about the values - just which parameters changed (and what type).

**Comment by bobylito** [comment]
I would say that the values would just be the by product here :)

**Comment by bobylito** [comment]
Ok I'll close this issue in favor of algolia/algoliasearch-helper-js#305. We'll reopen it if needed.
