### ISSUE TITLE
Implement the searchFunction hook in the Helper

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#507]
The idea of this proposal is to provide a way for any InstantSearch implementation to rely on a hook in the Helper to update the SearchParameters before they are sent to Algolia.

Pros of moving this feature to the Helper

 - Complete control over when the events are sent and the Helper lifecycle
 - Cleaner implementation

For now, the API is a function that you can set within InstantSearch.js configuration that will provide you with a fake helper that let you read the data and make the actual search. For mutating the state you have to work around and use the reference on the instantsearch instance. In v2, we are trying to move to a genuine helper.

If it was implemented in the JS Helper, it would make sense to reuse the function hook pattern. However I don't think that providing a helper in this context would make much sense, a SearchParameter would be fine (with a search function also, because users might want to control the search at this point: this is the original use case).

Another use that I have found recently is the ability to post pone the search while we do another search (eg. for implementing dynamic faceting, retrieving the meaninful facet first and then update the facet that we want to retrieve). That requires the availability of searchOnce and maybe searchForFacetValues. If we do not provide a Helper instance then we'd need to provide those as functions.

That's it for now :)

**Comment by vvo** [comment]
> a SearchParameter would be fine

Yes! So we can just do state.setPage(2).setQueryParameter(..).

> That requires the availability of searchOnce and maybe searchForFacetValues

That's the tricky part as for the API we would provide.

Do we know any other libraries using searchFunction for now but InstantSearch.js? Maybe they will need it at some point indeed, both React and Vue.

**Comment by bobylito** [comment]
> Do we know any other libraries using searchFunction for now but InstantSearch.js? Maybe they will need it at some point indeed, both React and Vue.

@mthuret @rayrutjes, maybe you could give us your point of view on that topic?
