### ISSUE TITLE
Use documentation.js to extract jsDoc information

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#508]
After experimenting with [documentation.js](https://github.com/documentationjs/documentation) on instantsearch.js in the v2 of the library, we have a usable plugin for the metalsmith build. This project offers some compelling advantage compared to the current tool:

 - built from the ground up to be used as a library for extracting jsDoc
 - flow compatibility
 - more traction / better maintained (to be monitored but still not a single contributor project)

Also doing this, we'll be able to revisit the structure of the documentation to offer more space for each aspect of the library and a more exhaustive experience.

 - [ ] Use / adapt documentation.js plugin used in instantsearch.js
 - [ ] Make a page per class so the content doesn't feel too bloated

**Comment by Haroenv** [comment]
would be useful, but we won't do any more changes on the doc website here.
