### ISSUE TITLE
Migrate to flow

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#509]
This library is now at the core of the InstantSearch libraries. Adding a type layer would contribute to make this critical piece of software sturdier and less buggy. The entry level for the usage of flow seems low and the compilation is just about removing the type annotations (it is fast). Also the tooling seems good. Bonus point, should integrate well with documentation.js.

**Comment by Haroenv** [comment]
We should migrate to typescript, but there's no need for an issue to track this. This can be done once the package is merged inside InstantSearch.js
