### ISSUE TITLE
Conjunctive facets aren't stored in a array

### ISSUE THREAD

**Issue by Jerskouille** [algolia/algoliasearch-helper-js#51]
It works fine except when facetting an array attribute.

**Comment by bobylito** [comment]
Thanks! :)

**Comment by redox** [comment]
This one is done, right?

**Comment by Jerskouille** [comment]
We have to release a new version for this, or we will break a lot of existing apps.

**Comment by bobylito** [comment]
Just to be sure @Jerskouille, what was the use case?

**Comment by Jerskouille** [comment]
Conjunctive facetting with ANDs : `tags:cat,tags:food`. Isn't this working now though?

**Comment by bobylito** [comment]
Let's make a test for that ;)

**Comment by bobylito** [comment]
Just to be clear, we need three things here : 
 - [ ] multiple parameters for single conjunctive facet stored in our SearchParameters
 - [ ] multiple parameters sent as the request
 - [ ] the facet values back in the response

**Comment by bobylito** [comment]
@redox @Jerskouille tests are in a PR #93 ;)

**Comment by bobylito** [comment]
Fixed with #93
