### ISSUE TITLE
Cleanup documentation stack

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#511]
I tried briefly to use flow, but some packages are so old and unmaintained that they contain dependencies that prevent the use of flow. Namely:

 - `zuul#firefox-profile#archiver` depends on `file-utils` which is not compatible because of a json file
 - `metalsmith-webpack` depends on `enhanced-resolve` which is not compatible because of a json file

This could be difficult as it could require to update / replace a big chunk of the stack

**Comment by vvo** [comment]
zuul =>
- I would now adivse to only test with jest and forget about trying to unit tests in ALL browsers
- I advise to then just do a functional test with webdriver.io and ensure a simple UI built with the helper is working as expected, that should be enough to be confident in releasing

metalsmith-webpack =>
they are doing a v2, which seems well ahead: https://github.com/christophercliff/metalsmith-webpack/issues/25
