### ISSUE TITLE
namespaced css class for matched term highlighting

### ISSUE THREAD

**Issue by t22james** [algolia/algoliasearch-helper-js#512]
Currently the `_highlightResult` returned by algolia will wrap `em` tags around any terms matching the search query. This makes styling very difficult when the native result also contains `<em>` tags.

Could you please add a namespaced classname to the html element you add so we can target the matches specifically? `<em class="algolia-highlight">` by default, or ideally, allow a classname to be passed as an option during `algoliasearchHelper` init.

Thanks!

**Comment by t22james** [comment]
infact, there will still be an issue if the matched term is *inside* an existing `<em>` tag... e.g.

`<em>Here is my <em>search term</em> which you matched</em>`
This will product invalid html...

as a further adjustment to the above suggestion, we could actually define the wrapping element in the init:

(default)
`highlightElement: '<em></em>'`

(leaving potential for)
`highlightElement: '<i class="my-highlight-class"></i>'`

**Comment by t22james** [comment]
ahh, apologies, this was simply not documented in algoliasearch helper itself, but is documented here: https://www.algolia.com/doc/guides/searching/highlighting-snippeting/#pre--and-post-tags

**Comment by bobylito** [comment]
Hi @t22james thanks for opening and managing this issue :)
