### ISSUE TITLE
Migrate to the upcoming V4 JS Client

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#521]
In the coming weeks, we will have a new v4 client. This issue is here to keep track of the changes that will be required (the idea is to reduce the time between the releases).

And this will be a major version.

Related issue in the JS Client: https://github.com/algolia/algoliasearch-client-javascript/issues/195

**Comment by Haroenv** [comment]
The major breaking changes will be: 

1. only Promises
2. methods that are deprecated in https://github.com/algolia/algoliasearch-client-javascript/pull/573
3. initIndex can be called from the main level too

For the rest you should be able to rely on the existing methods, with addition to being able to import single methods from the client, where then you'll pass on the reference to a `requester` (method that does the HTTP calls).

**Comment by Haroenv** [comment]
We’re gonna do this in a different way which won’t need as big migration strategy
