### ISSUE TITLE
Documentation doesn't list "filters" as a parameter for method "setQueryParameter"

### ISSUE THREAD

**Issue by graphographer** [algolia/algoliasearch-helper-js#528]
I had a moderately complex numeric filter requirement and couldn't find any way to do it with the search helper. After contacting Algolia technical support, I was informed of `searchHelper.setQueryParameter('filters', '...')`

I know it's in the API documentation (which is becoming increasingly difficult to find with the new site layout) but it's very difficult to connect the dots when the documentation makes it seems as though everything that can be done is listed.

**Comment by vvo** [comment]
@graphographer Hi, thanks, what were you expecting in term of documentation on the helper website? Maybe somewhere describing how to use this `filters` parameter?

**Comment by graphographer** [comment]
It would make sense to put it here:
https://github.com/algolia/algoliasearch-helper-js#query-parameters, with a
link to the full documentation in the API here:
https://www.algolia.com/doc/api-reference/api-parameters/filters/

I think the biggest confusion is that the documentation for the search
helper implies that the list given there is complete. If it is indeed not
complete, or is too much work to keep constantly up-to-date (if your API is
rapidly changing or something) the there should be a note to that effect,
and a link to the API reference (assuming that is kept more up-to-date).

**Comment by Haroenv** [comment]
`filters` was probably intentionally left out because it's supposed to be handled by the helper completely. You're right that it should be added here probably. cc @bobylito

**Comment by bobylito** [comment]
Well it was not left out on purpose. The list of all parameters is based on a old version of the API (that didn't have `filters`) and since now the JS Helper accepts parameters that are not in this list, we should probably make sure that it only reference helper specific parameters. Doing so we should link the full API reference and explicitly state that it accepts any of those. WDYT @Haroenv @vvo ?

**Comment by Haroenv** [comment]
We probably should link to the doc, that way it won't get outdated in the future
