### ISSUE TITLE
What about numeric facettings ?

### ISSUE THREAD

**Issue by Jerskouille** [algolia/algoliasearch-helper-js#53]
Right now, if we want a slider, we have an issue : a `disjunctiveFacet` doesn't ignore the `numericRefinements` on itself, which could make sense in some cases, but kills the whole idea of using facetting for this since the facet stats which come back take into account the newly created `numericRefinements`. How do we handle it ?
This question might also bring the same question with `facetsExcludes`, but I'm pretty sure that I we exclude a value from a disjunctive facet, we really don't want it at all.

**Comment by redox** [comment]
I've the impression that ignoring the `numericRefinements` while building the disjunctive facet queries would only allow someone to use the same numerical attribute both as a disjunctive facet and as a filter: which I've the feeling is not very common.

I would start by having  `{add,remove,toggle}NumericRefine` like we have for the rest and use it while building the disjunctive facet parameters.

**Comment by Jerskouille** [comment]
For the record, to avoid the caveat exposed by Sylvain, we could also create a new type (e.g. `numericFacet`) that would only retrieve the `facet_stats` and ignore the `numericFilters` on itself.

It wouldn't need any of the `{add,remove,toggle}Refine`, since we would only need to apply `numericFilters` on it.

The pros of this would be a good differentiation that would avoid the caveat described above.
The cons are multiple : New type, really close name between `numericFacet` and `numericFilter` that might be hard to get for a new user.

**Comment by bobylito** [comment]
@redox actually we have in v2 {add, remove}numericRefinement (thanks to @maxiloc).

Personally, I don't feel comfortable to tell the users that they should use the disjunctive faceting to handle the numeric properties. It doesn't feel quite correct. Even though I agree, the mechanics provided by the disjunctive is something similar to what we want in the end.

I think it was you @redox who evoked the idea of having a slider parameter and I think it could make sense. I tend to think that would match the purpose here. It is very specific and thus would give us the opportunity to be very specific on the refinement api for that. The setters could set{max, min }Refinement( facet, value ) and setRangeRefinement( [min , max] ).

**Comment by redox** [comment]
Yes right @bobylito, it's indeed weird to play with disjunctive facets to display a slider. But it's not so simple because to fetch the min/max values of a numerical attribute, we're using the facets... so you mix facet & sliders at indexing time.

**Comment by bobylito** [comment]
OK let's try the simplest solution here : use the disjunctive facetting for numeric stuff. It's pretty straightforward to implement and if we get feedback saying it's confusing, we'll consider a better solution.

**Comment by bobylito** [comment]
I started the implementation in fix/53. Will add test.

**Comment by bobylito** [comment]
ping @Jerskouille @redox

**Comment by Jerskouille** [comment]
LGTM
