### ISSUE TITLE
save url redirect from searched product back to search result

### ISSUE THREAD

**Issue by LarsWith** [algolia/algoliasearch-helper-js#531]
I wonder if there is a way I can save the search url/query form a search result so I can pass that to a product page so the user can go back to the previous page with the search result displaying.

My website works like this.
A user lands on my landing page where he or she can browse/search for products,

Eg simple a simple query "Macbook" with a "addNumericRefinement" to search for specific price.

When the search result now shows up a user can click on one of the products and be redirected to the product page. But if the user now goes back (clicking on the back arrow in browser) the user will get redirected to the landing page again, but now the search results is gone, so how can I store the search paramateres in eg my url so the user doesnt have to make a new search each time.

**Comment by bobylito** [comment]
Yes you can store the current state of the search into the URL using the URL methods [provided by the helper](https://community.algolia.com/algoliasearch-helper-js/reference.html#url). I know you probably have already implemented your search already, but have you considered any of the instantsearch? Like [instantsearch.js](https://community.algolia.com/instantsearch.js/v2/) for agnostic web dev or [vue-instantsearch](https://community.algolia.com/vue-instantsearch/) or [react-instantsearch](https://community.algolia.com/react-instantsearch/)?

**Comment by LarsWith** [comment]
@bobylito I tried this:

```
searchIndex() {
      this.algoliasearchHelper.addNumericRefinement('state', '=', this.stateId);
      this.algoliasearchHelper.setQuery(this.query).search();

      var state = this.algoliasearchHelper.url.getStateFromQueryString(this.query);
      console.log(state);

    },
```

But I get the error: **Uncaught TypeError: Cannot read property 'getStateFromQueryString' of undefined**

Is there anyway to just update my browser url right away when I do a search? That way I dont have to pass the url between pages and can simply just hit the back button on the browser

**Comment by LarsWith** [comment]
@bobylito I also tried:

```
var state = this.algoliasearchHelper.getState();
      var qs = this.algoliasearchHelper.url.getQueryStringFromState(state);
      console.log(qs);
```

but that also return a error: **Cannot read property 'getQueryStringFromState' of undefined**

**Comment by bobylito** [comment]
> Is there anyway to just update my browser url right away when I do a search?

Yes that's the history API: https://developer.mozilla.org/en-US/docs/Web/API/History you should have a look at pushState and replaceState.

As for the location of the url namespace, it is on the factory of the Helper not on the instance.

**Comment by bobylito** [comment]
> Is there anyway to just update my browser url right away when I do a search?

Yes that's the history API: https://developer.mozilla.org/en-US/docs/Web/API/History you should have a look at pushState and replaceState.

As for the location of the url namespace, it is on the factory of the Helper not on the instance.

**Comment by LarsWith** [comment]
@bobylito I am so sorry but I do not understand.

Could you edit my `searchIndex()` function above to update or store the url?

**Comment by bobylito** [comment]
To access the url object you need to do: `algoliasearchHelper.url` not `this.algoliasearchHelper.url`.

And I'm sorry I can't give you a full implementation because this is quite advanced. However you can have a look at [how it is implemented in instantsearch.js](https://github.com/algolia/instantsearch.js/blob/develop/src/lib/url-sync.js).
