### ISSUE TITLE
Get non-paginated object IDs from SearchResults

### ISSUE THREAD

**Issue by timkelty** [algolia/algoliasearch-helper-js#532]
Not sure if this is possible, if not - consider it a FR!

I want to get an array of ALL matching (non-paginated) object IDs from the result.

```
helper.on('result', function(results) {
	console.log(results.nbHits); // 1000
	console.log(results.hits.lenth) // 10

	// Need an array of the objectIDs of ALL (non-paginated) hits
}
```

Is this possible without doing a secondary search?

**Comment by bobylito** [comment]
You will never be able to have all the matching records, but you should be able to retrieve all the  paginated results. You can use `attributesToRetrieve` ([reference](https://www.algolia.com/doc/api-reference/api-parameters/attributesToRetrieve/)) to limit the content of the hits to only the objectId and you can set `hitsPerPage` to 1000 (the maximum number of hits that you can retrieve with a search) ([reference](https://www.algolia.com/doc/api-reference/api-parameters/hitsPerPage/))

Hope this helps.

**Comment by Haroenv** [comment]
To get all data, you should use [browse](https://www.algolia.com/doc/api-reference/api-methods/browse/), but be careful in doing this in the frontend, because if you're using this API key there, you allow everyone to crawl your dataset

**Comment by timkelty** [comment]
@bobylito @Haroenv Thanks both of you.
The tricky part is I still need the paginated results as well (with other attributes).

I didn't figure there would be a good solution.
I guess I was hoping there was a `SearchResults.allHitIds` or something :)

To give some context, here's what I'm doing:

- Searching `trips` index (https://paddling.com/paddle/trips/).
  - 1000s of results, paginated 12/page
  - each record has a `locationsIds` attribute
  - after the initial search, I collect all the `locationIds` results, and search the `locations` index for those IDs, so that the locations are filtered with the same facets as the trips.
  - plot locations on map

The problem with this is only the `locations` from `trips.locationsIds` from the _currentPage_ are plotted. The desired result is to plot _all_ relevent `locations`, while still paginating `trips`.

I can only think of 2 solutions:
- index all the same facets I am using for `trips`, in my `locations` index. Unfortunately this pretty taxing coming from the CMS.
- create an alternate hits/pagination widget that always requested the maximum records (1000), but divided them by pagination. It would cache the results, and only make another request to Algolia when required (view records > 1000 in pagination)

Any other ideas are greatly appreciated!

**Comment by bobylito** [comment]
Since you're using the Helper you can go on and the derived helper. Use your main helper as you would normally, and create a derived one that will used to plot records.

```js
var mapHelper = helper.derive(function(state) {
  return state.setQueryParemeter('page', 0)
              .setQueryParameter('hitsPerPage', 1000)
              .setQueryParameter('attributesToRetrieve', ['_geoloc', 'name', /*...*/]
});

mapHelper.on('result', function() {
  // update the map
});
```

The derived helper will be on sync with all the parameters that are set in the main helper and the main helper will trigger the search.

**Comment by timkelty** [comment]
@bobylito Yep - that's what I was doing previously…that works great for the geo bit, but the part about that that _doesn't_ work is the facets/attrs that are part of `trips` but not `locations` (the facets in the sidebar).

So, to make it work with a derived helper, I'd have to also index all those attrs used in facets for `trips`, in the `locations` index.

**Comment by timkelty** [comment]
So here's a simplified version of what I'm now doing (which works). The only issue is it make 3 queries to Algolia. Not sure if theres a way around that.

1. the initial (paginated/limited) trips request
2. the derived (1000 this) trips request
3. the resulting locations request

Do derived helper operations still count separately against your quota?

```
import searchHelper from 'algoliasearch-helper';

const locationsHelper = searchHelper(algoliaClient, 'locations', {
  hitsPerPage: 1000,
  disjunctiveFacets: ['outfitterIds', 'id'],
});

const derivedTripsHelper = helper.derive((state) => {
  return state
  .setQueryParameter('hitsPerPage', 1000)
  .setQueryParameter('attributesToRetrieve', ['locationIds']);
});

derivedTripsHelper.on('result', function(results) {
  if (results.nbHits) {

    getLocationIds(results.hits).forEach((id) => {
      locationsState = locationsState.addDisjunctiveFacetRefinement('id', id);
    });

    locationsHelper.setState(locationsState);
    locationsHelper.search();
  }
});
```

**Comment by bobylito** [comment]
You can't avoid making requests. I've asked @Haroenv if we could have a request-level cache in the JS client (since he's rebuilding it completely) so that might make the same request not being done (because they would be cached). But that's not there yet.

What is `derivedTripsHelper` derived from?

PS: Also on a side note, we have a new pricing that has unlimited search queries, so the number of queries would not matter (if you choose to switch to it which is obviously not automatic if you're satisfied with your current pricing)

**Comment by timkelty** [comment]
`derivedTripsHelper` is derived from the initial paginated `trips` search.
In this case, we are inside the `init` method of a custom InstantSearch widget (I updated the code above).

Good to know about unlimited queries, I'll investigate!

**Comment by Haroenv** [comment]
Not completely sure that cache is going to get there though, discussion at https://github.com/algolia/algoliasearch-client-javascript/issues/601

**Comment by timkelty** [comment]
Yeah I don't think so either, but thanks, I'll monitor that thread.

Really, to get what I'm after, it seems like I'd have to always request 1000 hits and have the `hits` and `pagination` widget limit the display and offset based on a different param.
