### ISSUE TITLE
Does algolia helper js have any function to update url based on search?

### ISSUE THREAD

**Issue by LarsWith** [algolia/algoliasearch-helper-js#533]
I am using the algolia js helper, the only problem is that its based on ajax so once I do a search my url bar doesnt change. This means that if I click on one of the displayed search results and go into a new page I cant go back to the previous page with the search result I just did displaying, I must search for the same item again. So does algolia have any function to update the url in the browser to match the search result so it can re-search the same again when going back.

So far I have tried this, doing a search for "test" :

```
searchIndex() {
      this.algoliasearchHelper.addNumericRefinement('time', '>=', moment().unix());
      this.algoliasearchHelper.setQuery(this.query).search();

      var qs = algoliasearchHelper.url.getQueryStringFromState(this.algoliasearchHelper.getState(['query', 'attribute:*']));
      console.log(qs);
      console.log(algoliasearchHelper.url.getStateFromQueryString(qs));
    },
```

This will output:

**q=test&nR[time][>=][0]=1505758418
searchpagevue.js:304 {query: "test", numericRefinements: {…}}**

Should I update my browser url to **q=test&nR[time][>=][0]=1505758418** so I can read that url once I go back?

Thanks

**Comment by Haroenv** [comment]
Yep, you can do: 

When a refinement is set: 

```js
var state = helper.getState(["query", "attribute:*"]);
var qs = algoliasearchHelper.url.getQueryStringFromState(state);
history.pushState(state, "the page title", "index.html?" + qs);
```

On page load:

```js
var qs = location.search.substring(1); // get rid of the `?`
var state = algoliasearchHelper.url.getStateFromQueryString(qs);
algoliasearchHelper.setState(state);

// or if this is the initialisation, you can do: 

var helper = algoliasearchHelper(state);
```

Hope that helps!

By the way, you can also check out [instantsearch.js](https://community.algolia.com/instantsearch.js/v2/) which is able to deal with urlSync with a simple [option](https://community.algolia.com/instantsearch.js/v2/instantsearch.html#struct-InstantSearchOptions-urlSync)
