### ISSUE TITLE
how do I know what filters I can use in getState()

### ISSUE THREAD

**Issue by kiwo12345** [algolia/algoliasearch-helper-js#534]
I was viewing the docs for `getState();`

and it said this about the filters: _optional filters to retrieve only a subset of the state_

So where can I find out what filters I can use and how I should spell the name?

I needed to print out my text query together with my numeric refinements and my current page in the pagination and index name. I wasnt sure if the pagionation was named p or page but I tried this which seems to work:

`getState(['query', 'attribute:*', 'page', 'index']));`

So where can I find what filters I can use and how I should spell their name?

**Comment by bobylito** [comment]
The attributes are what can be in the SearchParameters. And the SearchParameters can have anything from the [Algolia search API](https://www.algolia.com/doc/api-reference/api-parameters/). The SearchParameters also contains some special keys that do not exist in the Algolia API, those are for [managing the filters](https://community.algolia.com/algoliasearch-helper-js/concepts.html#managed-parameters). You can get the filters per attribute of your records using `attribute`. 

We've encountered the issue recently with the doc and we're thinking about doing a big revamp of the parameters so the parameters are more clearly defined.

**Comment by Haroenv** [comment]
resolved by removing the feature in https://github.com/algolia/algoliasearch-helper-js/pull/707
