### ISSUE TITLE
Prettier with getQueryStringFromState()

### ISSUE THREAD

**Issue by kiwo12345** [algolia/algoliasearch-helper-js#535]
Is there any way to get prettier with `getQueryStringFromState()`?

This `var qs = algoliasearchHelper.url.getQueryStringFromState(algoliasearchHelper.getState(['query', 'attribute:*', 'page', 'index']));`

Will output: **q=sdf&idx=inc_test&p=0&nR[time][>=][0]=1505821124&nR[price][<=][0]=1234**

Its the numeric refinement that doesnt look that good in my url later eg **[price][<=][0]=**

**Comment by Haroenv** [comment]
you can use the mapping object in the options of `getQueryStringFromState` as described here: https://community.algolia.com/algoliasearch-helper-js/reference.html#algoliasearchHelper.module:url.getStateFromQueryString

does that help you?

**Comment by kiwo12345** [comment]
@Haroenv should it be `getState(['query', 'price:price', 'page', 'index']));` then or am I mapping it wrong?, also how do I then set the state again from a custom mapping?

**Comment by bobylito** [comment]
Well getState returns an object that can be used directly either in setState or in the constructor of the helper. Using getState let you filter the part of the state you're interested in. For example you might want to not get nbHits if it's hardcoded in your js.

Then for creating a URL you can use [qs](https://www.npmjs.com/package/qs) and create some mapping to and from the substate you got from `getState`. The process would be:

For settting a URL:
 - `getState`
 - transform the state into a url (this you have to make your own)
 - set the URL (here use the browser API)

For reading a URL:
 - read the URL (here use the browser API)
 - transform the URL into a state (this you have to make your own)
 - `setState` or `algoliasearchHelper(client, index, state)`
