### ISSUE TITLE
attributesToHighlight in getState()

### ISSUE THREAD

**Issue by kiwo12345** [algolia/algoliasearch-helper-js#536]
I wonder if there is any way to keep the setting for `attributesToHighlight` when using the `getState()` function.

I tried: `getState(['query', 'attribute:*', 'page', 'hitsPerPage', 'attributesToHighlight', 'index'])` but `attributesToHighlight` doesnt get saved in the state, so when I reload the page from the saved state `attributesToHighlight` gets reset.

When I first init my helper I am forced to set `attributesToHighlight: []` since Algolia will highlight result by default and there is no way to turn this off in the dashboard

**Comment by Haroenv** [comment]
You should be able to do `index.setSettings({attributesToHighlight:[]})` as a way to avoid having to do that multiple times. You can only do this with the admin api key. For example you could make a quick node script to do that.

**Comment by bobylito** [comment]
You can also configure that [in the dashboard](https://www.algolia.com/explorer/display/).

**Comment by kiwo12345** [comment]
@bobylito no, I can only add attributes to highlight, it will by default always highlight the title/text search.

**Comment by bobylito** [comment]
<img width="916" alt="screen shot 2017-09-20 at 17 46 40" src="https://user-images.githubusercontent.com/393765/30653558-b0af61b8-9e2b-11e7-90fe-6e40bf3c32ad.png">

Well then there might be a bug. Can you send us a link to a [jsFiddle](http://jsfiddle.net) in which we can see the issue?

**Comment by kiwo12345** [comment]
@bobylito My code looks like this:

If `window.location.hash` doesnt exist it works fine. But if it does and I use `setState()` the result will highlight my "title" row

```
var _this = this;
    this.client = algoliasearch('x', 'x');
    this.algoliasearchHelper = algoliasearchHelper(this.client, 'xx', {
      attributesToHighlight: [],
      attributesToRetrieve: ["x", "x", "x", "x", "x", "x"],
      hitsPerPage: 20
    });

    if (window.location.hash) {
      var qs = window.location.hash.slice(1);
      this.algoliasearchHelper.setState(algoliasearchHelper.url.getStateFromQueryString(qs));
    } 

    this.algoliasearchHelper.search();
```

**Comment by bobylito** [comment]
I don't understand your issue @kiwo12345 

When I do:

```js
    var client = algoliasearch('latency', '6be0576ff61c053d5f9a3225e2a90f76');
    var helper = algoliasearchHelper(client, 'bestbuy', {
      attributesToHighlight: [],
      hitsPerPage: 20
    });

    console.log(helper.getState(['attributesToHighlight']));
```

I have an object with `attributesToHighlight`. Is your issue the fact that the attributesToHighlight gets overriden when using setState? This is the behaviour of [setState](https://community.algolia.com/algoliasearch-helper-js/reference.html#AlgoliaSearchHelper#setState).

**Comment by kiwo12345** [comment]
@bobylito Yes, `setState` overrides it, Okey

**Comment by bobylito** [comment]
Yes. You can use `setQueryParameter`.
