### ISSUE TITLE
.on('result') and .on('change') difference

### ISSUE THREAD

**Issue by kiwo12345** [algolia/algoliasearch-helper-js#537]
What is the difference between ` .on('result') `and `.on('change')` because I can only access my vueJS component when using `.on('change')`

Using in vueJS:

```
mounted() {
   var _this = this;
    this.algoliasearchHelper.on('result', function(data) {
      console.log(_this.$refs.paginate.selected); //Does not work, Cannot read property 'selected' of undefined
    });

    this.algoliasearchHelper.on('change', function(state) {
      console.log(_this.$refs.paginate.selected); //This works, I can access my component
    });

  },
```

`on('change');` Does work for me, however it gets called 7 times because of my numeric filters

**Comment by bobylito** [comment]
Hi there, it's documented [here](https://community.algolia.com/algoliasearch-helper-js/reference.html#algoliasearchhelper) and there is a diagram [here](https://community.algolia.com/algoliasearch-helper-js/concepts.html#event-based).
