### ISSUE TITLE
subsequent requests for disjunctive facets should use analytics=false

### ISSUE THREAD

**Issue by Haroenv** [algolia/algoliasearch-helper-js#540]
When we’re performing a disjunctive query, we’re sending two queries: one to generate the results, and a secondary one to generate the facet values (and potentially more than two queries if there are multiple disjunctive facets).

One issue that we have is that the secondary queries are present in the analytics, even though they shouldn’t.

The fix for this one is pretty easy: all of the secondary queries generated by the disjunctive facets should have the search parameter analytics=false (https://www.algolia.com/doc/api-reference/api-parameters/analytics/).

https://app.asana.com/0/214000806178027/442490537062541 (internal)

**Comment by Haroenv** [comment]
If I read it correctly, it needs to be added to this place? https://github.com/algolia/algoliasearch-helper-js/blob/develop/src/requestBuilder.js#L29

**Comment by bobylito** [comment]
Good catch!! :)

**Comment by bobylito** [comment]
We also need that for hierarchical facets.
