### ISSUE TITLE
Seems that attributesToRetrieve and attributesToHighlight are ignored completely

### ISSUE THREAD

**Issue by bhagwat** [algolia/algoliasearch-helper-js#55]
I tried with these options:

{
                "hitsPerPage": 12,
                "attributesToRetrieve":"nam1,field1,field2",
                "attributesToHighlight":"name"
}

The response contains all the fields irrespective of the specified fields: name, field1 and field2.

The query param does not contain the attributesToRetrieve param as well.

Any other way to set these attributes?

**Comment by bobylito** [comment]
Thanks @bhagwat, which version are you using?

**Comment by bhagwat** [comment]
Hi @bobylito . 
I am using this cdn.jsdelivr.net/algoliasearch.helper/1/algoliasearch.helper.min.js
Seems that it is using older version of algolia core api. I get this warning in Chrome developer tool:

algoliasearch: `client.startQueriesBatch()` was replaced by `client.search()`. Please see https://github.com/algolia/algoliasearch-client-js/wiki/Deprecated#clientstartqueriesbatch

**Comment by vvo** [comment]
@bhagwat About the depreciation message: this is only a warning and it does not relates with your current problem while using our helper.

We will answer to you about this particular problem very soon. Thanks.

**Comment by bobylito** [comment]
@bhagwat Do you a link to your implementation? It will make our investigation easier. Thanks :)
