### ISSUE TITLE
insideBoundingBox retrieved as strings from getStateFromQueryString

### ISSUE THREAD

**Issue by poulet42** [algolia/algoliasearch-helper-js#553]
When you populate your state from a query string and it contains a insideBoundingBox parameter, the search fails with 

> Invalid value for "insideBoundingBox" parameter, expected float

example :
`q=baguette&iBB[0][0]=51.1241999&iBB[0][1]=9.662499900000057&iBB[0][2]=41.3253001&iBB[0][3]=-5.559099999999944`

return 
`{
     ...,
     insideBoundingBox: [
       ["51.1241999", "9.662499900000057", "41.3253001", "-5.559099999999944"]
     ],
   }
`
so using the result directly in a `helper.setState` will fail.

would be great to either accept string representations of floats or transform the query string correctly.

**Comment by Haroenv** [comment]
Thanks for finding this! We actually preprocess some keys as numbers, but for some reason insideBoundingBox wasn't yet parsed as one, see the proposed fix in https://github.com/algolia/algoliasearch-helper-js/pull/554
