### ISSUE TITLE
Implement something like IN or LIKE or contains search with FacetFilters

### ISSUE THREAD

**Issue by gomesNazareth** [algolia/algoliasearch-helper-js#555]
I have a side filter in my project that uses the FacetFilter.
However FacetFilter searches on exact match but I need to implement something like IN or LIKE or contains search

Example

When I type Angular Universal . I should get results of all posts that have titles containing Angular or Universal or Both Angular Universal

Can anyone help me with this

**Comment by Haroenv** [comment]
You have two options here: 

```js
const query = 'angular universal';

helper
  .setQuery(query)
  .setQueryParameter('optionalWords', query)
  .search();
```

As described here: https://www.algolia.com/doc/guides/textual-relevance/optional-words/?language=js#treating-all-query-words-as-optional

The second option is to have `removeWordsIfNoResults: 'allOptional'` in your index settings. 

Feel free to reopen if needed.

**Comment by clevegomes** [comment]
@Haroenv  Thanks for replying and for the help. 
But the issue I have is that I want to search on particular field not  the full datable.

Example 
In the top query search I type "certified"
In the side filter for title I type "Angular Universal"
I should get a result of blogs having title containing "Angular" or "Universal" or "Angular Universal" and all blogs should have a word "certified" any where in the blog

Below is the sample prequest  

```

**Comment by Haroenv** [comment]
oh I see what you want now. In that case you should split up the query word by word manually, and do a disjunctive facet refinement with that value, does that make sense?
