### ISSUE TITLE
Additional parameter does not get added to request

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-helper-js#558]
```js
helper.searchForFacetValues("taxonomies.category", "", 30, {facetingAfterDistinct: true});
```

When inspecting the query, facetingAfterDistinct is not present.
When I add the parameter to the helper directly, then it works like expected.

**Comment by bobylito** [comment]
Sounds like a bug indeed. Thanks for the report @rayrutjes :)

**Comment by rayrutjes** [comment]
Just to be sure, the third parameter is called "userState", is that really supposed to accept custom query parameters?

I might have just mis-understood the signature there.

**Comment by rayrutjes** [comment]
This works like a charm in 2.23.2.
Thanks @bobylito !
