### ISSUE TITLE
Tests don't delete all indices

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/algoliasearch-helper-js#560]
It seems like the test suite create indices that are not deleted after the test ends. It results in a lot of indices left in the Algolia app.

Example: 
* _travis-algoliasearch-helper-js-809helper_searchonce1299
* _travis-algoliasearch-helper-js-807helper_sffv807
(numbers change but the rest of the name is always the same.

**Comment by bobylito** [comment]
Thanks for reporting this issue. I'll have a look. It is supposed to destroy them :/
