### ISSUE TITLE
Documentation link for Query Parameters Shortcuts does not work

### ISSUE THREAD

**Issue by akshayagarwal** [algolia/algoliasearch-helper-js#563]
All the references to Query Parameters Shortcuts on this page https://community.algolia.com/algoliasearch-helper-js/reference.html#parameters don't work.

I would be happy to create a patch if you can kindly point me to the correct link. 

Thanks

**Comment by akshayagarwal** [comment]
@Haroenv 

Sorry that link was mistaken. The correct link is https://community.algolia.com/algoliasearch-helper-js/reference.html#query-parameters 

In this section we have a line -> 'Before using those methods, be sure to check the shortcuts.' which contains a hyperlink to query parameter shortcuts. This hyperlink points to the URL https://community.algolia.com/algoliasearch-helper-js/query-parameters-shortcuts which returns a 404. 

Further, just below, in the setQueryParameter function documentation, there is again a hyperlink to query parameter shortcuts. The URL here is https://community.algolia.com/algoliasearch-helper-js/reference.html#query-parameters-shortcuts Unfortunately, although this URL exists, there is no section on this page with the id as 'query-parameter-shortcuts' hence clicking on this URL only leads us back to the same reference page. 

If you can kindly guide me regarding the correct URL of the 'query parameters shortcut' documentation, I can create a patch to update the URL of the above hyperlinks.

Thanks

**Comment by bobylito** [comment]
Having a look. Thanks for the details @akshayagarwal

**Comment by bobylito** [comment]
Ok so from what I can see of the actual state:
 - It should be an anchor
 - But no anchor is actually defined for shortcuts
 - Shortcuts are methods that let you avoid the usage of setQueryParameter or getQueryParameter.
 - Those methods are spread across different categories

Therefore the only that we can do to fix anything would be to remove the link itself. There are different places where it is mentioned:
 - https://github.com/algolia/algoliasearch-helper-js/blob/develop/src/algoliasearch.helper.js#L760
 - https://github.com/algolia/algoliasearch-helper-js/blob/develop/documentation-src/metalsmith/content/reference.md

Thanks for your help @akshayagarwal

**Comment by Haroenv** [comment]
What about adding an empty `<a name` for that hash?

**Comment by bobylito** [comment]
> What about adding an empty <a name for that hash?

The problem is that there is not a single place so you can't have a single anchor. Or am I missing something from your question @Haroenv ?

**Comment by Haroenv** [comment]
This feature no longer exists in the next version of the helper, so we don't need to fix the documentation site for it :)
