### ISSUE TITLE
Rendering server-side 

### ISSUE THREAD

**Issue by babgyy** [algolia/algoliasearch-helper-js#567]
I am trying to have an initial server-side rendering of search results in my search UI, built with **algoliasearch-helper-js**, **ReactJS**, and **Ruby on Rails** on the server (using **algoliasearch-rails** gem).

I have 2 problems : 
1. Support of server-side rendering 

algoliasearch-helper expects setTimeout and other browser-related functions to be present at initialization. I managed to [bypass some errors](https://github.com/reactjs/react-rails/issues/425) but not all and I am currently stuck. Is there any plan to support browserless initialization ? I am definitely not a JS expert, so please excuse me if I am talking nonsense or if this is an execJS issue only.

2. Is it possible to initialize the helper with a given API JSON response ?

More information : 
Server-side, thanks to the algoliasearch-rails gem (and its underlying ruby client), I am able to query the Algolia index and get the API JSON response.

Client-side, the algoliasearch-helper-js works flawlessly, but wraps the API JSON response with the SearchResults object. My React components uses it and its helper methods to display facets and hits, and trigger additional search queries.

When rendering server-side, I would like to feed my React component with the response payload from the algolia ruby-client, allowing it to render the hits and facets. I could have my React component work with the bare JSON response but I would rather make it work directly with the SearchResults object. However i didn't find any way to do this through the regular API.

I was able to build a SearchResults object
```
var algoliaResponsePayload = { hits: [...] } // API Response payload passed by Ruby
var helper = algoliasearchHelper(this.client, this.index, this.facets);
helper.setState(/* */); // Should probably set state to match the server side state when doing the request
var searchResult = new SearchResults(helper.getState(), algoliaResponsePayload)
```
Which works fine, but I am breaking through the API, and not sure what I am doing.

For the time being, I consider switching both workflows (results from ruby client & results from JS helper) to using the raw JSON response. That should make both problems go away but I can smell problems on the road as I plan to add search features. 

Thanks a lot for Algolia in general. It's amazing. And for your response.

**Comment by Haroenv** [comment]
Just a question, since you're using React, did you know about [react-instantsearch](https://community.algolia.com/react-instantsearch), it has SSR built-in

**Comment by bobylito** [comment]
Which engine are you using for running your code with the Helper? Also the code works on node since our full test suite runs on it.

**Comment by babgyy** [comment]
> Just a question, since you're using React, did you know about react-instantsearch, it has SSR built-in

I did not know about react instantsearch, i will look it up right now.

> Which engine are you using for running your code with the Helper? Also the code works on node since our full test suite runs on it.

I am not 100% sure I understand the question. 
As a JS Engine for SSR, I use Rails [ExecJS ](https://github.com/rails/execjs), which [clearly states it does not support all functions](https://github.com/rails/execjs#faq).

> It's not possible to initialize the helper with a result.

OK thank you for making it clear.

I will try with React InstantSearch, but I know already that I have to dummy-polyfill some functions such as setTimeout in order to load algoliasearch-helper from the execJS engine. 

Also I confirm that switching to using JSON raw responses was working fine but was getting more and more complicated as I was adding features such as hierarchical facets.

**Comment by bobylito** [comment]
> As a JS Engine for SSR, I use Rails ExecJS , which clearly states it does not support all functions.

It seems that execJS support multiple runtime. Amongst others it supports node.js, which has setTimeout. 

<img width="919" alt="screen shot 2018-03-23 at 15 56 11" src="https://user-images.githubusercontent.com/393765/37836448-bcdc21a2-2eb2-11e8-9e47-9d2d9ff1dfee.png">

So I thought it would be supported for some runtime.

I will close the issue for now, as it's beyond the usage of the Helper itself. Let me know if we can answer other questions.
