### ISSUE TITLE
Consistent returns in `extractNormalizedFacetValues`

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#568]
If an attribute is configured as a hierarchical facet and we don't find values for it, we return [undefined](https://github.com/algolia/algoliasearch-helper-js/blob/develop/src/SearchResults/index.js#L553) (returned by _.find when no values are found) instead of an empty array ([here](https://github.com/algolia/algoliasearch-helper-js/blob/develop/src/SearchResults/index.js#L565) and [there](https://github.com/algolia/algoliasearch-helper-js/blob/develop/src/SearchResults/index.js#L553))

This should probably be fixed because when the return value of this function is undefined then [the code throw an error](https://github.com/algolia/algoliasearch-helper-js/blob/develop/src/SearchResults/index.js#L647) saying that the attribute is not a retrieved facet.

related to https://github.com/algolia/angular-instantsearch/issues/99

**Comment by Haroenv** [comment]
done in #720
