### ISSUE TITLE
Need to implement multiple queries

### ISSUE THREAD

**Issue by pushpitab** [algolia/algoliasearch-helper-js#632]
Hi,

I want to implement multiple search queries one after another in sequence, my queries depend on the previous one. Any idea how I can do it algoliasearch-helper-js? Can I use Async-Await?
e.g, search for a user what are their "interests" and then for each interest what movies available? So I am trying to perform one search after the result comes back from the other.

Thanks,
PB

**Comment by Haroenv** [comment]
I think that would make more sense by using the JS client. The helper is meant for stateful searching, while it could be done by triggering new searches inside the results listener, it doesn't seem like the best option. What you can do is: 

```js
import algoliasearch from 'algoliasearch';
const client = algoliasearch('xxx', 'xxx');

const userId = 'xxx';

client
  .search([
    {
      indexName: 'interests',
      params: {
        facetFilters: ['user', userId],
      },
    },
  ])
  .then(({ results: [{ hits }] }) =>
    client.search([
      {
        indexName: 'movies',
        params: {
          // find all movies, related to the interests the user has
          filters: hits.map(({ movie }) => `tag:${movie}`).join(' OR '),
        },
      },
    ])
  );
```

does that make sense?

**Comment by pushpitab** [comment]
Thanks so much for the help I will try it out, I really would love to use algoliasearch-helper-js
If there is a solution using algoliasearch-helper-js please let me know.
Also, another question is:
If I have a list of interest and user id already cached can I do multiple searches in sequence with algoliasearch-helper-js?

**Comment by Haroenv** [comment]
you could likely do something with `helper.searchOnce(interests).then(res => helper.search(...somethign with res)`

**Comment by Haroenv** [comment]
Can you give the code you already have now? https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/javascript-helper is a template you can use now

**Comment by pushpitab** [comment]
To simplify I just created a list of interests. And with every interest, need to match Movie Genre and get a movies list. Hence I have to query multiple times. PSB the code snippet. Of course, this returns data in different order so I am not sure which interest returns which movies. Is there a way to find the query from search result data?

  for(var i=0;i<this.interest.length;i++){
                       this.loadData(this.interest[i],i);
    }

loadData(inerest,i){
     var client = algoliasearch('xx', 'xxx');
     var helper = algoliasearchHelper(client, 'MoviesGenre', {
        facets: ['movie']
      });
      helper
      .toggleFacetRefinement('movie', skill)
      .search();
      helper.on('result', function(data){
        console.log(data)
        console.log(data.hits);
      });

  },

**Comment by Haroenv** [comment]
Still not too clear what the issue was here, sorry for being late with responding. I think you got a response somewhere else so I'll close this issue
