### ISSUE TITLE
helper.toggleFacetRefinement("xx",xx).search() the callback doesn't not return any value

### ISSUE THREAD

**Issue by pushpitab** [algolia/algoliasearch-helper-js#638]
I am using helper.toggleFacetRefinement("xx",xx).search() and the callback does not return any value if the search criteria is not met. Should I use a random time out or is there a way to find out if the search has resulted in actual values or not?

**Comment by samouss** [comment]
I'm not sure to fully understood the issue. Could you provide a live example of your issue? It would help to better understand the issue. Here is [a template](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/javascript-helper) to avoid you the boilerplate part.
