### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by fujiii** [algolia/algoliasearch-helper-js#649]
Not sure if it's the place where one should inform about documentation typos, but I spent some time with blindly copied code snippet and my problem was simple typo.

Should be on RESULT instead of RESULTS.

[getFacetValues method](https://community.algolia.com/algoliasearch-helper-js/reference.html#SearchResults#getFacetValues)
helper.on('result<s>s</s>', function(content){

**Comment by Haroenv** [comment]
The source code of the docs is indeed here, please feel free to make a PR to fix that! 

By the way, is there any particular reason you use the helper, and not InstantSearch, is there anything we can improve that would make you switch?

**Comment by Haroenv** [comment]
this has been fixed in #699
