### ISSUE TITLE
Missing setter for search result page size

### ISSUE THREAD

**Issue by bhagwat** [algolia/algoliasearch-helper-js#65]
I did not find any documentation/sample on setting page size of search result. It will be great if someone creates a better documentation to make it more usable. For the time being I used the following workaround:

```javascript
helper.search(query, function (err, content) {/* callback */}, {hitsPerPage:12});
```

**Comment by bobylito** [comment]
Thanks @bhagwat! This is currently work in progress. It seems that you are using the version 1 of the helper. The new version v2 has been released and we are concentrating our efforts on this new version, especially documentation wise.
