### ISSUE TITLE
Seems that add/remove refinement is not functioning well

### ISSUE THREAD

**Issue by bhagwat** [algolia/algoliasearch-helper-js#71]
Hi guys,
I have been using these js files:

//cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"
//cdn.jsdelivr.net/algoliasearch.helper/1/algoliasearch.helper.min.js

It seems that add/remove refinements has stopped working well. It has been working well though in last week. Is the CDN content that I mentioned above has been changed? It might be the case that I started using multiple indexes for supporting search result supporting, but I have not been able to isolate the problem yet.

If needed I can share the server URL on email.

**Comment by bobylito** [comment]
@bhagwat Can I reach out to you with the email on your github front page?

**Comment by bhagwat** [comment]
Sure @bobylito . However I have changed the implementation to use version 2.0.0 and things are working fine after then (some code changes were required though).

**Comment by bobylito** [comment]
@bhagwat Oh have you had the chance to look at the migration guide? https://github.com/algolia/algoliasearch-helper-js/wiki/Migration-guide-:-V1-to-V2

**Comment by bhagwat** [comment]
@bobylito excellent documentation :) Well I managed to find sample code from the demo site http://algolia.github.io/algoliasearch-helper-js/examples/instantsearch+helper.html . We are planning to go live very soon. I will keep you updated, if you really want to see your code in action :)

**Comment by bobylito** [comment]
@bhagwat thanks! I will close this issue then. Keep us updated about your implementation either on the support chat or via hey@algolia.com, we'd love to see that :)
