### ISSUE TITLE
Cannot refine on several values of a conjunctive facet

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-helper-js#72]
Since V2, you cannot refine on several values of a facet anymore. This is possible as soon as you have a multi-valued attribute and want to AND several refinements.

Instead of
```javascript
m.facetsRefinements[ facet ] = value;
```

we need something like:
```
m.facetsRefinements[ facet ] = m.facetsRefinements[ facet ] || [];
m.facetsRefinements[ facet ].push(value);
```

**Comment by bobylito** [comment]
same as #51
