### ISSUE TITLE
Remove set of items from hits

### ISSUE THREAD

**Issue by soyzamudio** [algolia/algoliasearch-helper-js#744]
Hi guys, we have an array of hits and we are trying to filter the results by either of two conditions: `Completed` or `Not Started`

for `Completed` we have an array of the completed ids and we do:

`ids.forEach(i => this.algoliaHelper.toggleRefine('identifier', i));`

and this returns just the items that are completed.

for `Not Started` we want to basically do the opposite of `completed`, most items in the hits array are not started and we want to remove the completed ones so only the `not started` ones show up, but toggleRefine doesn't seem to do that.

Any help or suggestions?

Cheers!

**Comment by Haroenv** [comment]
The content of the comment doesn't really  make sense with the code you are doing. Are you trying to change the indexed data from the frontend? It'll be useful to see what you made so far. We have a template for working with the helper here: https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/javascript-helper
