### ISSUE TITLE
[Dependencies] Replace Lodash by direct method imports

### ISSUE THREAD

**Issue by loick** [algolia/algoliasearch-helper-js#745]
Half of the library's weight is lodash:
https://bundlephobia.com/result?p=algoliasearch-helper@2.28.0

What do you think about removing it from the dependencies and only adding the methods used in the library instead? (Especially for apps without tree shaking, might be useful)

**Comment by Haroenv** [comment]
This is the case for helper@canary, stay tuned for an upcoming stable release without lodash! I’ll close this issue because there are other issues about it
