### ISSUE TITLE
[3.0.0] getFacetStats does not seem to be working anymore

### ISSUE THREAD

**Issue by loick** [algolia/algoliasearch-helper-js#751]
Hi, 

I just migrated to the version 3.0, and it appears the function `getFacetStats` is not working anymore. I just moved the piece of code below from using `results` directly to `event.results`, and it works for everything but this function.

```helper.on('result', event => {
        const {
          disjunctiveFacets,
          hits,
          page,
          nbPages,
          nbHits,
          getFacetStats,
          facets: facetsResponse,
        } = event.results

        const mergedFacets = facetsResponse.map(facet => {
          const hasDisjunctiveFacet = disjunctiveFacets.find(
            f => f.name === facet.name,
          )
          return hasDisjunctiveFacet || facet
        })

        resolve({
          hits,
          page,
          nbPages,
          nbHits,
          facets: mergedFacets,
          stats: getFacetStats(FACET_PRICE),
        })
    })
```

Here is the error I get: 

```TypeError: Cannot read property '_state' of undefined
    at SearchResults.getFacetStats (/Users/loick/Documents/front/node_modules/algoliasearch-helper/src/SearchResults/index.js:733:12)
    at AlgoliaSearchHelper.<anonymous> (server.js:27818:19)
    at AlgoliaSearchHelper.emit (events.js:210:5)
    at AlgoliaSearchHelper.EventEmitter.emit (domain.js:476:20)
    at /Users/loick/Documents/front/node_modules/algoliasearch-helper/src/algoliasearch.helper.js:1270:12
    at Array.forEach (<anonymous>)
    at AlgoliaSearchHelper._dispatchAlgoliaResponse (/Users/loick/Documents/front/node_modules/algoliasearch-helper/src/algoliasearch.helper.js:1262:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Should I change the way I retrieve the stats? Thanks!

**Comment by Haroenv** [comment]
Hi @loick, `getFacetStats` did not get removed. Can you give the full stack trace as well as a reproducible example? We have a demo available here: 

https://codesandbox.io/s/javascript-helper-app-s2wy2

**Comment by Haroenv** [comment]
I wonder if:

https://github.com/algolia/algoliasearch-helper-js/blob/53c7c62f239bc53174bae79ec84812776da582dc/src/SearchResults/index.js#L688

should be:

```js
function getFacetStatsIfAvailable(facetList, facetName) {
  var data = find(facetList, {name: facetName});
  return data && data.data;
}
```

But this seems the case in v2 already too.

**Comment by loick** [comment]
it used to work on the V2, here it is breaking every time I try to access to the stats. I can give you a codesandbox, but I don't want to put my access key & id here. Where can I send it to you?

**Comment by Haroenv** [comment]
You can use the keys used in the example i sent

**Comment by loick** [comment]
Okay here it is, I get the same error: 

https://codesandbox.io/s/nice-wiles-u84zv?fontsize=14&hidenavigation=1&theme=dark

**Comment by Haroenv** [comment]
I'm surprised that this worked in v2, but you can't destructure a method, it needs to be called with `results` as the context: https://codesandbox.io/s/stupefied-montalcini-67z1u
