### ISSUE TITLE
addNumericRefine is addNumericRefinement?

### ISSUE THREAD

**Issue by reinaris** [algolia/algoliasearch-helper-js#77]
The readme says `addNumericRefine`.
But I cant find the function in the library.

Isn't it `addNumericRefinement`?

**Comment by vvo** [comment]
Yes @reinaris It's addNumericRefinement. I updated the docs.

**Comment by reinaris** [comment]
:+1: thanks! I wasn't sure so thats why I didn't update the docs myself :)

**Comment by vvo** [comment]
No prob, I only did a quick search in github and found out that no, we do not define addNumericRefine

**Comment by bobylito** [comment]
Thanks :)
