### ISSUE TITLE
Types Error:  An interface can only extend an object type or intersection of object types with statically known members

### ISSUE THREAD

**Issue by rubas** [algolia/algoliasearch-helper-js#774]
We see the following type error with TS 3.9 and 4

```
node_modules/algoliasearch-helper/index.d.ts(348,50):
TS2312: An interface can only extend an object type or
 intersection of object types with statically known members.
```
---

https://github.com/algolia/algoliasearch-helper-js/blob/develop/index.d.ts#L348

```
type SearchOptions = Client extends DummySearchClientV4
  ? SearchOptionsV4
  : SearchOptionsV3;

export interface PlainSearchParameters extends SearchOptions {}
```

> Interfaces can't extend conditional types because we can't know that all possible endpoints of a conditional type result in something that's legal to extend an interface from. For example, you can write interface I extends number { but you might have a conditional type that for some type resolves to number.
 [Source](https://github.com/microsoft/TypeScript/issues/23850#issuecomment-386194033)

**Comment by rubas** [comment]
@Haroenv - this becomes very relevant as soon as the @types/algoliasearch-helper package gets deleted.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43111

**Comment by Haroenv** [comment]
Hmm, this is confusing, since when we added that code no error showed up. @nunomaduro, do you have an idea for a workaround?

**Comment by nunomaduro** [comment]
cc @yannickcr 

@Haroenv Not sure. That was working in TS 3.8. 🙁

**Comment by yannickcr** [comment]
Must be a change between TS 3.8 and TS 3.9, I will try to find another way to do this so we can still be compatible with the client v3 and v4.
