### ISSUE TITLE
URL Helpers missing

### ISSUE THREAD

**Issue by alexcroox** [algolia/algoliasearch-helper-js#776]
The readme tries to link to URL Helpers which doesn't exist. I'm looking for this functionality, where can I find it documentated?

**Comment by Haroenv** [comment]
They no longer exist since v3. Are you using InstantSearch? In that case the routing is part of InstantSearch and no longer part of the helper. Thanks for noticing though, I'll remove it from the readme.

**Comment by alexcroox** [comment]
Oh right, I'll have to generate the URL myself then. I'm currently migrating away from InstantSearch as I ran into too many issues, I'm looking to take back more control by implementing this helper directly.

**Comment by Haroenv** [comment]
I understand, we'd love to understand what to improve to fir your use case fully again though. Would you want a call sometime to explain your full requirements so we can take this in account when making changes? haroen@algolia.com
