### ISSUE TITLE
2.0.2 and 2.0.3 point to 2.0.1

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-helper-js#79]
We forgot to build the dist files while tagging those versions.

**Comment by vvo** [comment]
Would be also good to have the building/releasing process in the "publish" page on hackpad

**Comment by bobylito** [comment]
:( Need to build and tag a new version then, because I don't think jsDelivr will be able to update itself if the tag is moved. @vvo I will update the docs.

**Comment by vvo** [comment]
Yes pushing a new patch version should do it, no big deal since no one should be using specific /2.0.1 /2.0.2

**Comment by pixelastic** [comment]
+1 for the release/build process on hackpad

Committing build files still feels weird to me, though.

**Comment by bobylito** [comment]
2.0.4 released yesterday with all the correct builds + hackpad docs up to date.
