### ISSUE TITLE
Mix ORs and ANDs in facetFilters

### ISSUE THREAD

**Issue by orditeck** [algolia/algoliasearch-helper-js#795]
Hi,

### Explanation

I have a multi-levels categories field on my objects, eg.:
```
{
  "categories_fr": {
    "lvl2": [
      "Niveau > Élémentaire > 1re année (6-7 ans)",
      "Niveau > Élémentaire > 2e année (7-8 ans)",
      "Niveau > Élémentaire > 3e année (8-9 ans)",
      "Matière > Les sciences et technologies > Chimie",
      "Matière > Les sciences et technologies > Structures et mécanismes",
    ],
    "lvl1": [
      "Matière > Les sciences et technologies",
      "Niveau > Élémentaire"
    ],
    "lvl0": [
      "Matière",
      "Niveau",
    ]
  }
}
```

In the Algolia dashboard, if I select two `categories_fr.lvl2` filters, it gives me this filter, which is resulting in a OR:
```
{
 "facetFilters": [
  [
   "categories_fr.lvl2:Niveau > Élémentaire > 1re année (6-7 ans)", // OR
   "categories_fr.lvl2:Matière > Les sciences et technologies > Chimie"
  ]
 ]  
}
```

If I manually change the query to the following, I now have a AND:
```
{
 "facetFilters": [
  [
   "categories_fr.lvl2:Niveau > Élémentaire > 1re année (6-7 ans)"
  ], // AND
  [
   "categories_fr.lvl2:Matière > Les sciences et technologies > Chimie"
  ]
 ]  
}
```

I can then mix ORs and ANDs.

---

### Question

Is there a way to do this using `algoliasearch-helper-js`?

So far, I can see that if I do this:
```
helper.addDisjunctiveFacetRefinement('categories_fr.lvl2', 'Niveau > Élémentaire > 1re année (6-7 ans)');
helper.addDisjunctiveFacetRefinement('categories_fr.lvl2', 'Matière > Les sciences et technologies > Chimie');
```
I'm gonna get the `OR` result as all `categories_fr.lvl2` get grouped.

What I'd like to do is something like
```
helper.addDisjunctiveFacetRefinement('categories_fr.lvl2', 'Niveau > Élémentaire > 1re année (6-7 ans)', 'list1');
helper.addDisjunctiveFacetRefinement('categories_fr.lvl2', 'Matière > Les sciences et technologies > Chimie', 'list2');
```

I'm gonna keep looking into the code the see if something in there could help me achieve that or if I have to create a custom query on my own.

**Comment by Haroenv** [comment]
Hi there, the helper doesn't have a way to mix disjunctive and non-disjunctive refinements unfortunately, since that would become too complicated for the count (facet count can only be done fully disjunctive or conjunctive, since it's not an engine feature per se). The way to go would be `setQueryParameter` with the `filters` parameter, since if you use any other disjunctive filter, that would override what actually happens with the facetFilters parameter

**Comment by orditeck** [comment]
Hi, thanks for the answer. I might re-evaluate the way we store our data then (might use "niveau" and "matière" as attributes, resulting in the expected behaviour).

Bonne journée d'un cousin Québécois :P

**Comment by Haroenv** [comment]
Bonne journée pour toi aussi :)
