### ISSUE TITLE
Cannot read slice of undefined

### ISSUE THREAD

**Issue by onhate** [algolia/algoliasearch-helper-js#799]
I followed the instructions for using `vue-instantsearch` but I'm getting this error, debugging the code I found out that actually there's no results on the response but instead there's hits, am I missing something?

```
Uncaught (in promise) Error: Unhandled error. (undefined)
    at InstantSearch.emit (events.js?aea8:142)
    at AlgoliaSearchHelper.eval (InstantSearch.js?3956:418)
    at AlgoliaSearchHelper.emit (events.js?aea8:153)
    at AlgoliaSearchHelper._dispatchAlgoliaError (algoliasearch.helper.js?bcc9:1286)
```

<img width="956" alt="2020-11-07 at 10 31 09@2x" src="https://user-images.githubusercontent.com/980905/98442638-9f846200-20fd-11eb-8529-e88d912ccb2f.png">

```
"algoliasearch": "^4.6.0"
"vue-instantsearch": "^3.4.2"
```

**Comment by Haroenv** [comment]
do you have this error live on a sandbox somewhere? I wonder if there would be mismatch in helper version or similar?. I can see `results` is undefined in the error, but that doesn't happen unless you would have manually set it up.

**Comment by onhate** [comment]
I just discovered that it only happens when I use `generateSecuredApiKey` on the server side and use that as api key, if I use the raw api key it works fine.

```
client.generateSecuredApiKey(apiKey, {
    restrictIndices: indexName
  });
```

**Comment by onhate** [comment]
actually, when I use `client.initIndex()` instead of directly using the client

```
createServerRootMixin({
        searchClient: client.initIndex(searchInfo.indexName),
        indexName: searchInfo.indexName
      })
```

**Comment by onhate** [comment]
it works without setting `initIndex`, I think I'm not supposed to do that anyways, or was it supposed to work with that config?

**Comment by Haroenv** [comment]
Ah, that's because the search index method has a search method, which doesn't have the same api as the client search, and thus doesn't have results. 

you should change it to just passing the client :)

**Comment by onhate** [comment]
thanks @Haroenv for the quickest responses ever I got on github issues :D
