### ISSUE TITLE
Cherry pick pre-v3 in js client master branch previous commits

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-helper-js#8]
Just in case, we need to ensure we cherry picked algolia/algoliasearch-client-js@b896bf33235d9f8d5093022a10e065aca4ea965 and algolia/algoliasearch-client-js@11cecaa349869b2054b4affdfd60398cad41bca1.

Commits were done on js client master branch after starting working on V3

**Comment by bobylito** [comment]
The first commit is missing :(

**Comment by bobylito** [comment]
The other has been integrated, the other is the object of #13
