### ISSUE TITLE
Typescript issues

### ISSUE THREAD

**Issue by march08** [algolia/algoliasearch-helper-js#812]
![Screen Shot 2021-02-23 at 11 11 55](https://user-images.githubusercontent.com/15802823/108829111-0f90f800-75c8-11eb-9315-1029311c4b4d.png)

Hey guys, who is maintaining the types? There are some issues with the exports here, using version `"@types/algoliasearch": "^3.34.11"`

Any way to resolve this?

**Comment by Haroenv** [comment]
could you make a reproduction to retrieve this error? Are you mixing @types/algoliasearch (v3) and algoliasearch (v4) possibly?

**Comment by Haroenv** [comment]
Will reopen with a reproduction, I can't see this issue myself, even with v3 algoliasearch
