### ISSUE TITLE
Proper way to modify SearchParameters on the AlgoliaSearchHelper object?

### ISSUE THREAD

**Issue by acechase** [algolia/algoliasearch-helper-js#84]
On initialization of my helper I am setting a couple geo params. My initialization looks like this:
```
var algolia = window.algoliasearch(window.ALGOLIA_APPLICATION_ID, window.ALGOLIA_SEARCH_API_KEY);

var algoliaHelper = window.algoliasearchHelper(algolia, 'metros', {
  hitsPerPage: 1,
  aroundLatLngViaIP: true,
  aroundRadius: 250000
});
```
Working with the helper as my primary object, what I do not understand from looking at the docs is how do I update values like aroundRadius? I cannot mutate the helper so I can't just do:
```
var s = helper.state;
s.aroundRadius = 10000000; // read-only attribute error
```

I would expect to see some type of "helper.state.setOption()" type of method, but I don't see anything like that. All the setters I see seem to apply specifically to facets.

I was able to get this to work using the mutateMe method on the state object, but that seems pretty low level. Is there a better way to do this?

My final code for updating the aroudnRadius param looks like this:
```
var searchState = algoliaHelper.state.mutateMe(function(state){
                    state.aroundRadius = 1000000;
                });
algoliaHelper.setState(searchState);
algoliaHelper.search('');
```

**Comment by redox** [comment]
Indeed, would be cool to have something like:

```js
  setQueryParameter : function setQueryParameter( param, value ) {
    return this.mutateMe( function( m ) {
      m[param] = value;
    } );
  },
```

What do you think @bobylito ?

**Comment by bobylito** [comment]
This is linked to #76 

We need to propose that kind of feature. We often end up modifying multiple parameters at once, so having something more general like a setPartialState would eliminate the intermediate state created by the multiple calls to setQueryParameters.

**Comment by redox** [comment]
`setPartialState` looks a bit techy to me; what about `setQueryParameter(param, value)` and `setQueryParameters(params)`?

**Comment by bobylito** [comment]
Sounds right!

**Comment by bobylito** [comment]
And what about `setQueryParameter( param, value )` and `merge( object )`?

**Comment by redox** [comment]
Maybe `merge` could be used internally on the `state` object but I prefer `helper.setQueryParameters` than `helper.merge`, what do you think?

**Comment by bobylito** [comment]
Ok let's do that! :)

**Comment by bobylito** [comment]
@acechase @redox made a PR for this issue, see if it fits you :)
