### ISSUE TITLE
Update version requirements to support algoliasearch 3.3.2?

### ISSUE THREAD

**Issue by acechase** [algolia/algoliasearch-helper-js#85]
Hi Guys,

I am using bower to install algoliasearch and algoliasearch-helper.

For algoliasearch I am using v3.3.2 and for algoliasearch-helper v2.0.4

algoliasearch-helper specifies algoliasearch v3.1.0 as its dependency. However, v3.3.2 seems to be compatible. Maybe it's worth widening the dependency version to include v3.3.2? Or maybe there's some incompatibility I'm not aware of?

```
Unable to find a suitable version for algoliasearch, please choose one:
    1) algoliasearch#3.1.x which resolved to 3.1.0 and is required by algoliasearch-helper#2.0.4 
    2) algoliasearch#3.3.2 which resolved to 3.3.2 and is required by eatwith-webPrefix the choice with ! to persist it to bower.json
```

On a tangential note - I've been implementing a new Algolia integration for my company (eatwith.com) and while doing so have also migrated our JS lib from the v2 version to v3. Really digging the updates to the library - kudos! :-D

Cheers,
Andrew

**Comment by bobylito** [comment]
AFAIK there are no incompatibilities. We'll update that for the next release :)
