### ISSUE TITLE
DisjunctiveFacetRefinements making multiple requests to algolia

### ISSUE THREAD

**Issue by varian97** [algolia/algoliasearch-helper-js#872]
Hi, I use algoliasearch-helper v. 2.28.0
I realized that algoliasearch make more than 1 requests if I use disjuntiveFacetRefinements, for example:

```javascript
  disjunctiveFacets: [
    'brand',
    'color',
  ],
  disjunctiveFacetsRefinements: {
    color: ['red'],
    brand: ['Brand1'],
  },
```

The network request shows 3 requests to algoia, 1 for retrieving the results and 2 more to build refinement lists.
The problem is, I don't need to build the refinement lists, how can I disable this?
I want to optimize my algolia search operations because at this rate, every months I always get charged for over-quota

By looking at the source code at https://github.com/algolia/algoliasearch-helper-js/blob/develop/src/requestBuilder.js
There is no parameter to contol whether the disjunctive facet should become query or not.
```javascript
_getQueries: function getQueries(index, state) {
    var queries = [];

    // One query for the hits
    queries.push({
      indexName: index,
      params: requestBuilder._getHitsSearchParams(state)
    });

    // One for each disjunctive facets
    state.getRefinedDisjunctiveFacets().forEach(function(refinedFacet) {
      queries.push({
        indexName: index,
        params: requestBuilder._getDisjunctiveFacetSearchParams(state, refinedFacet)
      });
    });

   .....
```

Thank you, hope to hear back from you.

**Comment by francoischalifour** [comment]
Hey! What are you using `disjunctiveFacetRefinements` for? Can you replicate what you have in this [sandbox](https://codesandbox.io/s/modest-framework-rolnf?file=/src/app.js) to see how we can achieve this?

Thanks!

**Comment by varian97** [comment]
Hi @francoischalifour 

I am working on a ecommerce site, we have a product detail page and we show product recommendations based on the current product opened by the customer. For example, if the product opened was a Sofa with blue color, we want to recommend another sofa with same color (for simplicity, assume we only consider color and categories), so we use disjunctive facet to filter such products. But turns out, there are multiple calls happened behind the scene as I mentioned earlier.

I have replicated my case on this sandbox https://codesandbox.io/s/sharp-wiles-747q6?file=/src/app.js
Please type something in the search bar and see the network. If there are `n` fields specified in `disjunctiveFacetRefinements` then the helper will make `n+1` calls to algolia.

![image](https://user-images.githubusercontent.com/15712645/134197282-d30870b4-d6e1-470f-8b5d-c0fbde7af615.png)

**Comment by Haroenv** [comment]
Note that three queries are done in a single network request, not three network requests. This isn't the same for cost-calculation
