### ISSUE TITLE
Keyboard closes on iOS 15.1

### ISSUE THREAD

**Issue by samjonesigd** [algolia/algoliasearch-helper-js#882]
I have the search function set when input length is greater than 2 in my input field.

This closes the keyboard on iOS 15.1 as they're typing when search results appear. It doesn't happen on previous versions.

Seems to be the setQuery function, if you remove this it does not happen.

**Comment by Haroenv** [comment]
Do you have a code snippet / sandbox? this library is not related to the keyboard

**Comment by samjonesigd** [comment]
Sorry was an old version of the helper. Updated and all good.
