### ISSUE TITLE
disjunction between same attribute and conjunction between different attributes

### ISSUE THREAD

**Issue by cmgchess** [algolia/algoliasearch-helper-js#886]
Hello,
I'm planning on implementing a filter.
Is it possible to setup the helper so that I can get disjunctive results within the same attribute and conjunctive results between different attributes. 

```
{
department: 'Dept 1',
person: 'Person 1'
},
{
department: 'Dept 2',
person: 'Person 1'
},
{
department: 'Dept 2'
person: 'Person 2'
}

```
My goal is to get the first 2 results. so I want to OR between departments and an AND with a person
(Dept 1 OR Dept2) AND Person1
is there a way to achieve this by initially configuring and then using `toggleRefinements`

I tried to set up the client with
`facets: ['person'],disjunctiveFacets:['department']` , Then it would perform an AND operation between persons as well which is not what I want.

Thanks.

**Comment by Haroenv** [comment]
If you want person to be disjunctive, department to be disjunctive, but conjunctive between them, that's done by default. The filters:

```
disjunctiveFacets: ["department", "person"],
disjunctiveFacetsRefinements: { department: ['a', 'b'], person: ['c', 'd']}
``

conceptually creates the filter: `(department:a or department:b) and (person:c or person:d)`
