### ISSUE TITLE
stray `implements` keyword in index.d.ts

### ISSUE THREAD

**Issue by sandersn** [algolia/algoliasearch-helper-js#897]
4e6ac6926bd284c7eafe060480fc4258844d121a adds an extraneous `implements` when adding another interface for SearchResults to implement:

https://github.com/algolia/algoliasearch-helper-js/commit/4e6ac6926bd284c7eafe060480fc4258844d121a#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8R1156

Four packages on Definitely Typed depend on algoliasearch-helper and I noticed this on the overnight run.

**Comment by Haroenv** [comment]
Oh, thanks!
