### ISSUE TITLE
Handling tags in the helper?

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#91]
We have an API to handle the tags. Right now, it's very bare bone (use of the most level apis, string based...). At the very least, we should have an API that  provides a basic add/remove/list the tags used for filtering : 

```javascript
helper.addTag( "tag" );
helper.removeTag( "tag" );
helper.listTags() // []
```

**Comment by redox** [comment]
I would go for `addTagRefinement`, `removeTagRefinement` (`getRefinements` or `getTagRefinements`) then because it's exactly like the facets & numerics.

**Comment by pixelastic** [comment]
I agree to keep the consistency with a set of `*Refinement` methods. Maybe
a `clearTags` also, to remove them all.

**Comment by redox** [comment]
So maybe here I would see the same logic than `getRefinements(attribute)` -> what about `clearRefinements(attribute)`:

```js
clearRefinements("_tags");
clearRefinements("my_facet_attribute");
clearRefinements("my_numeric_attribute");
```

Maybe that's only sugar on top of 4 `clearTagRefinements()`, `clearFacetRefinements(facet)`,  `clearDisjunctiveFacetRefinements(facet)` and `clearNumericalRefinements(attribute)`.

**Comment by bobylito** [comment]
Not sure about the clearRefinements _tag, i don't feel like it would be obvious for users that this is the attribute of the _tags because we don't have to specify it when manipulating tags.
