### ISSUE TITLE
Sorting using algolia helper

### ISSUE THREAD

**Issue by awais019** [algolia/algoliasearch-helper-js#952]
How can we sort results using algolia search helper.

**Comment by Haroenv** [comment]
Results are sorted by giving different sortBy rules. You can read more here: https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/

**Comment by awais019** [comment]
These are not working with helper

**Comment by Haroenv** [comment]
Yes, you set the different index that has the other sorting configuration set :)
