### ISSUE TITLE
Advanced tags filtering

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-helper-js#98]
Algolia API supports AND, OR and NOT filtering. How to provide a good API that easy to read, combine and manipulate?

In Flickr search, the provide a mode that let one query either in AND or OR mode. This does not provide any NOT feature. It is easy though and answer well the easiest cases for which you want to do either or and and filtering.

Maybe having a separate object for handling tag filters could be a solution, even though we ought to provide an object for or groups too... Just throwing some code here :

```javascript
var tagList = new TagList( "romantic", not( "horror" ) );
var orGroup = new OrGroup( "dinner", "musical" );
tagList.add( orGroup );
helper.setTagList( tagList );
//later...
var l = helper.getTagList();
var excludeTags = l.getExcludedTags();
excludeTags.remove( "horror" );
var orGroups = l.getOrGroups();
orGroups.first().remove( "musical" );
helper.setTagList( tagList );
```

This API wouldn't be enough or satisfying but that's some food for thinking...

This problem is definitely related to #35 with similar issues and API constraints.

**Comment by redox** [comment]
There is an open feature request in the API backend to support the parsing of boolean expressions -> I would stuck to that and wouldn't implement anything in the API clients.

We would do something like: `facetFilters: "(rating:1 OR rating:2) AND facility:wifi"`

**Comment by bobylito** [comment]
The input is the least problematic part here. How do you edit the current tag filters? How do you query those tags?

One thing that could help is a UI or any kind of software sample that uses the advanced combination of and or and negative tag capabilities. The way the user edit this kind of filter might give us an hint about how to do it properly.

**Comment by bobylito** [comment]
OK so let's make it simple : 
 - simple API for the common case, add remove etc with the support of not in the string (you prepend if you want the tag explicitly excluded) and support for two modes : and, or.
 - advanced API that let the programmer enter a string that matches the format proposed by the Algolia API. The uses are much more complex, so chances are that the user/programmer will know what it is doing.

One or the other API should have precedence, and I would say that once on the advanced you should not go back. Therefore I would make the advanced mode have the higher priority.

**Comment by bobylito** [comment]
```javascript
//simple mode
helper.setTagMode = "or"; // and by default
helper.addTag( "romantic" )
helper.addTag( "beach" );

// advanced mode
helper.setRawTagFilter( "romantic, ( sea, city ), -mountain" );
```

**Comment by redox** [comment]
I think that those advanced conditions are only applied programmatically, I would not go for anything else than your "advanced" API which is actually similar than `setQueryParameters("tagFilters", ".....")`.

Moreover, the facet & numeric filters also support those boolean expressions.

**Comment by bobylito** [comment]
OK agreed!
Don't you think that verifying the string would be a good idea ? Otherwise
we just have to make sure that if a user provides the parameters directly
using the setqueryparameters we don't override it with the simple API.

**Comment by redox** [comment]
We need to validate/verify that at the API level, otherwise it will be very difficult to maintain.

Yeah, ideally we would be able to "merge" the filters :/

**Comment by bobylito** [comment]
Hummm I'm interested in a strategy to merge the filters (tbh I have no idea which rules would make sense)
